### ISSUE TITLE
Publish to open-vsx.org?

### ISSUE THREAD

**Issue by hl2guide** [streetsidesoftware/vscode-spell-checker#1029]
Please consider publishing this extension to: https://open-vsx.org/

So that users of VSCodium can use it too.

**Comment by Jason3S** [comment]
@hl2guide,
It should already be there. [Code Spell Checker – Open VSX Registry](https://open-vsx.org/extension/streetsidesoftware/code-spell-checker)

**Comment by hl2guide** [comment]
ah ok, oops.
