### ISSUE TITLE
Support extensionKind "ui"

### ISSUE THREAD

**Issue by leighmcculloch** [streetsidesoftware/vscode-spell-checker#1033]
This extension currently only supports the "workspace" extensionKind. This means that the spell checker must be installed in dev containers to function.

VSCode now supports plugins registering with multiple extensionKinds, and it would be ideal if the extension could also run as a "ui" extension where it spell checks words in open files without having to run at the remote server.

**Comment by Jason3S** [comment]
I can see the desire for this to work.

It is possible to make it work in a limited fashion, but many of the features would not work because in UI mode, the extension does not have access to the files in the remote container.
