### ISSUE TITLE
choose which user dictionariy to add when there are multiple dicts declared in this setting: customUserDictionaries

### ISSUE THREAD

**Issue by PhungXuanAnh** [streetsidesoftware/vscode-spell-checker#1034]
```jsonc
"cSpell.customUserDictionaries": [
  {
    "name": "my words",     // name of dictionary (should be unique)
    "description": "These are the words I use in all projects.",
    "path": "~/custom-words.txt",
    "addWords": true
  },
  {
    "name": "company terms",
    "description": "These are terms used by my company.",
    "path": "~/gist/company-terms/company-terms.txt",
    "addWords": true
  }
]
```
If there are 2 custom dicts as above, It should be able to choose which dict to add word in Editor Context Menu (right-click)
How can I do that ?

**Comment by Jason3S** [comment]
@PhungXuanAnh,

Work is currently underway to make this possible. Currently VS Code makes it VERY difficult for an extension to have fine control over the Exit Context Menu. One option is to show a dialog asking which dictionary to add the word to.

The Quick Fix menu offers more options to Extension Developers. This is shown using `Cmd+.` or `Ctrl+.` depending upon your OS.

From the new version of the Extension:

![image](https://user-images.githubusercontent.com/3740137/125157171-9efb0a00-e169-11eb-9607-fec4b8fc073a.png)

![image](https://user-images.githubusercontent.com/3740137/125157185-b3d79d80-e169-11eb-977a-fc0543f806ff.png)


You can try a preview of the new version. See: [Releases · streetsidesoftware/vscode-spell-checker](https://github.com/streetsidesoftware/vscode-spell-checker/releases)

**Comment by PhungXuanAnh** [comment]
@Jason3S thank, I installed alpha version and confirm it worked. Could you please tell schedule release of this version, so I can install from market instead of vsix file

**Comment by Jason3S** [comment]
I hope to release it by the end of the month.

**Comment by Jason3S** [comment]
This should be fixed with the latest alpha release: [Release v2.0.1-alpha](https://github.com/streetsidesoftware/vscode-spell-checker/releases)
