### ISSUE TITLE
How to enable html entities like `&ensp;`

### ISSUE THREAD

**Issue by sheepzh** [streetsidesoftware/vscode-spell-checker#1038]

**Comment by Jason3S** [comment]
@sheepzh,

`&ensp;` is in the `htm-symbol-entities` dictionary.

Depending upon the file type, that dictionary might not be enabled.

To find out if this is the case, add in the document with the issue a comment containing:

`cspell:dictionaries html-symbol-entities`

**Comment by sheepzh** [comment]
Thanks!
