### ISSUE TITLE
Error message: Running the contributed command: 'cSpell.enableForWorkspace' failed.

### ISSUE THREAD

**Issue by UNIVAC-Colonel-Panic** [streetsidesoftware/vscode-spell-checker#1044]
Hi,

I'm a new user to VS Code and I'm not sure what info you need to troubleshoot this error. I only have a single markdown file open, but I have four windows open to it: one for preview and three for code. In case it matters, I haven't been able to get this extension to work yet, i.e., it's not the case that it was working before and now isn't.

### Help-\>About

>This|And That
>---------------|:--------
>Version| 1.58.0 (user setup)  
>Commit| 2d23c42a936db1c7b3b06f918cde29561cc47cd6  
>Date| 2021-07-08T06:54:55.083Z  
>Electron| 12.0.13  
>Chrome| 89.0.4389.128  
>Node.js| 14.16.0  
>V8| 8.9.255.25-electron.0  
>OS| Windows_NT x64 10.0.19043

### Installed extensions

>Name|Id|Description|Version|Publisher|Link
>-------|:-|------------|---------|---------|-----
>Bookmarks|alefragnani.bookmarks|Mark lines and jump to them|13.1.0|Alessandro Fragnani|[link](https://marketplace.visualstudio.com/items?itemName=alefragnani.Bookmarks)
>Code Spell Checker|streetsidesoftware.code-spell-checker|Spelling checker for source code|1.10.2|Street Side Software|[link](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker)
>Sort lines|tyriar.sort-lines|Sorts lines of text|1.9.0|Daniel Imms|[link](https://marketplace.visualstudio.com/items?itemName=Tyriar.sort-lines)

**Comment by Jason3S** [comment]
That must be frustrating.

It is possible that it did not fully install. This happens on occasion. Please see #388 on how to fix the issue.
