### ISSUE TITLE
Spell Checking in commit section of vscode

### ISSUE THREAD

**Issue by titusfx** [streetsidesoftware/vscode-spell-checker#109]
It would be nice if the spell check is made in the commit section.
![comment section](https://user-images.githubusercontent.com/1366004/28371645-d703277e-6c9d-11e7-9168-0b5781d03de8.png)

**Comment by robsonpeixoto** [comment]
Is possible? How can we help you?

**Comment by Jason3S** [comment]
@robsonpeixoto, it would be amazing if can help!. I think it is possible. Not 100% sure though. Nearly every pane in VS Code is an editor like window. The key thing to figure out is the URI to the window and convince the spell checker to check it. This is similar to issue #99, in that the URI is filtered out before it can be checked.

The spell checker filters out URIs that do not match a pattern [here](https://github.com/Jason-Rev/vscode-spell-checker/blob/master/client/src/cSpellClient.ts#L31):
```typescript
const schema = 'file';
const documentSelector =
    unique(languageIds
        .concat(enabledLanguageIds || [])
        .concat(LanguageIds.languageIds)
    )
    .map(language => ({ language, schema }))
    .concat([{ language: 'plaintext', schema: 'untitled' }]);
```

There is also another filter (the original) on the server side: [here](https://github.com/Jason-Rev/vscode-spell-checker/blob/master/server/src/server.ts#L35)

```typescript
const defaultExclude: Glob[] = [
    'debug:*',
    'debug:/**',        // Files that are generated while debugging (generally from a .map file)
    'vscode:/**',       // VS Code generated files (settings.json for example)
    'private:/**',
    'markdown:/**',     // The HTML generated by the markdown previewer
    'git-index:/**',    // Ignore files loaded for git indexing
    '**/*.rendered',
    '**/*.*.rendered',
    '__pycache__/**',   // ignore cache files.
];
```

**Comment by KUGA2** [comment]
If anyone could look into this again, i would be very grateful :)

It really bothers me when i see my own commits with silly type-os.

**Comment by gbuktenica** [comment]
I would be happy to look at this.

**Comment by Jason3S** [comment]
There is another option:
[cspell CI/CD](https://github.com/streetsidesoftware/cspell/tree/master/packages/cspell#cicd-continuous-integration-support)

**Comment by BillDenton** [comment]
Any update on this? I frequently make spelling mistakes in my commit messages. The code is OK because already checked in the editor by this extension.

**Comment by robsonpeixoto** [comment]
I using a hack. I added a config to set the code as GIT_EDITOR and I'm creating the commit from the embedded terminal:

```jsonc
    "terminal.integrated.env.osx": {
        "EDITOR": "code --wait", // I'm using vscode as default editor inside the vscode terminal
        "GIT_EDITOR": "code --wait", // but you can use only for git
    },
```

**Comment by BillDenton** [comment]
@robsonpeixoto I've added that in my global git config:
.gitconfig
[core]
	editor = code --wait
That's fine for "git commit" from the command line within VS code, but for most of my commits, I use the VS Code built-in git message window.

**Comment by FishingGo** [comment]
> I using a hack. I added a config to set the code as GIT_EDITOR and I'm creating the commit from the embedded terminal:
> 
> ```js
>     "terminal.integrated.env.osx": {
>         "EDITOR": "code --wait", // I'm using vscode as default editor inside the vscode terminal
>         "GIT_EDITOR": "code --wait", // but you can use only for git
>     },
> ```

it's amazing!!

**Comment by Diogo-Rossi** [comment]
I think this problem is partially solved with [this update of VS Code](https://code.visualstudio.com/updates/v1_69#_author-commit-message-using-an-editor)
