### ISSUE TITLE
Support the `files` field in ".vscode/cSpell.json" to determine which folders/files should be scanned.

### ISSUE THREAD

**Issue by Asaf-S** [streetsidesoftware/vscode-spell-checker#1099]
**Is your feature request related to a problem? Please describe.**
When trying to add this to my project, I'm trying to specify which folders should be included.
This is possible via CLI: `npx cspell "./src/**/*"`, but I can't find a way to do it in the `.vscode/cSpell.json` file.

**Describe the solution you'd like**
Having a key called `includePaths`, that accepts as its value - a string or an array of strings, each with a path to be included when running the package.

**Describe alternatives you've considered**
Currently, the only way is to include it all, and remove unwanted paths using the `ignorePaths` key.

**Additional context**
None.

**Comment by Jason3S** [comment]
Related to #678
