### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by zaklinaradivojevic** [streetsidesoftware/vscode-spell-checker#1178]
- Issue Type: `Performance`
- Extension Name: `code-spell-checker`
- Extension Version: `1.10.2`
- OS Version: `Windows_NT ia32 10.0.19043`
- VS Code version: `1.59.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\MEGA13~1\AppData\Local\Temp\streetsidesoftware.code-spell-checker-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by Jason3S** [comment]
Please include the data file:
> :warning: Make sure to **attach** this file from your *home*-directory:
> :warning:`c:\Users\MEGA13~1\AppData\Local\Temp\streetsidesoftware.code-spell-checker-unresponsive.cpuprofile.txt`

A bit more context on the kind of files you were editing would also be helpful.

**Comment by zaklinaradivojevic** [comment]
I've uninstalled the spell checker and installed another one so far I have no problem
