### ISSUE TITLE
[Feature Request] disable-this-line

### ISSUE THREAD

**Issue by lonix1** [streetsidesoftware/vscode-spell-checker#1230]
Please consider adding a `disable-this-line` flag.

We can do this (C#):
````cs
// get the foo from the bar and 
// add it to the baz
// cSpell: disable-next-line
var foobarbaz = true;
````

We can also do this, but it disables it for the entire file:
````cs
// get the foo from the bar and 
// add it to the baz
var foobarbaz = true;           // cSpell:ignore foobarbaz
````

It would be nice to be able to do this:
````cs
// get the foo from the bar and 
// add it to the baz
var foobarbaz = true;           // cSpell: disable-this-line
````

**Comment by Jason3S** [comment]
@lonix1,

Thank you for the suggestion. I believe `cspell:disable-line` does what you want.

I'm in the process of cleaning up the documentation:
- [Document Settings - CSpell](https://streetsidesoftware.github.io/cspell/configuration/document-settings/#enable--disable-checking-sections-of-code)
- [README - In Document Settings](https://github.com/streetsidesoftware/vscode-spell-checker#in-document-settings)

**Comment by lonix1** [comment]
Yes, it works!

I didn't see that bit in the docs - sorry for troubling you!

And thanks for making this incredible useful extension!! :+1:
