### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by oscarcalderonc** [streetsidesoftware/vscode-spell-checker#1240]
- Issue Type: `Performance`
- Extension Name: `code-spell-checker`
- Extension Version: `1.10.4`
- OS Version: `Darwin x64 19.6.0`
- VS Code version: `1.59.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/var/folders/mz/553fq3td0tn5qftqhv6z38r00000gn/T/streetsidesoftware.code-spell-checker-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by Jason3S** [comment]
There is a new version coming out soon that should take care of any issues you are seeing.
If you would like to try it out, see: [Releases · streetsidesoftware/vscode-spell-checker]
(https://github.com/streetsidesoftware/vscode-spell-checker/releases)

**Comment by Jason3S** [comment]
I'm going to close this. Please open a new issue if it happens with the new version of the extension.
