### ISSUE TITLE
Broken license link on vscode publication page

### ISSUE THREAD

**Issue by swaldhoer** [streetsidesoftware/vscode-spell-checker#1245]
Since the last commits and publishing to the VS Code marketplace, the license link is broken:
https://marketplace.visualstudio.com/items/streetsidesoftware.code-spell-checker/license

Is it possible to add this license info link back in the marketplace?

**Comment by Jason3S** [comment]
Thank you. I'll take a look.

**Comment by Jason3S** [comment]
Related to: [Prevent / Warn about missing LICENSE · Issue #603 · microsoft/vscode-vsce](https://github.com/microsoft/vscode-vsce/issues/603)
