### ISSUE TITLE
There is too many simple words missing (only I affected? )

### ISSUE THREAD

**Issue by JackVeromeev** [streetsidesoftware/vscode-spell-checker#1246]
Hello and thank you for this delightful extension, it saved me a lot of time from typos!
But day by day I face that the extension doesn't understand many simple words in code and comments.

![image](https://user-images.githubusercontent.com/15068679/131645457-85d59fa3-9f49-4a0a-baf1-8d7bcb72bd45.png)

May it be connected with the wrong settings? I usually add all the found words to the user dictionary, so they should be available in any vscode folder.

**Comment by JackVeromeev** [comment]
As addition: the list of the words added manually. Most of them are common English words, aren't they? Maybe I should add additional extension for those words?
![image](https://user-images.githubusercontent.com/15068679/131660746-ee0f34c3-5542-4c13-b0e7-5a5d8ea07360.png)

**Comment by Jason3S** [comment]
@JackVeromeev,

It looks like the English dictionary got turned off. Please double check VS Code Settings.

![image](https://user-images.githubusercontent.com/3740137/131668079-14239f09-482e-4684-8530-ca8c086c0b5d.png)

You might need to scroll down to see it. Please check Workspace and Folder settings.

![image](https://user-images.githubusercontent.com/3740137/131667880-8f6b33bf-5c49-4850-9c96-cf0f3cb46eea.png)

**Comment by JackVeromeev** [comment]
Hi @Jason3S 
Yes, it was the issue. Thank you a lot!
