### ISSUE TITLE
Solved: v2.0.2 marked as malicious software by Cisco scanner

### ISSUE THREAD

**Issue by bhall2001** [streetsidesoftware/vscode-spell-checker#1252]
Wanted to let you know that the company I work for has flagged the 2.0.2 (and now other versions) as containing malicious malware. As I understand from our Directory of Security, the scanner software used is from Cisco. I installed v2.0.0 which I was running prior to 2.0.2 and that also is now flagged as containing malicious malware.

I've had to uninstall the extension which I'm bummed about. I wanted to let you know.

Bob

**Comment by Jason-Rev** [comment]
Would you please post any details. Or email me directly.
***@***.***

**Comment by bhall2001** [comment]
github hides email addresses. I am checking with our director to see what I can share. I'll post here what I can.

**Comment by jbates58** [comment]
Hello @Jason-Rev 

I work for an MSSP, that also uses Cisco Software.

I will add some information here that I am able to share (as some of it is confidential).

I am unable to share the detection report from Cisco, but it states the following behavioural Indicators:

- Generic Ransomware Detected
- An HTML or JavaScript with Excessive Amount of JavaScript Function Definitions
- JavaScript Contains an Excessively Long String
- JavaScript Using "toString" Method
- Static Analysis Flagged Artifact As Potentially Obfuscated
- Static Analysis Flagged Artifact As Anomalous
- JavaScript Obfuscation Using "fromCharCode()" Function
- Artifact With Multiple Extensions Detected

That is all i can share from the report.

- SHA-256 - 22ad355ddb4692c52f69d0f3ff9c709629f1a247bb360b7c650fbe908f666a77
- https://www.virustotal.com/gui/file/22ad355ddb4692c52f69d0f3ff9c709629f1a247bb360b7c650fbe908f666a77/detection

![Streetside_software_detection](https://user-images.githubusercontent.com/7126355/131765035-de780c6c-1855-49c3-8f35-5bece0157344.png)

**Comment by jbates58** [comment]
Hello All,

We have reported the file to Cisco, and they have performed a more in-depth analysis on it. They have changed the disposition of the file from **MALICIOUS** to **CLEAN**.

This file should no longer be detected by the Cisco products.

[https://talosintelligence.com/sha_searches](url)
(Enter the following hash in the search bar) - 22ad355ddb4692c52f69d0f3ff9c709629f1a247bb360b7c650fbe908f666a77

@bhall2001 - you should be good to retry using the software.

This issue can now be closed off.

**Comment by Jason3S** [comment]
@jbates58,

Thank you for following up.
