### ISSUE TITLE
"File not spell checked : lines are too long" on a markdown file

### ISSUE THREAD

**Issue by dbourrion** [streetsidesoftware/vscode-spell-checker#1256]
Hi
On a markdown file, I got that notification "File not spell checked : lines are too long".

Ok, it's something like a novel that I'm writing (I'm a writer) but I was already using vscode-spell-cheker before and it was working.

Can't find an explanation. Help welcome.

**Comment by Jason3S** [comment]
It is there to prevent performance issue on generated files.

You can increase the limit: VS Code Settings -> `spell block line`

![image](https://user-images.githubusercontent.com/3740137/131900091-d57bf2cd-617d-4492-899d-1585f0a1db62.png)

**Comment by dbourrion** [comment]
Wow, yes, it works much better with a max increased at 5000

Thanks a lot.
