### ISSUE TITLE
custom dictionaries not working in latest verison 

### ISSUE THREAD

**Issue by derekwallace** [streetsidesoftware/vscode-spell-checker#1279]
Hi,
i have been using custom dictionalries successfully for the last year. this was the setup.
i have 5 dictionareis.
I will write to the derek dictionary.

      // "cSpell.dictionaryDefinitions": [
      //    { "name": "custom",  "path": "${workspaceFolder}/vscode/cSpell.dictionary.txt" },
      //    { "name": "derek",   "path": "${workspaceFolder}/vscode/cSpell.dictionary.derek.txt" },
      //    { "name": "rishabh", "path": "${workspaceFolder}/vscode/cSpell.dictionary.rishabh.txt" },
      //    { "name": "vivek",   "path": "${workspaceFolder}/vscode/cSpell.dictionary.vivek.txt" },
      //    { "name": "shubham", "path": "${workspaceFolder}/vscode/cSpell.dictionary.shubham.txt" },
      // ],

      // "cSpell.dictionaries": [ "custom", "derek", "rishabh", "vivek", "shubham", "en"],
      // "cSpell.customWorkspaceDictionaries": [ "derek" ],

this is now not working n latest vs code and latest extension.
i tried to updaet as it seems the settings are differnt to this.

      "cSpell.customDictionaries": {

         "custom": {
           "name": "custom",
           "path": "${workspaceFolder}/vscode/cSpell.dictionary.txt",
           "description": "Words used in this project",
           "addWords": false
         },
         "derek": {
            "name": "derek",
            "path": "${workspaceFolder}/vscode/cSpell.dictionary.derek.txt",
            "description": "Words used in this project",
            "addWords": true
          },
          "rishabh": {
            "name": "rishabh",
            "path": "${workspaceFolder}/vscode/cSpell.dictionary.rishabh.txt",
            "description": "Words used in this project",
            "addWords": false
          },
          "vivek": {
            "name": "vivek",
            "path": "${workspaceFolder}/vscode/cSpell.dictionary.vivek.txt",
            "description": "Words used in this project",
            "addWords": false
          },
          "shubham": {
            "name": "shubham",
            "path": "${workspaceFolder}/vscode/cSpell.dictionary.shubham.txt",
            "description": "Words used in this project",
            "addWords": false
          }
       },
       "cSpell.dictionaries": [ "custom", "derek", "rishabh", "vivek", "shubham", "en"],
       "cSpell.customWorkspaceDictionaries": [ "derek" ],

it is not working. Now my code is flagged with unkonw works etc.
Can you help me setup my dictionaries correclty.

thansk
derek

**Comment by Jason3S** [comment]
That must be frustrating.

A few things:
1. Is this a Multi-root Workspace?
   * If it is a multi-root, you need to include the name of the folder that has the dictionaries `${workspaceFolder:<name>}`.
2. You can see which dictionaries it tries to load:
    * Open a file with spelling errors
    * click ![image](https://user-images.githubusercontent.com/3740137/132523563-19b242c9-6c0b-4391-8eea-59c11b9b5f9a.png)
    * Make sure the  `File` tab is selected:
        ![image](https://user-images.githubusercontent.com/3740137/132523716-a4432fda-845e-4db9-b978-02edf7b46505.png)
    * Scroll down to the active dictionaries for the file you are editing.  You should see something like this:
        ![image](https://user-images.githubusercontent.com/3740137/132523913-8b8d5316-40e8-4778-b4b2-135503f0dae3.png)
    * Try clicking the links, if they do not open, then it cannot find the file.

 Please let me know if this helps.
