### ISSUE TITLE
Spell checking files that are not part of a project/workspace

### ISSUE THREAD

**Issue by SebastianMuskalla** [streetsidesoftware/vscode-spell-checker#1283]
I am using VSCode 1.60 with cSpell 2.0.4 (and the extension for the German dictionary 0.1.10).

If I open a workspace / project / folder, the spell checker works like a charm. But if I open a single file (`.txt` or `.md`) on my disk, it does not work.

This is the tooltip of the spell checker entry in the status bar

![image](https://user-images.githubusercontent.com/1058324/132778409-5d16c192-6a31-4adb-aaf4-be2e85053cff.png)

And this is what I get when I click that entry

![image](https://user-images.githubusercontent.com/1058324/132778442-ee1c9e8b-2013-45c4-89c5-d415e52bd66f.png)

If I create a new file, cSpell works while the file is unsaved. As soon as I save the file, it stops working.

I talked to another user who doesn't have the same problem, so it is probably some setting or incompatiblity. Here are all the `cSpell` related settings in my `settings.json`

```
 "cSpell.diagnosticLevel": "Hint",
    "cSpell.language": "en,de",
    "cSpell.logLevel": "None",
    "cSpell.userWords": [
         // removed
    ],
   "cSpell.enabled": true
```

The `search.exclude` setting that has been mentioned e.g. in issue #16 is not set.

I disabled all other extensions and the problem persists.

**Comment by wolf99** [comment]
I am seeing same issue in vscode 1.60.1.

There are the following cases:

1. Files that are part of the open project (implicitly, this means they are saved files) : cspell runs on these files
2. Files that are not part of the open project but are saved on disk : cspell **does not** run on these files
3. Files that are not saved (e.g. File > New file) : cspell runs on these files

**Comment by Jason3S** [comment]
@wolf99,

Did the setting work for you?
![image](https://user-images.githubusercontent.com/3740137/133642100-85b0608b-908c-4b40-bc34-6c9b572feabc.png)

**Comment by wolf99** [comment]
Ah ,that did it!
Thank you @Jason3S

**Comment by SebastianMuskalla** [comment]
Fixed it for me too!
It's a little bit unfortunate that the "Spell Check Only Workspace Files" is set by default and doesn't occur in the settings if you don't change it.
