### ISSUE TITLE
limit the number of suggestions provided to vscode

### ISSUE THREAD

**Issue by capaj** [streetsidesoftware/vscode-spell-checker#1290]
![image](https://user-images.githubusercontent.com/1305378/132942118-7ca25763-9ee1-472c-8029-b70cc227c537.png)

showing this many suggestions is not productive. There should be a configurable limit for this-by default it could be like 10, or 15 items.
Nobody has screen big enough to justify having more.

**Comment by Jason3S** [comment]
This should be fixed.
