### ISSUE TITLE
Request: Should generate a newline at the end of cspell.json when it does not have one.

### ISSUE THREAD

**Issue by Zamiell** [streetsidesoftware/vscode-spell-checker#1291]
Hello, and thanks for the excellent extension!

Currently, if I right click a word and select "Add Words to CSpell Configuration", it will helpfully insert the word at the right place and format the file for me so that all of the words are in alphabetical order.

However, it also truncates any new lines at the end of the file while it does this. This behavior goes against POSIX standards: https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline

Even GitHub warns you when a commit removes a trailing newline by showing a red X.

I submit that this extension should follow this widespread standard, and insert a newline at the end when auto-formatting a cspell.json file.

**Comment by Jason3S** [comment]
The expected behavior of the Spell Checker v2 is to preserve the file ending and line endings. I'll double check.

**Comment by Zamiell** [comment]
I see. I tested, and what you said does seem to be the case.

I would prefer if Spell Checker v2 was opinionated here and always inserted a new line to the config file in order to make it always conform to POSIX standards. Especially considering that users who are migrating from v1 will **not** already have a new line in their config file already because of the previous behavior of Spell Checker v1 forcibly removing it.

**Comment by Zamiell** [comment]
Thank you Jason. <3
