### ISSUE TITLE
Suppress context menu items?

### ISSUE THREAD

**Issue by lonix1** [streetsidesoftware/vscode-spell-checker#1296]
The (right click) context menu shows lots of items, e.g.

- Create a CSpell configuration file
- add words to dictionary
- add words to workspace settings
- add words to user settings
- ignore words
- ...

My context menu is quite cluttered with items from various extensions. I was wondering whether it's possible to disable these completely?

**Comment by Jason3S** [comment]
You can turn them off completely.

![image](https://user-images.githubusercontent.com/3740137/133100864-825d7231-9cdc-458c-8218-0a37b1017e53.png)

**Comment by lonix1** [comment]
Thanks.

I use the json settings, I've looked in there twice and didn't see anything. Is there a setting for that?
