### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by eminbahadir** [streetsidesoftware/vscode-spell-checker#1319]
- Issue Type: `Performance`
- Extension Name: `code-spell-checker`
- Extension Version: `2.0.5`
- OS Version: `Darwin x64 20.6.0`
- VS Code version: `1.60.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/var/folders/gz/clth3pxj2f705pn9r4lmlk180000gn/T/streetsidesoftware.code-spell-checker-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by Jason3S** [comment]
@eminbahadir,

Please attach the file from your machine as requested.
> :warning: Make sure to **attach** this file from your *home*-directory:
> :warning:`/var/folders/gz/clth3pxj2f705pn9r4lmlk180000gn/T/streetsidesoftware.code-spell-checker-unresponsive.cpuprofile.txt`

**Comment by Jason3S** [comment]
Please see #650
