### ISSUE TITLE
How to show squiggle only without scroll bar highlight?

### ISSUE THREAD

**Issue by keidarcy** [streetsidesoftware/vscode-spell-checker#1345]
![Screen Shot 2021-09-24 at 10 55 11](https://user-images.githubusercontent.com/48758247/134606618-d62f9c29-679e-44b0-a1d1-e1ca8dffbc16.png)

Is there any setting to hide red box part in screenshot? I tried all setting but can't find one.
It's mess to show that with git information in a big codebase.

**Comment by Jason3S** [comment]
Please see #872

**Comment by keidarcy** [comment]
Thanks! Understood!
