### ISSUE TITLE
cspell only uses one word per line of dictionary

### ISSUE THREAD

**Issue by David-de-Wit** [streetsidesoftware/vscode-spell-checker#1406]
I use Code Spell Checker (cspell) 2.0.8 with Latex Workshop in VSCode 1.60.2. I use as dictionary files structured, plain text, documents that list scientific names, for instance:

division Basidiomycota
  classis Agaricomycetes
    ordo Agaricales, Gilled mushrooms, Euagarics, some of the most familiar types of mushrooms
      familio Agaricaceae
        Agaricus bisporus, Button mushroom

Until recently this worked fine. Since about 2021-09, cspell seems to only recognise the first word of each line in the dictionary file, and ignores lines that begin with spaces. I'm not 100% sure that I'm right here. Am I right?

**Comment by Jason3S** [comment]
It is expecting your dictionary to be one word per line.

```gitignore
# comments are allowed.
each
word # comments are allowed after a word.
on
a
line
```

**Comment by David-de-Wit** [comment]
So, I'd really appreciate a return to the previous behaviour.

**Comment by David-de-Wit** [comment]
A quick check shows that my problem is solved. I hadn't found this in the documentation.
