### ISSUE TITLE
[Feature Request] Per-language dictionary

### ISSUE THREAD

**Issue by Sidneys1** [streetsidesoftware/vscode-spell-checker#141]
In addition to global and per-project dictionaries, there should also be dictionaries for different languages (e.g., c++, java) at both the global and project level.

For example, Code SpellChecker is always telling me that "stoi" (in C++) is not a word. I'd love to have the plugin ignore that word _in C++ files only_.

**Comment by Jason3S** [comment]
Good suggestion. The ability is already there, but there isn't UI.

The spell checker already uses the concept of custom dictionaries per language. They are being migrated to [cspell-dicts](https://github.com/Jason3S/cspell-dicts). Some of them are still defined in [cspell](https://github.com/Jason3S/cspell)/dictionaries.

I'll make sure `stoi` gets added to the `cpp` dictionary, or if you like, make a pull request with any missing words.

As far as being able to insert words from the UI into a language specific dictionary, this is something I intend to support, just haven't gotten around to it.  So, thank you for bringing it up.

**Comment by bentolor** [comment]
It looks to me that this feature is now available in the current plugins, no?

Actually I see that I can enable i.e. language dictionaries like `companies`, `cpp` or `rust`. I mostly miss a `java` dictionary.

**Comment by Jason3S** [comment]
@bentolor `java` has been added to the default spell checker.

**Comment by Jason3S** [comment]
Note: this is already possible.
