### ISSUE TITLE
 Doesn't check python Django files

### ISSUE THREAD

**Issue by SomePythonCodes** [streetsidesoftware/vscode-spell-checker#1413]
models.py
File is excluded by .gitignore

urls.py
File is excluded by .gitignore

**Comment by Jason3S** [comment]
I found the line:
[gitignore/Python.gitignore at master · github/gitignore](https://github.com/github/gitignore/blob/master/Python.gitignore#L49)

```gitignore
*py,cover
```

gets interpreted as `*.py`. If you remove that line, it should work.  I'll see if I can find a fix.
