### ISSUE TITLE
New version adds inconvenient autofill in Latex

### ISSUE THREAD

**Issue by adamoppenheimer** [streetsidesoftware/vscode-spell-checker#1450]
Hi, first I would like to say thank you very much for a great addon for VSCode.

Relevant information:
I am using this on Mac OS 10.15.7, with VS Code version 1.61.1, Code Spell Checker v2.0.10, and Latex Workshop v8.21.0.

The issue I am having is that the most recent version of this addon introduced an autofill for Latex that is inconvenient. Whenever I type a colon (:) then type enter, it autofills to become \ddots (the autofill is suggested as @:, if that helps).

I have pinned the issue down to the combination of this addon with Latex Workshop. If either is installed alone, this autofill does not happen. I am under the impression that Latex Workshop is not changing shortcuts because a spell-checker is installed. I think the issue is more likely coming from this spell checker introducing a new shortcut.

Obviously this is low priority, but I am sure I am not the only person having this issue. (I consider this an issue because I often use a colon before introducing an equation, but rarely use \ddots).

Thank you!

**Comment by Jason3S** [comment]
@adamoppenheimer,

Please open an issue withe Latex Workshop as well. This extension does not offer an autofill of `@:`. Although it is possible that there is some strange interaction that happens. If you type `cspell:` the extension will offer to auto complete suggestions for this extension.
