### ISSUE TITLE
Is there any option to disable spell check during typing (until word ends)?

### ISSUE THREAD

**Issue by Delgan** [streetsidesoftware/vscode-spell-checker#1464]
Hi! I just discovered this extension which is super useful, thanks!

One thing I noticed is that the word I'm typing is intermittently underlined since I haven't finished writing it.

If I'm willing to write `"example"`, underlines will appear when `"examp"` and `"exampl`" is typed and disappear with the final `"e"`.

This is a bit distracting and I guess it consumes resources unnecessarily.

I was wondering if it was possible to execute the spellcheck only when the cursor leaves the current word or when a `\W` character is written?

**Comment by Delgan** [comment]
Thanks for the tip @Jason3S!

Do you think that optimizing the spell check for the word being written is feasible (I don't know the VSCode Extension API) or even desirable (perhaps too complex for too little benefit)?

If not, feel free to close this ticket. The "Spell Check Delay Ms" workaround seems good enough for me. :+1:

**Comment by Jason3S** [comment]
The extension does not have access to what the user is typing, just the edits to the file, so detecting the "end" of the word is difficult.

I'll close this for now.
