### ISSUE TITLE
Add word to cspell.json rather than settings.json

### ISSUE THREAD

**Issue by msorens** [streetsidesoftware/vscode-spell-checker#148]
(1) In order to add a spell check to the build process I want to use the dedicated cspell.json rather than the multi-purpose settings.json. However, when I add a word to the dictionary from the context menu in VSCode, it goes to settings.json. Is there a setting (or other way) so that I can interactively add a word to cspell.json?
(2) The only other choice on the context menu is "add word to global dictionary". Where is this global dictionary? I inadvertantly added a word there and want to delete it but I cannot find the global dictionary.

**Comment by Jason3S** [comment]
@msorens,

Thank you for bringing this up.

How it is supposed to work:
If you have a `cspell.json` file in the project root or `.vscode` directory, adding a word to the project dictionary using the UI will add the word to both `settings.json` and `cspell.json`.

The Global dictionary is stored in the user settings. That location is chosen by VS Code.
You can get to the settings in VS Code by: `F1` `Open User Settings`

You bring up a good point about custom user / team dictionaries. It is not easy to add / remove words from them.

**Comment by gaochenyi** [comment]
So there are only workspace user words and no folder user words. Am I right?

**Comment by Jason3S** [comment]
`user` words are global and come from VS Code. `words` are defined in `cspell.json` files. You can also have a "folder" level `cspell.json` files.

**Comment by gaochenyi** [comment]
> `user` words are global and come from VS Code. `words` are defined in `cspell.json` files. You can also have a "folder" level `cspell.json` files.

Thanks, but I am still confused. I would like to have a way to use some words only in the folder `test`. Could a `cspell.json` file containing the following line works? My test says no. Do I miss something?

```json
{ "words": [ "hehe", "haha" ] }
```

**Comment by Jason3S** [comment]
The spell checker currently does not pickup nested `cspell.json` files. It is something I have been considering.

If you have a VS Code project with a Workspace and Folders, it will pick that up and use the folder level `cspell.json` file.

**Comment by gaochenyi** [comment]
Oh, that's the reason—there is no project at all. I will create one. Thanks.

**Comment by Jason3S** [comment]
Since the way it works in V2 has changed, I'm closing this issue. If this is still an issue, please one a new issue describing the desired behavior.

Kind regards,
Jason
