### ISSUE TITLE
Provide an option to remove corrections from the QuickFix menu

### ISSUE THREAD

**Issue by agross** [streetsidesoftware/vscode-spell-checker#1522]
As per https://github.com/streetsidesoftware/vscode-spell-checker/issues/264#issuecomment-965644724

When I'm doing refactorings (Alt+Return) I'm not interested in having the menu cluttered with possible corrections. At least it should be allowed to limit the number of suggestions shown there.

**Comment by Jason3S** [comment]
@agross,

I have added some code to reduce the number of suggestions shown. But I'm not seeing the original issue.

`alt+enter` is used match all occurrences of find. Are you seeing something strange happen?

**Comment by agross** [comment]
I have bound `alt+enter` to the `Quick Fix...` action. Does that answer your question?

**Comment by Jason3S** [comment]
That makes more sense.

There is a setting: `Preferences->spell num suggestions` should limit the number of suggestions shown.

![image](https://user-images.githubusercontent.com/3740137/149195487-1f4c03dd-d315-4c63-b01f-38a54b46c4e6.png)

**Comment by agross** [comment]
Thank you, I'll try that!

**Comment by agross** [comment]
Works well, thank you! 👍
