### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Funsho-ops** [streetsidesoftware/vscode-spell-checker#1526]
- Issue Type: `Performance`
- Extension Name: `code-spell-checker`
- Extension Version: `2.0.12`
- OS Version: `Windows_NT x64 10.0.18363`
- VS Code version: `1.62.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\user\AppData\Local\Temp\streetsidesoftware.code-spell-checker-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by Jason3S** [comment]
@Funsho-ops,

Please attach the file as directed, otherwise there is noting that can be done.

**Comment by Jason3S** [comment]
I would like to be able to help, but without more information, it is not possible to work on this.
