### ISSUE TITLE
Extension unable to start: Connection to server is erroring. Shutting down server.

### ISSUE THREAD

**Issue by alexcu** [streetsidesoftware/vscode-spell-checker#1528]
Hi there,

This error has begun showing up out of nowhere, rendering the extension useless:

<img width="766" alt="image" src="https://user-images.githubusercontent.com/1430592/141705691-47bc0b7c-427d-48f4-844b-4f9173e3fc04.png">

Error:

```
Connection to server is erroring. Shutting down server.
```

I have no ideas as to what may have caused this issue (have not updated any extensions or VS Code itself recently).

Anyone have suggestions for getting the extension to work? I have re-installed (both via UI and `rm -rf` the extension directory) without any luck. Happy to provide any additional info if it can help.

Thanks,
Alex

**Comment by alexcu** [comment]
I gather this error is resulting from the backend `vscode-languageserver-node` client https://github.com/microsoft/vscode-languageserver-node/blob/b988c1e9d17fb11fec9700028da7bc3b99d17ef3/client/src/common/client.ts#L3533

**Comment by alexcu** [comment]
Ran an extension bisect. Appears to be a conflict issue with `withfig.fig`. Closing for now.

**Comment by Jason3S** [comment]
@alexcu,

Thank you for investigating. What was the actual issue?

**Comment by alexcu** [comment]
@Jason3S Not entirely sure.

**Comment by roblight** [comment]
I just ran the Extension Bisect command and it identified this extension as the problem.

**Comment by Jason3S** [comment]
@roblight,
Are you also running fig? 
Are you able to just run this extension?
