### ISSUE TITLE
How to turn off spell check display errors on problems panel ?

### ISSUE THREAD

**Issue by Osolemio44** [streetsidesoftware/vscode-spell-checker#1535]
Hi. i want to keep using spell check, but only in the editor. I dont want to see those errors in the problems panel. 
I tried setting log level to "none".
¿ How can i disable the errors displaying on the problem panel? 

![image](https://user-images.githubusercontent.com/55595063/141956761-dc5e763f-baa8-4f9f-8d88-20089b6a4de9.png)

Thanks for the great work!

**Comment by Jason3S** [comment]
Please see #186. 
Extensions do not have control over what is displayed in the problems pane. See https://github.com/microsoft/vscode/issues/95707.

You can set the diagnostic level to `Hint`:
![image](https://user-images.githubusercontent.com/3740137/141966070-e6f4983e-cddd-43f2-88b9-45f2f3934ecc.png)

That will hide it from the problems pane, but the squiggles will be `...`.
