### ISSUE TITLE
Plugin breaks VS Code's Intellisense word suggestions

### ISSUE THREAD

**Issue by maciejmatczak** [streetsidesoftware/vscode-spell-checker#1536]
Hi,

I faced an issue when using this plugin. I code in TCL with a custom user snippets for language setup. Some day my word based suggestions stopped working (it should suggest a snippets and words based what matches better):
![obraz](https://user-images.githubusercontent.com/1786383/142067753-b35ce6ee-ab53-4be1-a547-828d2e16b30b.png)

Word based suggestion is missing. Issue opened against VS Code here (closed by bot :/) https://github.com/microsoft/vscode/issues/136500

After trying to replicate the issue on "non-infected" machine, I started to install plugins one by one from the "infected" one and I stopped on Spell Checker.

At this point, I can install this plugin, which breaks my IDE, uninstall it, which immediately fixes the issue.

Example how it looks like: https://github.com/microsoft/vscode/issues/136500#issuecomment-970686200

Please let me know if I can somehow help more, provide some logs, etc. I pretty much like that plugin! :)

**Comment by maciejmatczak** [comment]
@Jason3S, can I ask you to create an issue against VS Code?

I would do it, but I believe you will be able to describe the root cause directly in contrary to me :D

**Comment by Jason3S** [comment]
I'll create an issue.
