### ISSUE TITLE
Markdown: everything misspelled

### ISSUE THREAD

**Issue by bfallik** [streetsidesoftware/vscode-spell-checker#1590]
I'm running vscode-spell-checker on Linux. When I open a Markdown file vscode shows that every word in the file is misspelled (underlined with a red squiggly line). The "Problems" tab in vscode lists over 100 spelling problems (e.g. `"build": no suggestions spelling [5,1]`). 

I don't see anything obviously misconfigured anywhere in the settings. The extension is configured to check Markdown files. I don't remember tweaking any of the default spelling configs and I only need language support for English (US).

Any help would be appreciated! Thanks.

**Comment by Jason3S** [comment]
It is acting like the `language` setting is blank or not set to `en` for English.

Open VS Code preferences and search for `cspell language`

![image](https://user-images.githubusercontent.com/3740137/145483650-3d498c74-b1f7-4880-923b-05c8d89793fc.png)

Please make sure it is set to `en`.

**Comment by bfallik** [comment]
Hi @Jason3S ,

Yeah based on the experience it does seem like the language setting is incorrect but that's not what I'm seeing in vscode.
![Screenshot from 2021-12-09 17-55-29](https://user-images.githubusercontent.com/220118/145488804-da1d2879-7e10-49ec-a8d5-cd08e72d749c.png)

Is there another setting that might be conflicting with or overriding this value?

Thx,
brian

**Comment by Jason3S** [comment]
@bfallik,

That is frustrating. 

## Other settings

`overrides` can change the language of a file.
![image](https://user-images.githubusercontent.com/3740137/145560571-879bc48f-d7a1-4273-a35e-5a94cd698691.png)

`locale` and `languageId` fields are used to change the language and the file type respectively.

# There are a few things to try.

## Show Current file Configuration

1. Open a Markdown file with the issue
2. Click on the `Spell` in the status bar. 
    ![image](https://user-images.githubusercontent.com/3740137/145560788-1ba1790a-e906-4b6e-a42b-2a5a859ffaa7.png)
    It will open a Configuration window showing more information.
3. It will look something like this: 
    ![image](https://user-images.githubusercontent.com/3740137/145560995-31124159-6165-4c77-b6b7-7c141ce67142.png)

4. You should find the following in the list of dictionaries: 
    ![image](https://user-images.githubusercontent.com/3740137/145561176-6707af38-71e1-45ab-a813-7cdbae460056.png)
 

## Use `cspell` cli to test

Assuming you have NodeJS installed on your machine, open a Terminal window in VS Code and run:

```
npx cspell "**/*.md"
```

If you see the same errors, then it is a configuration issue in a `cspell.json`. If you do not, then it might be an issue in the VS Code settings or a bad install (happens occasionally).

**Comment by bfallik** [comment]
hji @Jason3S ,

Thanks for your help on this. Turns out I had a second spell checking extension installed. I don't remember installing it but :man_shrugging: . Once I uninstalled that extension Code Spell Checker returned to normal. I'll go ahead and close this ticket.

Thx,
brian
