### ISSUE TITLE
Context menu shifted, causing immediate item selection

### ISSUE THREAD

**Issue by nmggithub** [streetsidesoftware/vscode-spell-checker#1591]
Hello! I have had this issue in VSCode for a while that, occasionally, when I right-click something the context menu will not appear directly offset from the mouse pointer, but will instead be shifted to where the pointer is then right on top of one of the menu items, which is immediately selected. I have narrowed it down to this extension (disabled it and the behavior disappeared, enabled it and the behavior reappeared), and I believe it is likely due to the items it adds to the context menu. I an running VSCode with this extension on Arch Linux.

**Comment by Jason3S** [comment]
@nmggithub,

Please include a few screen shots so it is easier to understand the issue.

To be clear, the extension can only influence the items in the context menu, not how it behaves. So, it might be a good idea to open an issue against VS Code.

**Comment by nmggithub** [comment]
@Jason3S,

Honestly a video recording would show this off better. I'll see if I can replicate in against the source code of the extension itself (very meta), so I don't have to worry about showing private code in my recording, and it will also ease reproducibility.

**Comment by Jason3S** [comment]
@nmggithub,
Great!

Would you please link the VS Code to this one? That way if someone else looks, they can also find that issue.

**Comment by nmggithub** [comment]
Ok! Unsure if people would come here as further testing shows it's more complicated, but the issue is here: https://github.com/microsoft/vscode/issues/113175. Seems to not have much progress on it.
