### ISSUE TITLE
Ability to exclude a language from being checked

### ISSUE THREAD

**Issue by MohammadMD1383** [streetsidesoftware/vscode-spell-checker#1596]
I want to exclude Persian from being spell checked.

also being able to exclude a range of characters from being checked is good.

thanks.

**Comment by Jason3S** [comment]
The `ignoreRegExpList` lets you exclude those values.

[Unicode Characters in the Arabic Block `u0600-u6ff`](https://www.fileformat.info/info/unicode/block/arabic/list.htm)

![image](https://user-images.githubusercontent.com/3740137/145984705-6edced09-86b6-40b7-a932-be05f66252df.png)

**VS Code `settings.json`**

```json
    "cSpell.ignoreRegExpList": [
        "/[\\u0600-\\u06FF]+/g"
    ]
```

**`cspell.json`**

```json
    "ignoreRegExpList": [
        "/[\\u0600-\\u06FF]+/g"
    ]
```

**Comment by MohammadMD1383** [comment]
Thanks! Solved!!
