### ISSUE TITLE
Stopped working in GitPod

### ISSUE THREAD

**Issue by Foxhoundn** [streetsidesoftware/vscode-spell-checker#1614]
Hey,

I have noticed that the extension has stopped working when used in GitPod - it seems that locally it still works fine.

Let me know if / what data should I provide to allow you to debug properly.

Cheers

**Comment by Jason3S** [comment]
Was it working before? I haven't tried it on GitPod.

**Comment by Jason3S** [comment]
I just tried it out. It is working for me. I had to install the extension in the GitPod workspace for it to work.

![image](https://user-images.githubusercontent.com/3740137/147232906-7d0fb746-c2e6-4dbb-9ebb-adca05d047c0.png)

**Comment by Foxhoundn** [comment]
> I just tried it out. It is working for me. I had to install the extension in the GitPod workspace for it to work.
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/3740137/147232906-7d0fb746-c2e6-4dbb-9ebb-adca05d047c0.png)
> 
> 

It was working fine from September till December, then it stopped working. It installs fine, it shows the extension in the Status bar, but there are no actual spell checks in the Editor.

**Comment by Jason3S** [comment]
I need more information.

How is it not actually spell checking?

Do you see: 
![image](https://user-images.githubusercontent.com/3740137/147352387-0b3b417b-f06c-41b7-a3ff-794ca7b1c6f1.png)

Or something else? Like missing the `~~~`
![image](https://user-images.githubusercontent.com/3740137/147352560-1d7f4806-9d3c-4453-8004-979593393ff8.png)

The missing `~~~` seem to be either an issue with GitPod or VS Code.
![image](https://user-images.githubusercontent.com/3740137/147352710-59edaa49-92a6-48e1-9d35-fa8497713e7f.png)

The extension does not have any control over the display of the `~~~`

**Comment by Jason3S** [comment]
Remote Desktop works:
![image](https://user-images.githubusercontent.com/3740137/147353916-3aa46962-ab65-44b3-8958-0cb208c3c9af.png)

**Comment by Foxhoundn** [comment]
It seems that it actually started working again for some reason

![CleanShot 2021-12-27 at 11 00 06](https://user-images.githubusercontent.com/8861481/147460630-cc210281-16b4-458f-a7c0-d5bd7cd3421e.png)

I will report more if It stops working for me again, we can close this for now
