### ISSUE TITLE
Possessives/Apostrophes Are Not Included

### ISSUE THREAD

**Issue by imlouisrussell** [streetsidesoftware/vscode-spell-checker#164]
Possessives/Apostrophes do not appear to be accounted for. This appears to be also affecting proper nouns (e.g. Moore's Law) added to dictionaries.

**Comment by Jason3S** [comment]
I'll take a look. Do you have some other examples?

**Comment by tdreid** [comment]
Similarly I'm finding that when I  click Add Word to [User | Folder] Dictionary the command that is generated stops at the apostrophe.  If I correct the command before hitting enter all is well.  However, if I do not notice the difference then only the base of the word is copied into the dictionary, which has happened a few times.

**Comment by Jason3S** [comment]
It is related to the word selection rules in VS Code. Each programming language has different rules. The spell checker just gets the word selected by VS Code.

**Comment by ankostis** [comment]
Can i not solve it with a regex?

**Comment by ankostis** [comment]
Replying to myself (suggested in #232): `"cSpell.ignoreRegExpList": ["'s\\b"]`

**Comment by Jason3S** [comment]
The word splitter should now take care of this.
