### ISSUE TITLE
`updateing` was not marked as spelling error

### ISSUE THREAD

**Issue by jugmac00** [streetsidesoftware/vscode-spell-checker#1656]
Code Spell Checker v2.0.14

=> The word `updateing` was not marked as spelling error - it is neither in my project's nor in my user's word list, so this must be either builtin or inferred.

**Comment by Jason3S** [comment]
`updateing` is not in any bundled dictionary.

It is cause by `allowCompoundWords`.

```sh
npx cspell trace --allow-compound-words updateing
```

![image](https://user-images.githubusercontent.com/3740137/148580640-c27c752b-510e-4997-b79a-b0765b17e050.png)

To turn off `allowCompoundWords`

## VS Code Settings

![image](https://user-images.githubusercontent.com/3740137/148579021-c2bb48a0-d882-449e-b343-ce7d3f482e28.png)


```js
    "cSpell.languageSettings": [    
        {
            "languageId": "*",
            "allowCompoundWords": false
        }
    ],
```

## `cspell.json`

```js
{
    "languageSettings": [    
        {
            "languageId": "*",
            "allowCompoundWords": false
        }
    ]
}
```
