### ISSUE TITLE
Ignore all non ASCII characters

### ISSUE THREAD

**Issue by AhmedElTabarani** [streetsidesoftware/vscode-spell-checker#1665]
There is a way to make it ignore all non ASCII characters ?

because this is annoying

![image](https://user-images.githubusercontent.com/69223584/148989843-544964ce-beb0-4b48-a0f5-9f54ac375830.png)

I use `Error Lens` extension to visualize the errors but if there is a way to make `Spell Checker` ignore the non ASCII characters that will help

**Comment by Jason3S** [comment]
This looks like a duplicate of #1596

**Comment by AhmedElTabarani** [comment]
> This looks like a duplicate of #1596

Thanks ❤
