### ISSUE TITLE
Extension won't start after 2.1.4 update

### ISSUE THREAD

**Issue by AlexIII** [streetsidesoftware/vscode-spell-checker#1676]
After the last update to `2.1.4` the extension stopped working for me, its not showing `✓ Spell` in the vscode "taskbar" and doesn't do spell checking.
Reverting to `2.1.3` fixes the problem.

**Comment by Jason3S** [comment]
@AlexIII,

That is frustrating. Would you try something? Sometimes VS Code fails to fully install the extension. Please delete the extension files:

Possible locations (change `jason` with your user name):

- Windows - `c:\Users\jason\.vscode\extensions\streetsidesoftware.code-spell-checker-2.1.4`
- Mac OS and Linux - `/Users/jason/.vscode/extensions/streetsidesoftware.code-spell-checker-2.1.4`

Then re-install install `2.1.4`.

Kind regards,
Jason

**Comment by AlexIII** [comment]
@Jason3S it worked, many thanks!
I guess this can be closed if this is an expected behavior (or something that cannot be fixed from the extension itself).
