### ISSUE TITLE
[Feature request]; pack for Arabic language 

### ISSUE THREAD

**Issue by oSethoum** [streetsidesoftware/vscode-spell-checker#1695]
First of all, Thank you so much for this amazing extension, it's helping a lot especially non native speakers. 
Are you planning on adding language pack for Arabic ? if not how can we ignore non supported languages this infos are a bit annoying. 

![image](https://user-images.githubusercontent.com/88779394/150784120-d71faa55-2c20-43d3-b458-8e63bb38a19c.png)

**Comment by Jason3S** [comment]
There are two things that can be done:
1. Ignore the Arabic characters (see: #1596)
2. Create the dictionary

## Creating the Dictionary and Extension

1. Creating the Dictionary
   - The dictionaries are defined here: [cspell-dicts](https://github.com/streetsidesoftware/cspell-dicts)
   - There is an example of Persian here: [cspell-dicts/dictionaries/fa_IR](https://github.com/streetsidesoftware/cspell-dicts/tree/main/dictionaries/fa_IR)
   - The instructions on how to create a dictionary are found here: [how-to-create-a-new-dictionary](https://github.com/streetsidesoftware/cspell-dicts#how-to-create-a-new-dictionary)
1. Creating a Language Extension
   Once the dictionary is published, an extension can be created.
   - The repository is here: [VS Code Spelling Dictionary Extensions](https://github.com/streetsidesoftware/vscode-cspell-dict-extensions)

**Comment by oSethoum** [comment]
@Jason3S  Thank You !
