### ISSUE TITLE
Support for Ruby

### ISSUE THREAD

**Issue by zdrummond** [streetsidesoftware/vscode-spell-checker#171]
Thanks for the great extension. Its been invaluable while writing JS. 

Any chance support for more languages will be added, like Ruby?

**Comment by Jason3S** [comment]
Yes, it would be great to support Ruby!

The basic thing needed is a list of keyword. See: [cSpell Dictionaries](https://github.com/Jason3S/cspell-dicts). Python is a great example.

I try to include most of the programming languages into the spelling extension by default.

**Comment by zdrummond** [comment]
So to be clear; if we can come up with an equivalent ruby keyword list, like the python.txt<https://github.com/Jason3S/cspell-dicts/blob/master/python/python.txt> list, then we can get it working on Ruby files?

On Jan 19, 2018, 12:00 AM -0800, Jason Dent <notifications@github.com>, wrote:

Yes, it would be great to support Ruby!

The basic thing needed is a list of keyword. See: cSpell Dictionaries<https://github.com/Jason3S/cspell-dicts>. Python is a great example.

I try to include most of the programming languages into the spelling extension by default.

**Comment by Jason-Rev** [comment]
Yes. Do a pull request with a list of keywords and common library names and
functions, we can create support for Ruby.

**Comment by rjshenk** [comment]
@Jason-Rev Do you know if there is any progress on this? I might work on this if no one else is.

**Comment by Jason3S** [comment]
@rjshenk That would be wonderful!
Please see: [streetsidesoftware/cspell-dicts: How to create a new dictionary](https://github.com/streetsidesoftware/cspell-dicts#how-to-create-a-new-dictionary)

**Comment by zdrummond** [comment]
@Jason-Rev I never got a chance to work on it. I might be able to throw something together when I have some time off in a couple of weeks, but if you have a chance, go for it!

**Comment by rjshenk** [comment]
This `python.txt` file is what needs to be made for ruby right? https://github.com/streetsidesoftware/cspell-dicts/blob/master/packages/python/python.txt

Ruby keywords could come from here? https://docs.ruby-lang.org/en/2.2.0/keywords_rdoc.html
Ruby popular gem names could come from here? https://rubygems.org/stats

**Comment by Jason3S** [comment]
@rjshenk yes, that is the idea.

**Comment by dalinhuang99** [comment]
I got a list of ruby keywords + ruby on rails keywords here:

```
__ENCODING__
__LINE__
__FILE__
BEGIN
END
alias
and
begin
break
case
class
def
defined?
do
else
elsif
end
ensure
false
for
if
in
module
next
nil
not
or
redo
rescue
retry
return
self
super
then
true
undef
unless
until
when
while
yield
action
ActionController
ActionView
ActiveRecord
ADDITIONAL_LOAD_PATHS
application
ARGF
ArgumentError
ARGV
Array
asset
association
Attachment
attributes
@base_path
BasicSocket
Benchmark
Bignum
Binding
Block
Callback
Case
CGI
CGIMethods
Class
ClassInheritableAttributes
Comparable
ConditionVariable
Config
Configuration
connection
Continuation
CROSS_COMPILING
Data
Date
DateTime
Delegater
Delegator
Device
Digest
Dir
dispatcher
display
DomainName
DRb
DRbIdConv
DRbObject
DRbUndumped
Enumerable
ENV
EOFError
ERB
Errno
Exception
FALSE
FalseClass
Fcntl
Fiber
File
FileList
FileTask
FileTest
FileUtils
Fixnum
Float
FloatDomainError
format
frozen
GC
Gem
GetoptLong
Hash
hidden
image
IndexError
Inflector
Integer
Interrupt
invalid
invalid?
IO
IOError
IPSocket
Kernel
key
kind
LN_SUPPORTED
load
LoadError
LocalJumpError
location
Logger
Mail
Marshal
MatchData
MatchingData
Math
Method
model_name
Module
Monitor
Mutex
Mysql
MysqlError
MysqlField
MysqlRes
NameError
NIL
NilClass
NoMemoryError
NoMethodError
notify
NotImplementedError
NoWrite
Numeric
Object
object_id
ObjectSpace
Observable
Observer
open
OPT_TABLE
params
ParseDate
PGconn
PGError
PGlarge
PGresult
PLATFORM
Precision
Proc
Process
PStore
Queue
quote
Rake
RakeApp
RakeFileUtils
RAKEVERSION
Range
RangeError
Rational
readonly
Record
records
Regexp
RegexpError
RELEASE_DATE
request
Request
responses
RUBY
RUBY_PLATFORM
RUBY_RELEASE_DATE
RUBY_VERSION
RuntimeError
sad asdasd
ScanError
scope
ScriptError
SecurityError
send
session
Signal
SignalException
SimpleDelegater
SimpleDelegator
Singleton
SizedQueue
Socket
SocketError
Source
StandardError
STDERR
STDIN
STDOUT
String
StringScanner
Struct
Sweeper
Symbol
SyntaxError
system
SystemCallError
SystemExit
SystemStackError
target
Task
TCPServer
TCPSocket
template
Template
test
Text
Thread
ThreadError
ThreadGroup
Time
timeout
TOPLEVEL_BINDING
to_s
touch
Transaction
true
TRUE
TrueClass
type
TypeError
Type (namespaced)
UDPSocket
UnboundMethod
UNIXServer
UNIXSocket
URI
Url
Verbose
VERSION
YAML
ZeroDivisionError
```

**Comment by d2s** [comment]
Latest Ruby documentation is located at:
https://ruby-doc.com/core/doc/keywords_rdoc.html

Besides of those keywords, the _Class Index_ list (on the sidebar of the documentation) could be copy-pasted to the list of words in the dictionary. Though I'm rather sure there could exist more automated way to parsing the documentation structure (as it would be more maintainable in the long run).

Each of the core Ruby classes have their own _Methods_ that most likely would be needed to be added to the dictionary later. For example, https://ruby-doc.com/core/Array.html page has list of methods for the class in the left side sidebar. One approach could be to copy-paste those from each of the core documentation pages, or write a script to do that automatically.

If someone has extra time and wants to improve software experience for Ruby programmers out there, this could be a way to do it.

**Comment by el-ethan** [comment]
Hello! I am not clear on the status of Ruby support. My current version of the extension does not seem to support Ruby still, so I found this post, and started to add a new dictionary for Ruby, only to find that one has already been added here: https://github.com/el-ethan/cspell-dicts/tree/master/dictionaries/ruby

What work still needs to be done for the extension to work with Ruby? I would love to contribute if I can to move this forward, but not clear about what needs to be done. Thanks!

**Comment by Jason3S** [comment]
@el-ethan 

Support for Ruby is built into the spell checker. But it might not be turned on.

There are a few ways to turn it on:

## Using the Spell Checker Configuration:

   1. Open a Ruby file.
   2. Click on: ![image](https://user-images.githubusercontent.com/3740137/107873836-c816b780-6eb5-11eb-9f68-771c2a523ce2.png)
   3. Click the checkbox:  
    ![image](https://user-images.githubusercontent.com/3740137/107873859-e54b8600-6eb5-11eb-90e7-0096ee7769f0.png)
    or
    ![image](https://user-images.githubusercontent.com/3740137/107873902-16c45180-6eb6-11eb-81d4-c742adf5cae1.png)
    ![image](https://user-images.githubusercontent.com/3740137/107873910-280d5e00-6eb6-11eb-8caa-8a1f8fd8d118.png)

## Use the command: `F1` `Enable Spell Checking Document Language`

1. Open a Ruby file, then use the `Enable Spell Checking Document Language` command.
![image](https://user-images.githubusercontent.com/3740137/107874007-e204ca00-6eb6-11eb-985b-f522f1d24875.png)
 
## Use the VS Code Preferences:
    
![image](https://user-images.githubusercontent.com/3740137/107874088-622b2f80-6eb7-11eb-81c9-22f954c48015.png)

**Comment by lawnchamp** [comment]
@Jason3S You are the real mvp.
