### ISSUE TITLE
German words are always case-sensitive

### ISSUE THREAD

**Issue by Shimazu1** [streetsidesoftware/vscode-spell-checker#1757]
Inside my VS Code settings.json I have
```json
{
   "cSpell.caseSensitive": false
}
```
But I stile get errors for words like 'fehler' but 'Fehler' is fine.

![grafik](https://user-images.githubusercontent.com/9071680/153392063-e9b7c714-1b44-42b5-8090-ebf899cc3040.png)

Is this a bug or more a misconfiguration of my side?

**Comment by Jason3S** [comment]
@Shimazu1,

It is non-obvious on how to do this.  This [Case Sensitivity - CSpell](https://cspell.org/docs/case-sensitive/#by-file-type) article helps, but I don't think it is clear enough.

It needs to be overwritten using `languageSettings`.

<img width="667" alt="image" src="https://user-images.githubusercontent.com/3740137/153547643-3e2280e6-49b9-4697-8ec6-2e69357e2d50.png">


```js
    "cSpell.languageSettings": [
        {
            "languageId": "javascript,typescript,json", // The file type you want to apply the setting to.
            "locale": "*",  // "*" matches all locales, "de" will only match German.
            "caseSensitive": false
        }
    ]
```

**Comment by Shimazu1** [comment]
Thanks, it worked and also for this great extension!
