### ISSUE TITLE
"transform" is marked as a forbidden word and I can't find why

### ISSUE THREAD

**Issue by FrankHermes** [streetsidesoftware/vscode-spell-checker#1765]
After a recent update, all occurrences of the word "transform" are marked Forbidden in my code. 
I write a lot of Unity C# code and transform is a really basic type there. It should not be marked forbidden. 
I haven't set it as a forbidden word as far as I know, also adding it to my workspace or user settings as doesn't help. What is wrong here? I use en-us and nl-nl dictionaries.

**Comment by Jason3S** [comment]
@FrankHermes,

The Dutch dictionary has marked `transform` as forbidden, as a result, whenever the locale is `nl`, the word will be forbidden. To get around this, add `transform` to the `ignoreWords`.

<img width="364" alt="image" src="https://user-images.githubusercontent.com/3740137/154030094-47f20751-e684-404b-ba08-a703bb07e64e.png">

You can also turn off Dutch in C# files, that would have the same effect.

I hope that helps.

Kind regards,
Jason
