### ISSUE TITLE
Words limits

### ISSUE THREAD

**Issue by kibbage** [streetsidesoftware/vscode-spell-checker#1771]
It looks like there is a limit to the number of words that can be added to the dictionary in VS Code. I have added about 100 words to the workspace dictionary and now I can't add any more. Is there a way to get around this limit?

**Comment by Jason3S** [comment]
@kibbage,

There isn't a limitation on number of words stored in the workspace settings. It is possible that there is a syntax error with the file causing changes to be ignored. The extension cannot fix errors in VS Code configuration files.

An alternative is to have the extension create a `cspell.json` file and a custom dictionary. If you right click on an unknown word, you will get something like the following:
<img width="315" alt="image" src="https://user-images.githubusercontent.com/3740137/154422456-bc6ce2c3-8711-46fe-8a61-26cf37388c0c.png">

Just choose `Create a CSpell Configuration File` and the `Create a Custom Dictionary File`.

**Comment by kibbage** [comment]
That worked perfectly!

Thank you,

Ken Gladden

If you don’t hear back from me in 24 hours call or text (650) 400-7814
