### ISSUE TITLE
Disabling color highlighting and problems count for file names in the explorer

### ISSUE THREAD

**Issue by floatingpurr** [streetsidesoftware/vscode-spell-checker#181]
Hello, is there a way to avoid spell checker coloring file names and displaying problems count in the explorer tab?

**Comment by brookslyrette** [comment]
It would be really nice to have this as an option.

**Comment by Jason3S** [comment]
Note, this is a change in VS Code behavior. They show ALL problem counts.
It might be controlled by this setting:

```js
  // Show Errors & Warnings on files and folder.
  "problems.decorations.enabled": true,
```

**Comment by brookslyrette** [comment]
Can we make `vscode-spell-checker` issues come up as warnings, not errors? Ideally, this would be a configuration setting.

**Comment by Jason3S** [comment]
They are set to `Information` by default.

VS Code is doing the rest.

![image](https://user-images.githubusercontent.com/3740137/36436671-4217dd18-1665-11e8-83be-77c339234419.png)
