### ISSUE TITLE
occasional word segements flagged as mispelled

### ISSUE THREAD

**Issue by brewster1134** [streetsidesoftware/vscode-spell-checker#1810]
I have noticed this in the past, but correctly spelled words, will flag a partial of that word as a separate mispelled word. i have removed custom settings to test it, but it still gets flagged

below is the current one i noticed, but i will try to find the previous cases where i noticed this issue

<img width="289" alt="Screen Shot 2022-03-04 at 6 56 11 PM" src="https://user-images.githubusercontent.com/217428/156865200-61335518-27d9-4d5d-b712-4795eb30d2bc.png">
.

other i have been finding...
* typo `Delet` in `onAddDeleteFeedback`
* typo `Inval` in `isResetTokenInvalid`

**Comment by Jason3S** [comment]
@brewster1134,

I'm going to need a bit more information. 

Questions:
1. What type of files have the issue? JavaScript, CPP?
2. Are there any regular expressions defined in `ignoreRegExpList`?
   The most common cause of partial word issues come from over aggressive regular expression in `ignoreRegExpList`.

**Comment by brewster1134** [comment]
aha! so i had tried removing my custom `ignoreRegExpList` settings to troubleshoot, but nothing changed. found i just had to restart my extension host, and now i can see edits in real time :) 

so i did find the rules causing an issue.

e.g. this rule `"id = .+"` was causing the `INVAL` typo 

i add a non word char to it `"[\W]id = .+"`, which resolves the problem, so now i can keep messing with my regexp to get them working just right. 

thank you for sending me down the right path!

**Comment by Jason3S** [comment]
@brewster1134,

The extension has an experimental feature to help with writing regular expressions. It is far from perfect, but it might help.

See https://github.com/streetsidesoftware/vscode-spell-checker/issues/650#issuecomment-756635327 on how to show the RegExp Explorer.
