### ISSUE TITLE
How to override `blockCheckingWhen*` in language scope? (markdown)

### ISSUE THREAD

**Issue by eckdanny** [streetsidesoftware/vscode-spell-checker#1830]
Context: I use `cspell` mostly for markdown in docs, but I have to set [`blockCheckingWhenTextChunkSizeGreaterThan`](https://github.com/streetsidesoftware/vscode-spell-checker/blob/1b032f7b8af8da181d2f90019099f2b9ba170db8/packages/_server/src/config/cspellConfig.ts#L296) config option to some arbitrary big int. This is to accommodate [badges](https://shields.io/) (which may include a base64-encoded svg in them).

Similar to: #1256

### Is there no way to declare `blockCheckingWhen*`s on a <samp>LanguageSetting</samp> scope?

My workspace settings:

```json
"cSpell.blockCheckingWhenTextChunkSizeGreaterThan": 5000,
"cSpell.languageSettings": [
  {
    "languageId": "markdown",
    "ignoreRegExpList": [
      "[^\\s]{40,}",
    ]
  }
],
```

vscode extension: `@2.1.7`

Maybe just not clear to me from docs _how_ one does a <samp>language-overridable</samp> spec.

**Comment by Jason3S** [comment]
@eckdanny,

VS Codes does not have a friendly way of setting this, you have to use their language overrides in the `settings.json` file:

```
    "[markdown]": {
        "cSpell.blockCheckingWhenTextChunkSizeGreaterThan": 500
    }
```

**Comment by eckdanny** [comment]
_Ahhh!_ So that's what is meant by the <samp>language-overridable</samp> scope.

Reading the [vscdoe-spell-checker docs](https://streetsidesoftware.com/vscode-spell-checker/docs/configuration) I was (incorrectly) reaching for a _top-level_ <samp>cSpell.languageSettings[]</samp> or <samp>cSpell.overrides[]</samp> config.

Feel free to close @Jason3S, unless you want to leave it for <samp>label=FAQ</samp> PR.
