### ISSUE TITLE
Misplaced indicator

### ISSUE THREAD

**Issue by TheZoker** [streetsidesoftware/vscode-spell-checker#184]
Is it intended, that the light bulb suggesting me to edit the text is placed at the very left of the line?

![screenshot_2018 02 17_20h51m09s_002_](https://user-images.githubusercontent.com/1368405/36345055-6fb5c480-1424-11e8-9698-64dfb5c48dee.png)

If not please fix it :)

**Comment by Jason3S** [comment]
@TheZoker Thank you.
