### ISSUE TITLE
xml files are not spell-checked by default?

### ISSUE THREAD

**Issue by BenLeadbetter** [streetsidesoftware/vscode-spell-checker#1858]
With a default configuration and these two files in my workspace root:
```
<!--test.xml-->
<test>Some mispeled text</test>
```
```
<!--test.txt-->
<test>Some mispeled text</test>
```

The `.txt` is spellchecked and the `.xml` is not. Am I missing some configuration?

Thanks in advance! :-)

**Comment by Jason3S** [comment]
You have to turn it on for that file type.

Try:
`F1` `Enable Spell Checking Document`
<img width="344" alt="image" src="https://user-images.githubusercontent.com/3740137/160628379-189b2d20-dde5-49c9-9ab6-c9829420f77a.png">

**Comment by BenLeadbetter** [comment]
Ah ok great. I ran this command and it added this config to my settings, which was the item I was looking for. Cheers!
```
"cSpell.enableFiletypes": [
        "xml"
    ]
```
