### ISSUE TITLE
"onDidChangeDiag" message in the console at each editor document switch.

### ISSUE THREAD

**Issue by boltex** [streetsidesoftware/vscode-spell-checker#1859]
I'm developing an extension, which shows / changes the opened document in an editor. When running my extension through an extension host to test/debug it, at each change of shown file in the editor i get something outputting about "onDidChangeDiag" in the console like so:

![image](https://user-images.githubusercontent.com/847716/160748692-309191e9-9a2c-4cd6-9d8e-df5f268eef13.png)

I tracked it down to your extension... That didn't happen a little while ago. (git blame says Jason Dent added that 4 days ago). From vscode documentation, a onDidChangeDiagnostic event just means the status of the document has changed with regards to it's total estimated compilation/linting/checking related states.

Maybe you forgot to remove this console output? https://github.com/streetsidesoftware/vscode-spell-checker/blob/eb7229a0a4ac0901c02c9c5dbe8a28eb399d3887/packages/client/src/statusbar.ts#L150

I just use vscode.workspace.openTextDocument on some opened editor with the opened file in preview mode to switch the viewed file. So it's not even a hack, and shouldn't be considered an error if onDidChangeDiagnostic triggers.... If I may suggest so...

Anyways, great product! You rock!

**Comment by Jason3S** [comment]
@boltex,

Sorry about that. It was left over from a debugging session.

**Comment by Jason3S** [comment]
@boltex,

I'll release a new version in a day or two. In the meantime, you can install it from here: [Release v2.1.10 · streetsidesoftware/vscode-spell-checker](https://github.com/streetsidesoftware/vscode-spell-checker/releases/tag/v2.1.10)

**Comment by Jason3S** [comment]
@boltex,

I have released 2.1.11 to the VS Code marketplace.
