### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Alex-Zongo** [streetsidesoftware/vscode-spell-checker#1863]
- Issue Type: `Performance`
- Extension Name: `code-spell-checker`
- Extension Version: `2.1.7`
- OS Version: `Darwin x64 20.3.0`
- VS Code version: `1.65.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///var/folders/51/gkw58slj4gq47xhbrz7hl1j40000gn/T/streetsidesoftware.code-spell-checker-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by Jason3S** [comment]
@Alex-Zongo,

Please re-open if you are able to provide more details.

**Comment by Alex-Zongo** [comment]
@Jason3S , thanks for your response and sorry for the late response. Actually, I only had to update vs-code to correct the error...
