### ISSUE TITLE
Cannot import using `@` syntax after another import

### ISSUE THREAD

**Issue by PigeonF** [streetsidesoftware/vscode-spell-checker#1878]
I am trying to set up a `cspell.json` for CI which looks like this

```json
{
  "$schema": "https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json",
  "version": "0.2",
  "language": "en",
  "noConfigSearch": true,
  "import": ["@cspell/dict-de-de/cspell-ext.json"]
}
```

running `cspell-cli --config ci/cspell.json` works fine.

However, if I try to load this in VS Code using

```json
{
  "cSpell.import": ["${workspaceFolder}/ci/cspell.json"]
}
```

as the `.vscode/settings.json`, I get the following error:

```text
[Error - 8:53:57 PM] 2100	2022-04-05T18:53:57.599Z	Error: /home/pigeon/Desktop/example/ci/@cspell/dict-de-de/cspell-ext.json does not exist.
    at w (/home/pigeon/.vscode/extensions/streetsidesoftware.code-spell-checker-2.1.11/packages/_server/dist/main.js:2:517903)
    at o.addFile (/home/pigeon/.vscode/extensions/streetsidesoftware.code-spell-checker-2.1.11/packages/_server/dist/main.js:2:750692)
    at /home/pigeon/.vscode/extensions/streetsidesoftware.code-spell-checker-2.1.11/packages/_server/dist/main.js:2:724164
    at Array.forEach (<anonymous>)
    at o.processSettings (/home/pigeon/.vscode/extensions/streetsidesoftware.code-spell-checker-2.1.11/packages/_server/dist/main.js:2:724147)
    at /home/pigeon/.vscode/extensions/streetsidesoftware.code-spell-checker-2.1.11/packages/_server/dist/main.js:2:746346
    at async ne (/home/pigeon/.vscode/extensions/streetsidesoftware.code-spell-checker-2.1.11/packages/_server/dist/main.js:2:744931)	
```

It seems like the `cspell.json` interprets the `@cspell/dict-de-de/cspell-ext.json` as a relative path instead of a package name (?)

**Comment by Jason3S** [comment]
@PigeonF,

I tried to reproduce what your are seeing.

Where did you install the German dictionary (where is the node_modules directory)?

If you do `cspell-cli trace --config ci/cspell.json Wasser` what do you get for the `de-de` dictionary?

<img width="540" alt="image" src="https://user-images.githubusercontent.com/3740137/161834979-6912878f-dce9-4ba6-9319-ecadc79d1cdd.png">

**Comment by PigeonF** [comment]
Running `cspell-cli trace --config ci/cspell.json Wasser` I get `Wasser * de-de                /usr/lib/node_modules/@cspell/dict-de-de/de_DE.trie.gz` (I think I ran `npm install -g @cspell/dict-de-de` at some point).

For what its worth, I also have the `streetsidesoftware.code-spell-checker-german` extension installed in VS code

**Comment by PigeonF** [comment]
I have created a repository to help with the reproduction: https://github.com/PigeonF/issue-1878.

The german sentence in the readme is not highlighted in VS code, but I do not know if that is because all the dictionary files are found, or because of the error shown in the screenshot

**Comment by Jason3S** [comment]
@PigeonF,

The extension will search your current project for `@cspell/dict-de-de/cspell-ext.json`, since it is not finding it, you get the error. It will not search the global install.

## Using Global Installs
One workaround, but not ideal for a CI environment, is to do this instead:

```
$ npm install -g @cspell/dict-de-de
$ npx cspell-cli link add @cspell/dict-de-de
$ npx cspell-cli README.md
```

The `link` command tells `cspell` how to find the globally installed dictionary. Then you do not need the 
`"import": ["@cspell/dict-de-de/cspell-ext.json"]`. This will also work for the VS Code extension.

See: `npx cspell-cli link --help`.

## CI environment

1. Add `package.json` to your project:
   ```
   $ npm init
   $ npm install cspell-cli @cspell/dict-de-de
   ```
2. Checking Spelling on the CI platform
   ```
   npm install
   npx cspell-cli --config ci/cspell.json "**"
   ```

**Comment by PigeonF** [comment]
Alright, thank you for the help ❤️
