### ISSUE TITLE
Corner case for CamelCase

### ISSUE THREAD

**Issue by AlekSi** [streetsidesoftware/vscode-spell-checker#19]
Consider this:

> … and sends PUBLISHed messages to …

Here `PUBLISH` is capitalized because it's packet type (in MQTT, if you wonder). Spell checker tells me `PUBLIS` is not a word. Maybe it can also check words `PUBLISH` and `ed`?

**Comment by Jason3S** [comment]
I had to decide which way to go for that one.

Most of the code I have seen have associate the last upper case letter with the next word.  Even in GO, this is true.  See *HTMLEscape*.

**Comment by AlekSi** [comment]
Can we go both ways? Check both `PUBLIS`/`Hed` and `PUBLISH`/`ed` (`HTML`/`Escape` and `HTMLE`/`scape`) and show error only if both are incorrect.

**Comment by AlekSi** [comment]
But that can give false positives… I guess I will write `PUBLISH'ed` when it will work (it gives me error at the moment) or `PUBLISH-ed` (works now).

**Comment by Jason-Rev** [comment]
Hmm, I need to think about what will give the best experience.  I might be able to have it as a setting.

**Comment by thorn0** [comment]
Another corner case are the words like "don't" and "can't". In camel case, they're usually written like `dont` and `cant`. E.g. `dontModifyModel`. Of course, the spellchecker complains about the word "dont". But if we simply add it to the dictionary, "dont" in the comments also won't detected.

**Comment by Jason3S** [comment]
Good point.  I don't have a good solution for that yet.

**Comment by isra-fel** [comment]
Hi, Jason, I found "VMware" seemed to be the same case. The warning says `Unknown word "Mware"`.
Why do I get the same warning even after I put "VMware" in the user dictionary?

**Comment by Jason3S** [comment]
@isra-fel good example. The issue has to do with the rules to break up CamelCase words.

**Comment by Paul-Dempsey** [comment]
FWIW proper punctuation for this usage is PUBLISH-ed ;-)
