### ISSUE TITLE
`chevron_left/right` text appearing in configuration pane ribbon

### ISSUE THREAD

**Issue by olipratt** [streetsidesoftware/vscode-spell-checker#190]
### Issue

When the Spell Checker config pane is opened in a narrow window, presumably `<` and `>` chevron icons are supposed to appear in the ribbon at the top, but instead just large `chevron_left` and `chevron_right` text appears. See this image:

![chevron_text](https://user-images.githubusercontent.com/18227628/36632910-747aa958-1984-11e8-8b61-31ff5de9c65a.png)

### My machine

VS Code: 1.20.1
Code Spell Checker: 1.6.4
Windows 10

**Comment by Jason3S** [comment]
@olipratt ,

I tried to reproduce this. Are there any special steps?

**Comment by olipratt** [comment]
Hi - Sorry for the delay in responding, but still occurs for me on the same machine, now plugin version 1.6.10 and code 1.24.1.

Specifically just:

- Open any file
- Right click -> `Show Spell Checker Configuration Info`
- Make sure the pane that opens is narrow enough so not all the headings can appear, and those large words just appear.

I even tried completely uninstalling the plugin in VS code, and re-installing it, but same problem.

**Comment by Jason3S** [comment]
Thank you.
It is a HTML/CSS render issue. I have not been able to reproduce it myself.

**Comment by Jason3S** [comment]
This screen no longer exists. Thank you for the bug report.
