### ISSUE TITLE
Property loadDefaultConfiguration is not allowed.

### ISSUE THREAD

**Issue by Zamiell** [streetsidesoftware/vscode-spell-checker#1923]
![image](https://user-images.githubusercontent.com/5511220/165755486-9a694991-cb9b-4372-b508-38f98d3e20f1.png)

But it is allowed, as per [this page](https://cspell.org/types/cspell-types/interfaces/CSpellSettings/#loaddefaultconfiguration), so this is a bug.

My guess is that the schema for the extension forgot to be updated when the option was added.

**Comment by Jason3S** [comment]
@Zamiell,

The extension hasn't been updated since that option went in.

**Comment by Zamiell** [comment]
I see. What is the process to update the extension? Can we get a new version released?

**Comment by Jason3S** [comment]
I'll try and do it today or tomorrow morning.

**Comment by Jason3S** [comment]
@Zamiell Please try out the extension from: [Releases · streetsidesoftware/vscode-spell-checker](https://github.com/streetsidesoftware/vscode-spell-checker/releases)

**Comment by Zamiell** [comment]
Yup, that seems to work great. Thank you sir!
