### ISSUE TITLE
How to show all spell error, or go to next spell error?

### ISSUE THREAD

**Issue by wqking** [streetsidesoftware/vscode-spell-checker#1978]
Thanks for the good job. I would like to ask, is there way to do,

1, Display all errors in one file, or even better, in a folder?
2, Is there any way to go to next/previous spell error in the editor?

What I want to do is to see spell errors easily instead of browsing the whole source file line by line.

**Comment by Jason3S** [comment]
> 1, Display all errors in one file, or even better, in a folder? 

The [cspell](https://www.npmjs.com/package/cspell) tool can help with this. It will spell check whole projects.

> 2, Is there any way to go to next/previous spell error in the editor?

If you open the VS Code Keyboard Shortcuts and type `Spell Go to`, you should see something like the following. You can bind your own keys.
<img width="689" alt="image" src="https://user-images.githubusercontent.com/3740137/171113092-500a1a25-eff3-42ae-93d5-41136a91594b.png">

**Comment by wqking** [comment]
Thank you for the quick reply. That's quite helpful.
