### ISSUE TITLE
Suggestion tip does not always appear next to the word with the error

### ISSUE THREAD

**Issue by alanosman** [streetsidesoftware/vscode-spell-checker#198]
Hi, I am writing markdown help files using visual code and using this great plug-in for spell checking.  However, I am finding that the suggestion light bulb icon is not appearing in the correct place.  On paragraphs of text it appears at the start of the paragraph or at the beginning of a line.  This makes you have to work a bit harder to find the suggestion.  It would be nice if it would appear under the typo.

For example:
![image](https://user-images.githubusercontent.com/2914981/37474409-a0c62070-2846-11e8-9af7-f3458164fd5d.png)

Thanks!

**Comment by Jason3S** [comment]
Hello @alanosman,

Thank you for the feedback. I agree that it is not ideal. Sadly, the extension doesn't have any control over the placement of the lightbulb. That is VS Code.

But you can use a keyboard shortcut to get the suggestions to show up: `ctrl-.` (control period) or `cmd-.` (command period on mac) when the cursor is in the word.

**Comment by Jason3S** [comment]
Closing stale issues.
