### ISSUE TITLE
Web support.

### ISSUE THREAD

**Issue by proJM1** [streetsidesoftware/vscode-spell-checker#1986]
Can we please add web support so that we can use the extension on the vscode for the web?
vscode for the web: https://vscode.dev

**Comment by Jason3S** [comment]
@proJM1,

Thank you for the feedback. This a duplicate of #1554.

This extension does work on [GitHub Codespaces](https://docs.github.com/en/codespaces/overview) and [Gitpod](https://www.gitpod.io/).
