### ISSUE TITLE
Consider on-boarding to VS Code Sponsors

### ISSUE THREAD

**Issue by isidorn** [streetsidesoftware/vscode-spell-checker#1998]
VS Code PM here 👋 

Consider on-boarding to VS Code sponsorship. It is as easy as adding:
```json
"sponsor": {
  "url": "https://opencollective.com/code-spell-checker"
}
```

to your `package.json`

More details here
https://github.com/microsoft/vscode-discussions/discussions/14

**Comment by Jason3S** [comment]
@isidorn,

Thank you!

**Comment by isidorn** [comment]
Thanks for doing that.
Make sure to use latest `vsce 2.9.1` when publishing your extension so this is respected.

**Comment by Jason3S** [comment]
@isidorn,

Thank you. It is working on Insiders:
<img width="358" alt="image" src="https://user-images.githubusercontent.com/3740137/172838192-42aa9f25-8005-4f17-9b93-9f6399ca8238.png">

**Comment by isidorn** [comment]
Cool, thanks!

fyi @sandy081
