### ISSUE TITLE
Sorting of custom dictionary - upper case first

### ISSUE THREAD

**Issue by rhshadrach-8451** [streetsidesoftware/vscode-spell-checker#1999]
Related to #113

When I add a new word to my custom dictionary, it gets automatically sorted, which is great. And I also love how it only sorts based on case after first ignoring case (e.g. "abc" appears next to "ABC"). However I noticed that it is sorting so that upper case comes after lower case (e.g. "ABC" comes after "abc"). While I don't think there is any universal standard of sorting, most tools I work with do put upper case before lower - e.g. Python's sort and *nix's sort. 

Is lower case first intentional?

The version I'm using is 2.2.1.

**Comment by Jason3S** [comment]
@rhshadrach-8451,

It is just using the built-in compare function.

```ts
function sortWords(words: string[]): string[] {
    return words.sort(compare);
}

function compare(a: string, b: string): number {
    return a.localeCompare(b);
}
```

See: [String.prototype.localeCompare() - JavaScript | MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare)

Because the `locale` is not defined, it uses the default locale and preferences from your OS.

**Comment by rhshadrach-8451** [comment]
Thanks @Jason3S. Does it make sense to be opinionated here? E.g.

    a.localeCompare(b, undefined, { caseFirst: 'upper' })

I *believe* this will still put 'B' after 'a', but am a bit out of my element here so please correct me if this is wrong. Our use case is the dictionary is part of our repository, and so I would like the order to be well-defined amongst developers without having to modify settings outside of our development environments (e.g. OS wide setting). Exposing a setting for the extension default to current behavior would certainly work well.

**Comment by Jason3S** [comment]
JavaScript sort behavior:

```sh
node -e "
arr = 'grape Apple apple orange Pear bananna pineapple'.split(' ');
console.log(arr.sort());
console.log(arr.sort((a, b) => a.localeCompare(b)))
console.log(arr.sort((a, b) => a.localeCompare(b, undefined, { caseFirst: 'upper' })))
console.log(arr.sort((a, b) => a.localeCompare(b, undefined, { caseFirst: 'upper', sensitivity: 'case' })))
"
```

Result:

```
[ 'Apple', 'Pear', 'apple', 'bananna', 'grape', 'orange', 'pineapple' ]
[ 'apple', 'Apple', 'bananna', 'grape', 'orange', 'Pear', 'pineapple' ]
[ 'Apple', 'apple', 'bananna', 'grape', 'orange', 'Pear', 'pineapple' ]
[ 'Apple', 'apple', 'bananna', 'grape', 'orange', 'Pear', 'pineapple' ]
```

It is possible to add a sort option.

The current sorting choice was chosen to make sure accented characters appeared next to non-accent characters with the same base.

A PR request is welcome or contact [Support - Street Side Software](https://streetsidesoftware.com/support/) to schedule the work.

**Comment by Jason3S** [comment]
@rhshadrach-8451,

If this is important for your organization, a PR request is welcome or contact [Support - Street Side Software](https://streetsidesoftware.com/support/) to schedule the work.
