### ISSUE TITLE
New words are Not in current spell checker?

### ISSUE THREAD

**Issue by brmonaghan** [streetsidesoftware/vscode-spell-checker#2017]
![meirl (12) {ACCQMIEESB42abAlqSJ8zTWmk5s_VL7aTj5fYHupoUyny-j5BARptyTsZljdQypb-33---9ImTwQ_30ZfZ6fmbRGd6E86m4mBA}](https://user-images.githubusercontent.com/71337477/173661178-7f40100a-6bc0-4ee4-a871-c18cec7601be.png)
We are right now recovering from a pandemic, and you guys haven't still made coronavirus A WORD? REALLY? Can you please fix your spell checker with words such as contactless, curbside, drive-thru, and especially coronavirus? I would really appreciate that.

**Comment by brmonaghan** [comment]
Just did it! Thanks so much @Jason3S

**Comment by Jason3S** [comment]
@brmonaghan,

Thank you.
