### ISSUE TITLE
Document incorrectly references "enableCompoundWords" / "disableCompoundWords"

### ISSUE THREAD

**Issue by dashleysmith** [streetsidesoftware/vscode-spell-checker#2035]
Should be "allowCompoundWords"

**Comment by dashleysmith** [comment]
Sorry, I should have been more specific. But now reading it again I can see that I was misreading the documentation..

I was trying to configure vscode settings.. but there the config entry has a different name: "allowCompoundWords". 
![image](https://user-images.githubusercontent.com/34645359/174867906-ef81d319-747e-4a93-b987-72bb84a58f94.png)

So I amend my report: nothing is incorrect.. but its a bit confusing. Maybe the same setting name can be supported in both places?

**Comment by Jason3S** [comment]
@dashleysmith,

I can see the confusion.

The  setting name is `allowCompoundWords` (true/false). The full in-document directives are called: `enableAllowCompoundWords` and `disableAllowCompoundWords`, but to make it less wordy, the shorter forms are accepted.
