### ISSUE TITLE
(GUI) Spell Checker Preferences -> FILE -> Active Dictionaries displays negative-referenced dicts

### ISSUE THREAD

**Issue by david-fong** [streetsidesoftware/vscode-spell-checker#2048]
Following streetsidesoftware/cpsell-dicts#1101, I recently did this in my cSpell.json file:

```json
"languageSettings": [
  {
    "languageId": "cpp",
    "dictionaries": ["!cpp", "cpp-refined"]
  }
],
```

I was confused because the gui (Spell Checker Preferences -> FILE -> Active Dictionaries) shows that the `cpp` dict is active, but when I type words into that file from the `cpp` dictionary such as "cudarrr", it has squiggles since I negative referenced the `cpp` dictionary. If I change the negative reference to a positive reference, the squiggles on "cudarrr" go away and the GUI is the same (no problem there). Ie. The GUI seems to not be reflecting the active dictionaries properly for this scenario.

Screenshot:

![image](https://user-images.githubusercontent.com/42986768/176355570-c01e721d-e8a4-4b79-b8d5-a2ba2446482d.png)

**Comment by Jason3S** [comment]
@david-fong,

I believe this was cause by stale display data. This has been fixed in the latest release by #2060.
