### ISSUE TITLE
vscode-spell-checker activating failed in vscode-server(vscode for web)

### ISSUE THREAD

**Issue by fly2tomato** [streetsidesoftware/vscode-spell-checker#2050]
The latest vscode-server version 4.4.0 upgraded to VS Code v1.66.2. https://github.com/coder/code-server/releases
But when I installed code spell checker from the extension market in code server, the installed version v2.2.3 activating failed. The error was:
Activating extension 'streetsidesoftware.code-spell-checker' failed: The language client requires VS Code version ^1.67.0 but received version 1.66.2.

![image](https://user-images.githubusercontent.com/11885550/176609436-2cc3cf1f-ea28-4d9a-9bd7-0b6f6a8da6dd.png)

How can I install the right version of code spell checker for my vscode-server ?

**Comment by Jason3S** [comment]
@fly2tomato,

It is very frustrating that this happened.

If it is possible, choose `v2.2.1`
<img width="564" alt="image" src="https://user-images.githubusercontent.com/3740137/176620882-fcec797c-5daf-4466-98a2-22724ae58140.png">

See: https://github.com/streetsidesoftware/vscode-spell-checker/issues/2013#issuecomment-1155487054

**Comment by Jason3S** [comment]
@fly2tomato,

Doesn't this work?:
```
code-server --install-extension streetsidesoftware.code-spell-checker@2.2.1
```

**Comment by fly2tomato** [comment]
It works! Thx a lot! Hope the extension version installed in code-server market could match code-server in the future~

**Comment by Jason3S** [comment]
@fly2tomato,

A few things happened:
1. #1995, had the unexpected requirement of needing VS Code 1.67.0. This was not correctly reflected in the extension's manifest.
1. It is not possible to remove extension versions from the marketplace, meaning non-upgraded versions of VS Code and Code servers would download the wrong version.
2. `coder-server` release are a couple of months behind, as soon as they release a new version, the latest version of the extension should work.
