### ISSUE TITLE
package.json is checked but not opend when startup

### ISSUE THREAD

**Issue by tjx666** [streetsidesoftware/vscode-spell-checker#2089]
I notice that when I restart vscode, although package.json is closed, the spell checker problems is still shown in problems panel.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/179446216-9053e292-1842-4037-b8a6-051e766d9b09.png">

Reproduce steps:

1. make a folder contains package.json, write some spell wrong words in it
2. close package.json
3. reload vscode
4. you will see problems of spell check in problems panel

versions:

```
MacOS: 12.4
VSCode: 1.70.0-insider
streetsidesoftware.code-spell-checker: v2.3.1
```

**Comment by Jason3S** [comment]
@tjx666,

VS Code and other extensions will often load `package.json` in the background, this in turn causes the spell checker to check them.

You can tell the spell checker to ignore them: VS Code -> preferences -> `spell ignore paths`

<img width="460" alt="image" src="https://user-images.githubusercontent.com/3740137/179502655-0248024a-0695-4f3b-b582-eff7dc9a8b29.png">

<img width="117" alt="image" src="https://user-images.githubusercontent.com/3740137/179502702-2d9483dc-43fd-49fc-a346-63eb9b5cb164.png">

**Comment by tjx666** [comment]
Before check one loaded file, can't this extension check weather it is opened? @Jason3S

**Comment by tjx666** [comment]
This seems had been fixed
