### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by bmx4life77** [streetsidesoftware/vscode-spell-checker#2099]
- Issue Type: `Bug`
- Extension Name: `code-spell-checker`
- Extension Version: `2.3.1`
- OS Version: `Windows_NT ia32 6.2.9200`
- VS Code version: `1.69.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by Jason3S** [comment]
@bmx4life77,
 
Please provide some information about the issue.

**Comment by Jason3S** [comment]
@bmx4life77,

More information is needed. Please give some details about what went wrong.
