### ISSUE TITLE
Since version 2.2.2, the extension does not work for VSCode v1.62.3

### ISSUE THREAD

**Issue by luoway** [streetsidesoftware/vscode-spell-checker#2115]
Extension Name: Code Spell Checker
Extension Version: 2.2.2 and 2.2.3
OS Version: macOS Monterey 12.0.1
VS Code version: 1.62.3

![20220801-120206](https://user-images.githubusercontent.com/12523415/182070966-187863dd-70dd-4e1b-a1f7-44bbe51bec9a.png)
![20220801-120119](https://user-images.githubusercontent.com/12523415/182070972-83a8c5e3-5d79-4697-8e37-5b7795ced823.png)

Only userWords exists in my user settings.
![20220801-120351](https://user-images.githubusercontent.com/12523415/182071126-50e3854f-f16a-4650-835c-0268263e5854.png)

When the extension does not work, there is not Spell Checker status in the status bar.
![20220801-120805](https://user-images.githubusercontent.com/12523415/182071167-0ac1eb13-b288-4d49-8c36-d06878ddfe13.png)

**Comment by luoway** [comment]
The problem is solved after upgrading vscode to version 1.69.2 and the extension to 2.3.4

**Comment by Jason3S** [comment]
Related to #2013
