### ISSUE TITLE
Context menu suggestion: use a submenu

### ISSUE THREAD

**Issue by ddirks** [streetsidesoftware/vscode-spell-checker#2120]
By default, I see quite a few (seven, in my case) context menu entries for Code Spell Checker. As a result my context menu has grown quite long.

I see in Issue #1296 that I can remove *all* cSpell entries from the context menu. That helps with the menu crowding, but forces me to use the command palette when I have a misspelled word.

Have you considered using a submenu structure in the context menu? That way a single "Spelling" item could expand to all the appropriate menu items.

Thanks for your consideration!

**Comment by Jason3S** [comment]
@ddirks,

Thank you for bringing this up. The last I had checked, sub-menus were not available to extensions, but I will check again to see if it is possible.

**Comment by Jason3S** [comment]
@ddirks,

It looks like it is now possible: [Contribution Points | Visual Studio Code Extension API](https://code.visualstudio.com/api/references/contribution-points#menu-example)

**Comment by ddirks** [comment]
@Jason3S,

Thanks for looking into this suggestion, and for the fast implementation! I appreciate it (and I think others will too)...
