### ISSUE TITLE
Adding words to .cspell.json breaks Prettier formatting

### ISSUE THREAD

**Issue by tobysmith568** [streetsidesoftware/vscode-spell-checker#2151]
Hey :)

When I use the Code Action to add a word to my .cspell.json the file reverts back to the original formatting. This means I have to manually open the file and save it again so that Prettier likes it.

Would you be open to a feature where vscode-spell-checker uses Prettier programmatically to format the file before it writes it, if it can detect the presence of a prettier config?

Prettier expose APIs for both [resolving a Prettier config](https://prettier.io/docs/en/api.html#prettierresolveconfigfilepath--options) and [formatting a given string](https://prettier.io/docs/en/api.html#prettierresolveconfigfilepath--options).

If you'd be interested, I'd be happy to try and give implementing it a go myself?

**Comment by Jason3S** [comment]
@tobysmith568,

What about an options to have the extension open the `cspell.json` file in the editor and save it? I think that would allow for the automatic formatting to happen. 

I would prefer not to call other tools if possible.

**Comment by tobysmith568** [comment]
Hey @Jason3S

>I would prefer not to call other tools if possible.

That's understandable :)

I don't have a load of VS Code extension knowledge, would your suggestion open the file visibly?

If so, is it possible to trigger VS Code to run formatting on the file behind the scenes? Perhaps with the `vscode.executeFormatDocumentProvider` [Link](https://code.visualstudio.com/api/references/commands#commands) ?

**Comment by Jason3S** [comment]
@tobysmith568,

`vscode.executeFormatDocumentProvider` might be a good option. I'll take a look.

**Comment by Jason3S** [comment]
@tobysmith568,

Thank you for the suggestion. That turned out to be the best solution.
