### ISSUE TITLE
How can I get list of all spelling mistakes across the project with a single command?

### ISSUE THREAD

**Issue by codewithdpk** [streetsidesoftware/vscode-spell-checker#2155]
How can I get list of all spelling mistakes across the project withing the single command?

**Comment by Jason3S** [comment]
@codewithdpk,

Similar to #1978

The [cspell](https://www.npmjs.com/package/cspell) command line tool can help with that.

## Using a command line tool:

### Using Node
From the terminal view:

```sh
npx cspell "**"
```

To get help: `npx cspell lint --help`.


### Using Docker
From the terminal view:

```sh
docker run -v $PWD:/workdir ghcr.io/streetsidesoftware/cspell:latest "**"
```

To get help: `docker run -v $PWD:/workdir ghcr.io/streetsidesoftware/cspell:latest lint --help`.
