### ISSUE TITLE
Pasting a text led to unexpected state

### ISSUE THREAD

**Issue by enamcse** [streetsidesoftware/vscode-spell-checker#2157]
When I pasted a piece of text, it entered into an unexpected state like the video.
Info: It was a markdown file. The os is Windows 10. Feel free to ask me if any more info is needed.

![](https://media1.giphy.com/media/frbxFQ0XcKgNGjwuv9/giphy.gif)

**Comment by Jason3S** [comment]
@enamcse,

I think this is a VS Code issue with how Diagnostics are displayed and shown.

In any case, please add some sample files and what paste to this issue. I'll try to reproduce it.

**Comment by Jason3S** [comment]
@enamcse,

Would you please list the other extension you have installed? It seem like one of them might be causing the issues to expand inline.

**Comment by enamcse** [comment]
> @enamcse,
> 
> Would you please list the other extension you have installed? It seem like one of them might be causing the issues to expand inline.

Here is the list:

```
> code --list-extensions
alefragnani.project-manager
alexcvzz.vscode-sqlite
codezombiech.gitignore
cschlosser.doxdocgen  
dbaeumer.vscode-eslint
donjayamanne.git-extension-pack
donjayamanne.githistory
eamodio.gitlens
ecmel.vscode-html-css
esbenp.prettier-vscode
github.classroom
GitHub.vscode-pull-request-github
jeff-hykin.better-cpp-syntax
ms-azuretools.vscode-docker
ms-python.python
ms-python.vscode-pylance
ms-toolsai.jupyter
ms-toolsai.jupyter-keymap
ms-toolsai.jupyter-renderers
ms-vscode-remote.remote-containers
ms-vscode-remote.remote-ssh
ms-vscode-remote.remote-ssh-edit
ms-vscode-remote.remote-wsl
ms-vscode.cmake-tools
ms-vscode.cpptools
ms-vscode.cpptools-extension-pack
ms-vscode.cpptools-themes
ms-vscode.powershell
ms-vsliveshare.vsliveshare
ms-vsliveshare.vsliveshare-audio
p1c2u.docker-compose
rebornix.ruby
redhat.java
streetsidesoftware.code-spell-checker
twxs.cmake
Tyriar.theme-sapphire
VisualStudioExptTeam.vscodeintellicode
vscjava.vscode-java-debug
vscjava.vscode-java-dependency
vscjava.vscode-java-pack
vscjava.vscode-java-test
vscjava.vscode-maven
vscodevim.vim
wingrunr21.vscode-ruby
xabikos.JavaScriptSnippets
yzhang.markdown-all-in-one
ziyasal.vscode-open-in-github
```

**Comment by enamcse** [comment]
> @enamcse,
> 
> I think this is a VS Code issue with how Diagnostics are displayed and triggered.
> 
> In any case, please add some sample files and what to paste to this issue. I'll try to reproduce it.

I copied the first two sentences of the 3rd paragraph of page 15 of the book "Deep Learning" by I. Goodfellow, Y. Bengio, and A. Courville from [this link](https://www.deeplearningbook.org/contents/intro.html). The lines are also pasted below:

```
Neuroscience has given us a reason to hope that a single deep learning algorithmcan solve many diﬀerent tasks. Neuroscientists have found that ferrets can learn to“see” with the auditory processing region of their brain if their brains are rewiredto send visual signals to that area (Von Melchner et al., 2000).
```

**Comment by Jason3S** [comment]
@enamcse,

I'm able to paste it into an empty markdown file just fine. It works just fine. I'm able to see the spelling issues and the editor is stable.

Please use Extension Bisect to find the one causing the issue. See: [Visual Studio Code extension bisect utility](https://code.visualstudio.com/blogs/2021/02/16/extension-bisect)
<img width="549" alt="image" src="https://user-images.githubusercontent.com/3740137/185129668-60e0cbf7-bbbb-4c76-9c6e-09aa570f22b3.png">

**Comment by Jason3S** [comment]
@enamcse,

I expect that you figured it out.
