### ISSUE TITLE
Regex Modifiers - multiple lines (or .* across newline characters)

### ISSUE THREAD

**Issue by gadams999** [streetsidesoftware/vscode-spell-checker#2166]
Hi,

I'm looking for guidance on how (if) cSpell can ignore headers in a markdown file. I use Dendron to take notes, and cSpell alerts on created links in the front matter. For instance:

```
---
id: 4pcgvl1j9l06o9h6l8eezuu
title: General IT Stuff
desc: General it stuff
updated: 1660947089860
created: 1659889222987
---

Things that are not super important or used often.

[[it.general.onlogic-pc]]
```

The characters in `id` get flagged. I've got a working regex expression that works in regex101 of `/---.*---/sg`, but it's not working with the extension. I could filter based on `/^id:.*/gm`, but I'm curious if ignoring the entire front matter can be accomplished, as some files have significant attributes and values.

Appreciate the hard work on cSpell, I'm learning all kinds of ways to optimize VS Code!

**Comment by Jason3S** [comment]
@gadams999,

This question was also asked here: https://github.com/streetsidesoftware/cspell/discussions/3456#discussioncomment-3437952
