### ISSUE TITLE
Cspell dose not mark all wrong words in latex

### ISSUE THREAD

**Issue by chengkun0010** [streetsidesoftware/vscode-spell-checker#2177]
<img width="1207" alt="Snipaste_2022-08-27_18-06-30" src="https://user-images.githubusercontent.com/77137493/187025624-c43b0144-3573-4d2a-9b80-60230a9993fe.png">

Please see the picture.
In the line 506, the wrong word "hhhhsadad" has been marked. Howerver, in line 508, the wrong word "hhhhsadad" does not marked.
Thank you for your answers.
My vscode is version 1.70.

**Comment by Jason3S** [comment]
@chengkun0010,

There might be an error with the Math exclusions. Would you be able to create attach a file with the issue as well as your CSpell settings?
