### ISSUE TITLE
Disabling spell checking for user does not work

### ISSUE THREAD

**Issue by wysokinskim** [streetsidesoftware/vscode-spell-checker#2185]
I wanted to disable spell checking. I chose appropriate option from command palette. It added `"cSpell.enabled": false`  configuration key to my properties file. It did not have any effect. Spell checking was still active even after I restarted VSC.

**Comment by Jason3S** [comment]
@wysokinskim,

If you see this: 
<img width="65" alt="image" src="https://user-images.githubusercontent.com/3740137/187412789-d9bfc90a-16d7-4815-bf18-c5c4ac8656de.png">
Then it is not checking the file.

Workspace level settings override User level settings. This is a confusing issue with VS Code.

Also, check any `cspell.json` files for `enabled`.
