### ISSUE TITLE
Plain Text and Shell Files

### ISSUE THREAD

**Issue by oraclejavanet** [streetsidesoftware/vscode-spell-checker#2186]
Hello. This is a feature request. Would like request support for plain text files or UNIX/Linux shell files. Thank you.

**Comment by Jason3S** [comment]
@oraclejavanet,

The spell checker should work for different file types, but you might need to enable it.

1. Open a file you want to spell check.
1. Hover or click on: 
   <img width="60" alt="image" src="https://user-images.githubusercontent.com/3740137/188256039-5859f1eb-ee8f-4d38-aab7-8a42387ce891.png">

It should tell you why it is not checked.

**Comment by jeronimd** [comment]
I did this and it says "File is NOT in the workspace.", How can I resolve this?

**Comment by Jason3S** [comment]
@jeronimd,

Did you get it to work?

**Comment by jeronimd** [comment]
Yes, good to go.
