### ISSUE TITLE
v2.7.0 failed to read config file

### ISSUE THREAD

**Issue by zcqno1** [streetsidesoftware/vscode-spell-checker#2187]
spell checker failed to read config file in a v2.7.0 version. Has try reinstall and reload, not help.

![image](https://user-images.githubusercontent.com/11766057/188253876-a0bc1d6b-54a5-4a23-80ce-7a08744e2ae0.png)
![image](https://user-images.githubusercontent.com/11766057/188253885-0179d534-5ea3-4c77-a97c-c65725e77962.png)

install v2.6.0, it works fine

![image](https://user-images.githubusercontent.com/11766057/188253906-185de1ad-6dd0-4c49-841c-41aed68a9cef.png)

**Comment by Jason3S** [comment]
@zcqno1,

VS Code failed to install the extension, but it keeps a copy of the failed attempt.

Please delete `/root/.vscode-server/extensions/streetsidesoftware.code-spell-checker-2.7.0`.

**Comment by zcqno1** [comment]
@Jason3S thanks for your quick response ❤️ 
Delete the broken 2.7.0 package and reinstall, did solve the problem.
