### ISSUE TITLE
Bug: Spell Check Only Workspace Files isn't work as expected.

### ISSUE THREAD

**Issue by icetbr** [streetsidesoftware/vscode-spell-checker#2192]
A flag for this would be welcome. Thanks.

**Comment by Jason3S** [comment]
@icetbr,

Please help me understand the issue. What are you trying to do?

1. Ignore files that are not part of the workspace?
   <img width="877" alt="image" src="https://user-images.githubusercontent.com/3740137/188326667-a5469087-8a92-471e-b571-636c2b6c490f.png">
3. Ignore files that are in the workspace like: `.vscode/settings.json`
   
   <img width="955" alt="image" src="https://user-images.githubusercontent.com/3740137/188326732-53052ee1-c8c9-44fa-97cb-d16c5ee9ce0d.png">

5. Something else.

**Comment by icetbr** [comment]
Hi, it's 1, but it doesn't do me any good!

~/.config/Code/User/settings.json

![image](https://user-images.githubusercontent.com/1111617/188329816-0f4319f7-0950-469d-8ab0-9aac7aa82ccb.png)

**Comment by icetbr** [comment]
Is this equivalent? because it doesn't help either

![image](https://user-images.githubusercontent.com/1111617/188330857-b3ececb3-ea33-47af-8600-c4eb0013bab0.png)

**Comment by Jason3S** [comment]
It should be `"files": ["/**"],`

**Comment by Jason3S** [comment]
@icetbr,

I'll update the extension tomorrow.
