### ISSUE TITLE
Add option to include files and dirs included .gitignore

### ISSUE THREAD

**Issue by tom-pollak** [streetsidesoftware/vscode-spell-checker#2196]
My main use-case is that I have repos with git worktrees of the same repo inside of it, for example
```
notes/
  drafts/
  papers/
```

where drafts is both a git branch and a folder in main

At the moment spell checker ignores all files inside drafts/ as it is included in .gitignore, is there a way to disable this?

**Comment by Jason3S** [comment]
If you add the following `cspell.json` file to your `drafts` directory in your `drafts` branch, it will tell the spell checker to not use `.gitignore` for that directory.

**`cspell.json`**

```json
{
    "useGitignore": false
}
```

**Comment by Jason3S** [comment]
It is now possible to set `cSpell.useGitignore` at the folder level in a [Multi-root Workspace](https://code.visualstudio.com/docs/editor/multi-root-workspaces).

<img width="978" alt="image" src="https://user-images.githubusercontent.com/3740137/188400634-2eed6d96-1686-4723-b8da-5a047733d1db.png">
