### ISSUE TITLE
"Spell: Create a Spell Configuration File" command fails with "Unable to read file..." error

### ISSUE THREAD

**Issue by JeffJacobson** [streetsidesoftware/vscode-spell-checker#2212]
## Steps to reproduce

1. Install version 2.6.0 or later of extension
2. Make sure there is no cspell config file in the directory
3. Select _Spell: Create a Spell Configuration File._ from command palette.
4. Select either _cspell.json_ or _cspell.config.yaml_.

The error message below appears and the file is not generated.
> Unable to read file 'c:\\Users\\_UserName_\\source\\repos\\_project-name_\\cspell.json' (Error: Unable to resolve nonexistent file 'c:\\Users\\_UserName_\\source\\repos\\_project-name_\\cspell.json')

Error does not occur following the same steps with version 2.5.4

## Notes

If I add a `cspell.json` file containing just a pair of curly braces (`{}`) and then try the steps above, it will ask if I want to overwrite the existing file and then work correctly. (If the `cspell.json` file is completely empty, I get the message _Unexpected end of JSON input_ instead of being asked if I want to overwrite.)

## OS info

|            |                                                 |
| ----------:| ----------------------------------------------- |
| Edition    | Windows 10 Enterprise                           |
| Version    | 21H2                                            |
| OS build   | 19044.1889                                      |
| Experience | Windows Feature Experience Pack 120.2212.4180.0 |

**Comment by Jason3S** [comment]
@JeffJacobson,

Thank you. That corresponds to when we switched how the extension works with the file system. It might be an issue that is unique to windows. I'll take a look.

Kind regards,
Jason

**Comment by Jason3S** [comment]
@JeffJacobson,

Thank you for raising this issue.

**Comment by JeffJacobson** [comment]
> Thank you for raising this issue.

You're welcome
