### ISSUE TITLE
Extension not working Versions 2.2.2+

### ISSUE THREAD

**Issue by leviFrosty** [streetsidesoftware/vscode-spell-checker#2225]
System details:
macOS Monterey v 12.1
Apple M1 Pro
Memory 16GB

VSCode information:
Version: 1.65.2 (Universal)
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T14:33:49.188Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 21.2.0

**Actual result:**
Extension will only load if rolled back to version 2.2.1 or older. If on newer version: 2.2.2+ and when trying to enter any command from command pallet, I get an error like so:
<img width="328" alt="image" src="https://user-images.githubusercontent.com/79994715/190030011-707de1ca-3bda-4b8f-9428-d8793b7887ca.png">

**Expected Result:**
Be able to spellcheck files on latest release version

**Comment by Jason3S** [comment]
@leviFrosty,

This is related to #2013. The extension needs a newer version of VS Code. If you update VS Code, it will work.

**Comment by leviFrosty** [comment]
@Jason3S Thanks for the help.
