### ISSUE TITLE
Markdown isn't spell-checked at all...

### ISSUE THREAD

**Issue by neilyoung** [streetsidesoftware/vscode-spell-checker#2244]
I need to let my markdown text spell check in StackEdit. Don't know what happened. Recall it worked somewhen.

Doesn't work anymore. 

"contxext" - not detected....:(

Code:
Version: 1.71.2
Commit: 74b1f979648cc44d385a2286793c226e611f59e7
Date: 2022-09-14T21:07:15.900Z (6 days ago)
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: No

**Comment by Jason3S** [comment]
@neilyoung,

There is not enough information to help out here.

If the file is spell checked, you will see: <img width="56" alt="image" src="https://user-images.githubusercontent.com/3740137/191555705-406751b7-c77e-4227-a946-dd99fd1027d5.png">

If it shows something else, hovering over / clicking on <img width="58" alt="image" src="https://user-images.githubusercontent.com/3740137/191556013-77e5038f-4bfc-46b8-bd01-76dc11e8c132.png"> should help find out why.

**Comment by neilyoung** [comment]
@Jason3S:

Thanks.

> If the file is spell checked, you will see: image

Having this:

<img width="99" alt="image" src="https://user-images.githubusercontent.com/731020/191556513-fab66780-8047-4f89-84fc-43bb29eea495.png">

Hovering over it says: "Issues 100: \<file-name\> is spell checked"

> If it shows something else, hovering over / clicking on image should help find out why.

I don't have such an icon/icon combination. But clicking on the icon above just opens the settings page. Markdown spell check is enabled.

Any other log?

What I'm missing is the explicit marking of the wrongly typed word. Of any wrongly typed word

**Comment by neilyoung** [comment]
Maybe I'm messing up something. I was under the impression, that wrongly typed words are clearly marked by a red underline. But it seems they are blue and get somehow lost under the tons of unknown words after the limit is reached.

Can be closed

**Comment by Jason3S** [comment]
@neilyoung,

There are several things going on here:
1. `unknown words` are the errors.
2. If a word it unknown, it marks it as an error or warning depending upon your settings.
3. It is easy to add your technical terms to your own dictionary. Most software related terms are already in [dictionaries/software-terms](https://github.com/streetsidesoftware/cspell-dicts/tree/main/dictionaries/software-terms), but feel free to make a PR to add new ones.
4. There is a limit to the number of ~~~ shown. By default it is 100.

**Comment by neilyoung** [comment]
OK, but that doesn't convince me. I really don't get why things like "ecxessive" remain undiscovered, just because I have more than 100 unknown words. Why is StackEdit for instance w/o having to load special dictionaries (or even this Github issue editor) perfectly able to discover those errors and cSpell not? 

Anyway, don't bother. I now know the insufficiencies and can circumvent.
