### ISSUE TITLE
quick fix is replacing the hole text with the suggestion SCSS 

### ISSUE THREAD

**Issue by rynex-zv** [streetsidesoftware/vscode-spell-checker#2268]
When I select a suggestion my whole text being replaced with it see this 2 images:
![image](https://user-images.githubusercontent.com/29366919/193463794-0e0cb83c-559c-4b31-ab54-a13a56aa92a3.png)
![image](https://user-images.githubusercontent.com/29366919/193463818-71fe732e-fa77-4f4f-b387-4da92c265381.png)

**Comment by Jason3S** [comment]
@rynex-zv,

This is a bug with VS Code: https://github.com/microsoft/vscode/issues/151190
Looks like they broke another rename provider.

In `.vscode/settings.json`, add the following:

```json
"[scss]": {
    "cSpell.fixSpellingWithRenameProvider": false
}
```

**Comment by Jason3S** [comment]
@rynex-zv,

If you click on `operator` and hit `F2` (rename), and change it to `operators` you will see that the same thing happens.
