### ISSUE TITLE
per file dictionaries

### ISSUE THREAD

**Issue by dmoody256** [streetsidesoftware/vscode-spell-checker#228]
I would like to customize the spell checker so that it checks against certain dictionaries for a given file.

I know I can add words in the comments for a given file to control per file spell checking, but unfortunately the content of the source files is strictly controlled so I am not allowed to add comments which are not directly relevant to the code. Some rules to an extension in a code editor are not relevant enough.

I can however modify the vscode workspace file, so I would like a way to define per file dictionaries in the workspace settings.

**Comment by Jason3S** [comment]
This is "almost" possible. A few months ago, I was working on a feature to allow for individual file overrides based upon glob matching.

It is currently working for the command line linter, but not the plug-in.

**Comment by Jason3S** [comment]
I believe this is fixed. If this is still an issue, please one a new issue describing the desired behavior.

Kind regards,
Jason
