### ISSUE TITLE
Remote SSH: linux

### ISSUE THREAD

**Issue by tangyoha** [streetsidesoftware/vscode-spell-checker#2282]
Hello, how to use the plug-in in the remote working directory? The plug-in cannot be installed in the remote directory, and the error is' XHR failed '

**Comment by Jason3S** [comment]
@tangyoha,

Would you be able to give more details on your setup?
Are you using a plug-in to connect to the remote directory?
Are you running VS Code remotely?

Do you have an example set on how this could be reproduced by sone one else?

**Comment by tangyoha** [comment]
@Jason3S,
Yes, I am running voce remotely. use [remote ssh](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh)

**Comment by Jason3S** [comment]
@tangyoha,

I'm able to use this use fine. Is it still and issue?


<img width="287" alt="image" src="https://user-images.githubusercontent.com/3740137/201362530-12d939a4-f546-4a7c-b085-1cc94f687721.png">
