### ISSUE TITLE
How to use macOS built-in spelling dictionary?

### ISSUE THREAD

**Issue by suliveevil** [streetsidesoftware/vscode-spell-checker#2284]
`~/Library/Spelling/LocalDictionary`

**Comment by Jason3S** [comment]
@suliveevil,

It is already possible to add it yourself:

`Preferences` -> `Settings` -> `Spell Custom Dictionaries` 

<img width="964" alt="image" src="https://user-images.githubusercontent.com/3740137/194764150-641e8966-6544-4944-9555-e0ae71f6ae5b.png">


**`settings.json`**
```json
"cSpell.customDictionaries": {
    "LocalDictionary": {
        "path": "~/Library/Spelling/LocalDictionary",
        "description": "User LocalDictionary",
        "addWords": true
    },
    "usr/share/dict/words": {
        "path": "/usr/share/dict/words",
        "description": "System Shared Dictionary",
        "addWords": false
    }
}
```

**Comment by suliveevil** [comment]
Thank you very much. 🥰
