### ISSUE TITLE
Extension will not activate

### ISSUE THREAD

**Issue by ahibbard-cornelisnetworks** [streetsidesoftware/vscode-spell-checker#2291]
I have installed v2.2.3 installed on my M1 MacBook Pro. However, the Runtime Status continues to say "Not yet activated." I have have confirmed that the extension is enabled and have reloaded my window multiple times, but with change.

**Comment by Jason3S** [comment]
@ahibbard-cornelisnetworks,

I'm guessing you are running an older version of VS Code. Please see: https://github.com/streetsidesoftware/vscode-spell-checker/issues/2013#issuecomment-1155487054

It is also possible that part of the extension is missing. VS Code keeps a cache of all extensions. You might need to delete that and reinstall them. See #388. 

On my Mac, it is in `~/.vscode/extensions/streetsidesoftware.code-spell-checker-*`.
