### ISSUE TITLE
Spell Checking not enabled when file is excluded in .gitignore

### ISSUE THREAD

**Issue by kimfucious** [streetsidesoftware/vscode-spell-checker#2292]
This is a very useful extension.  Thanks for making it.

How can I get it to work on files that are excluded in the .gitignore file?

**Comment by Jason3S** [comment]
@kimfucious,

There is a setting that controls `.gitignore` usage:

`Preferences` -> `Settings` -> `spell Use Gitignore`

![image](https://user-images.githubusercontent.com/3740137/196097139-ddf0c6b4-23ab-46ac-8ee0-c96777df25e9.png)

or add it to a `cspell.json` file:

**`cspell.json`**
```json
{
   "useGitignore": false
}
```

**Comment by kimfucious** [comment]
Perfect; thanks1
