### ISSUE TITLE
Extension will not work past 2.2.1 on Catalina 10.15.7

### ISSUE THREAD

**Issue by jwest2023** [streetsidesoftware/vscode-spell-checker#2298]
I am on a MacBook 15,4 on Catalina 10.15.7. For some reason when I use cSpell past version 2.2.1 the spell check does not appear to be working (ie. spelling errors don't show up as problems in my vscode window). Any help would be appreciated!

![Screen Shot 2022-10-19 at 1 12 54 AM](https://user-images.githubusercontent.com/116141612/196602965-00746cc6-a20e-4aeb-9ce7-bc9b8f90d586.png)

![Screen Shot 2022-10-19 at 1 12 07 AM](https://user-images.githubusercontent.com/116141612/196602995-c8406f55-3722-48ee-9ccc-d6cc89a6c158.png)

**Comment by Jason3S** [comment]
@jwest2023,

I'm guessing you are running an older version of VS Code. Please see: https://github.com/streetsidesoftware/vscode-spell-checker/issues/2013#issuecomment-1155487054
