### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by josejb007** [streetsidesoftware/vscode-spell-checker#2304]
- Issue Type: `Bug`
- Extension Name: `code-spell-checker`
- Extension Version: `2.10.1`
- OS Version: `Windows_NT x64 10.0.19044`
- VS Code version: `1.70.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by Jason3S** [comment]
@josejb007,

Please paste / attach the data.

**Comment by Jason3S** [comment]
Closed due to no reponse.
