### ISSUE TITLE
High Load with large files

### ISSUE THREAD

**Issue by Jason3S** [streetsidesoftware/vscode-spell-checker#2338]
I recently had to uninstall the extension as the CPU load was getting so bad typing was beginning to lag. There is definitely some kind of performance issue with the extension.

<img width="199" alt="image" src="https://user-images.githubusercontent.com/1090602/201329600-3be421eb-3fab-4fa1-afc7-3f0de0ff122c.png">

You might be able to notice when I uninstalled it. I found the offender using this process.
https://apple.stackexchange.com/a/393075

_Originally posted by @phawxby in https://github.com/streetsidesoftware/vscode-spell-checker/issues/507#issuecomment-1311567328_

**Comment by Jason3S** [comment]
@phawxby,

There is not enough information here to do anything. 

It is most likely caused by:
- a slow regular expression.
- a upgrading VS Code.

Please share any configuration you used and the type of file/s. If possible, some clear steps on how to reproduce the issue.

**Comment by phawxby** [comment]
It's hard for me to recreate a repo for this as it's a private repo. What I can say

* MacOS 12.6 (Intel)
* Node 16.18.0
* Typescript 4.0.0 (full ESM project)

As projects go this is actually fairly small, it has only been in development a few weeks but it does contain some extremely large files as it's doing data processing. One CSV file is 180MB, but at the time I didn't have it or any other files open. 

Could it have been trying to spell check files that weren't even been edited in the background?

**Comment by Jason3S** [comment]
@phawxby,

It is most likely trying to spell check the very large `.csv` files.

You can add `*.csv` to `cSpell.ignorePaths`:

<img width="1207" alt="image" src="https://user-images.githubusercontent.com/3740137/201359720-2c352b08-7e65-4dd1-854e-0bb90f37d7d9.png">

Opening a file in the editor, will cause the spell checker to try spell checking it.

When spell checking a file, VS Code sends the entire file to the extension.

**Comment by phawxby** [comment]
> @phawxby,
> 
> It is most likely trying to spell check the very large `.csv` files.
> 
> You can add `*.csv` to `cSpell.ignorePaths`:
> 
> <img width="1207" alt="image" src="https://user-images.githubusercontent.com/3740137/201359720-2c352b08-7e65-4dd1-854e-0bb90f37d7d9.png">
> 
> Opening a file in the editor, will cause the spell checker to try spell checking it.
> 
> When spell checking a file, VS Code sends the entire file to the extension.

Should it not be spell checking only the files actually being edited and abort spell checking of files which have been closed? Could this not become problematic with large snapshot files for example?

**Comment by Jason3S** [comment]
It only spell checks files that VS Code has open. When the file is closed, it stops spell checking. It should only spell check the first 500K of the file. But if the file is constantly changing, it is possible VS Code is trying to sync the file. I'll take a look.

**Comment by Jason3S** [comment]
@phawxby,

Slow regular expressions could still be the primary cause. Did you add any?

**Comment by phawxby** [comment]
No, I don't think there's actually any regular expressions in the entire project.

**Comment by LucasArruda** [comment]
I am not sure what exactly is happening, but I just found out, after some investigation, and some tips from other people's issues, that this extension is causing my VSCode to keep a constant 60% CPU usage.

I have like 12 or so files opened but this constant CPU usage happens when I am idle, like during a meeting. And it happens right after I start VSCode and it never ceases, like if it's constantly checking something or stuck processing.

Other people seem to be having the exact same issue

https://github.com/Microsoft/vscode/issues/58671#issuecomment-424514988

**Comment by Jason3S** [comment]
@LucasArruda,

I can try and help, but I will need more information. I think it is better to open a new issue, than to add to this one.

Things to try:
1. Quit VS Code and kill and Code Helper processes that are sticking around.
2. Do you have a cspell config file (cspell.json or cspell.config.yaml)? Please add a copy of it.
3. Have you added any other dictionaries or configuration like `"cSpell.ignoreRegExpList"` or `"cSpell.includeRegExpList"`
   <img width="724" alt="image" src="https://user-images.githubusercontent.com/3740137/217344701-09678a8a-18ca-448d-9d88-302acfc59550.png">
   or
   <img width="849" alt="image" src="https://user-images.githubusercontent.com/3740137/217344799-5e709a39-c66d-4afc-8228-24947cb30aa1.png">

**Comment by Jason3S** [comment]
This issue has gotten stale. No progress can be made.
