### ISSUE TITLE
How to see all mistakes?

### ISSUE THREAD

**Issue by kevinlinxc** [streetsidesoftware/vscode-spell-checker#2353]
My file is long, so it's not feasible to scroll around looking for underlines. 

Is there a way to see all of the mistakes at once? Clicking the warning sign just opens the extension settings.

**Comment by Jason3S** [comment]
You make a good point about how the warning symbol would imply listing the issues.

Please see #1978

**Comment by kevinlinxc** [comment]
Thank you. For future people, Ctrl + Shift + P to bring up the command palette, search for "Spell Go To" and click the result
