### ISSUE TITLE
Unable to add path using home directory to ignore paths

### ISSUE THREAD

**Issue by ssbarnea** [streetsidesoftware/vscode-spell-checker#2382]
While trying to prevent extension from spellchecking vscode own settings.json files I found impossible to add its path to exclude, basically because the user settings are inside home directory and not inside a workspace.

I tried any any of the options below did not work:
- `~/Library`
- `${userHome}/Library` - [see official docs](https://code.visualstudio.com/docs/editor/variables-reference)

![](https://sbarnea.com/ss/Screen-Shot-2022-12-02-12-55-29.77.png)

**Comment by Jason3S** [comment]
@ssbarnea,

Other than `${workspaceFolder:Client}`, the extension does not support VS Code task/launch substitutions. It might be a worthwhile enhancement.

The simplest solution would be to add a `cspell.json` file to your home directory:

```json
{
    "ignorePaths": ["/Library"]
}
```

**Comment by Jason3S** [comment]
Or enable: `Settings` -> `Spell: Spell Check Only Workspace Files`
<img width="953" alt="image" src="https://user-images.githubusercontent.com/3740137/205302335-d4dd04cf-7f65-4e3a-b924-9373cb447c84.png">
