### ISSUE TITLE
Please, add Business Central .AL language / extension files in default enabledLanguageIds & enableFiletypes lists

### ISSUE THREAD

**Issue by JavierFuentes** [streetsidesoftware/vscode-spell-checker#2409]
As a Business Central developer,
I would like Business Central project files to be included in the default settings of this fantastic VSCode extension.

BC files have the extension `.AL`

Currently, I can include them with any of these custom configurations:

`"cSpell.enabledLanguageIds": [ "al" ]`
`"cSpell.enabledLanguageIds": [ "*" ]`

`"cSpell.enableFiletypes": [ "al" ]`
`"cSpell.enableFiletypes": [ "*" ]`

... but, please, add it as default...

NOTE.-   
A BC project includes files with other extensions than `.AL`, like `.JSON`, `.XML`, `.RDLC`, `.WORD`, `.XLSX`

**Comment by sahanms** [comment]
Good first issue

**Comment by peterdanwan** [comment]
Hello @Jason3S and @sahanms! I would like to work on this issue if possible!

**Comment by Jason3S** [comment]
@JavierFuentes,

I didn't realize this was left open. The AL dictionary was created a few months ago, but apparently hadn't been included in the extension.

There is a new extension that has a copy of the latest dictionaries: [CSpell Bundled Dictionaries - Code Spell Checker - Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker-cspell-bundled-dictionaries). Version 1.0.3 include the AL dictionary.
