### ISSUE TITLE
Add Latin dictonary?

### ISSUE THREAD

**Issue by Cornelius-Figgle** [streetsidesoftware/vscode-spell-checker#2423]
When editing html templates, text is often replaced with Latin sentences as an example. I would like to be able to add a Latin dictionary so I don't end up with 260 info messages for Latin words

![image](https://user-images.githubusercontent.com/110970234/210241510-a04e233d-4084-4f48-ace4-6d2cd1b6d1ba.png)

Is there an easy way to do this?

**Comment by Jason3S** [comment]
@Cornelius-Figgle,

It with the `lorem-ipsum` dictionary.

A simple fix is to add to your file:

```
<!--- cspell:dictionaries lorem-ipsum -->
```

Or you can enable it in the `dictionaries` setting.

**Comment by Cornelius-Figgle** [comment]
Ah thanks! I couldn't see one in the Readme so I assumed there was none
