### ISSUE TITLE
Add all issues to dictionary not working, works fine when adding individually

### ISSUE THREAD

**Issue by Hifilo** [streetsidesoftware/vscode-spell-checker#2429]
Hello,

In a text file I have opened, I can't add all the issues to the dictionary. I get a "no matching configuration found" error. 

I can add words individually, but not all at once. From what I can tell, cspell is configured, and working. 

The text file is just a collection of aliases I have made for easy access, so I don't need to spellcheck them. 

I could probably add the file to an ignorelist, but this way I can insure the aliases won't be a problem in other files.

**Comment by Jason3S** [comment]
@Hifilo,

Are you still seeing this?

**Comment by Hifilo** [comment]
I resolved it. It seemed I was adding to the dictionary in my root, but I
didn't have the cspell.json there. copying it over resolved it.
Thanks.
