### ISSUE TITLE
Feature req: vscode: Setting to hide quick fix entries for adding to dictionary

### ISSUE THREAD

**Issue by losnappas** [streetsidesoftware/vscode-spell-checker#2430]
Please add a setting to hide the "Add x to workspace/user settings" buttons.

### Discussed in https://github.com/streetsidesoftware/vscode-spell-checker/discussions/2421

<div type='discussions-op-text'>

<sup>Originally posted by **losnappas** December 31, 2022</sup>
I couldn't find a setting for not showing those 2 options. Does a setting like that exist?

E.g. the last 2 here, I'd rather not show those because often they get in the way:

![image](https://user-images.githubusercontent.com/25119292/210135301-5f12d3fa-7822-471d-bdd0-bb9f849821a6.png)
</div>

**Comment by Jason3S** [comment]
A new setting was added: `cSpell.hideAddToDictionaryCodeActions`

<img width="707" alt="image" src="https://user-images.githubusercontent.com/3740137/211214541-56e4f390-f338-4e4d-943b-6e4f94b09a16.png">

**Comment by losnappas** [comment]
Wow, fast work! Thanks so much!

**Comment by Jason3S** [comment]
I was making a different change to the settings, so I included this one too.
