### ISSUE TITLE
how to remove forbidden words

### ISSUE THREAD

**Issue by Anderman** [streetsidesoftware/vscode-spell-checker#2452]
Warnings is a forbidden word. How do I remove this from the spell checker
Because hasWarnings and showWarning are marked as forbidden words also

**Comment by Jason3S** [comment]
@Anderman,

By default, `Warnings` is not forbidden.

There is a `trace` feature in `cspell` to help find which dictionary defines a word.

Run this in the terminal in the directory of the file with issues.
```sh
npx cspell trace Warnings
```

If a word is forbidden, it will show up in red:
<img width="502" alt="image" src="https://user-images.githubusercontent.com/3740137/212924894-15deecb4-a1c6-469a-b316-a45a21a91101.png">
