### ISSUE TITLE
Difference between "cSpell.import": [] and "cSpell.dictionaryDefinitions"?

### ISSUE THREAD

**Issue by GandalfSaxe** [streetsidesoftware/vscode-spell-checker#246]
`"cSpell.import":` is not mentioned in the docs, and from the settings description seems very similar to `"cSpell.dictionaryDefinitions"`?

**Comment by Jason3S** [comment]
These are great questions.

`cSpell.import` allows for another `cspell.json` file to be imported.

`cspell.json` can be found here: [cspell](https://github.com/Jason3S/cspell)

**Comment by GandalfSaxe** [comment]
so `cSpell.dictionaryDefinitions` is for paths for custom dictionaries and `cSpell.import` is for path to custom `cspell.json` which are... default settings?
