### ISSUE TITLE
C Spell does not work for jupyter notebook on VS Code Insiders

### ISSUE THREAD

**Issue by chandresh** [streetsidesoftware/vscode-spell-checker#2462]
C Spell does not work for jupyter notebooks:

Here is an example of a jupyter where C Spell is not showing errors:

<img width="1313" alt="Screenshot 2023-01-22 at 12 02 02 PM" src="https://user-images.githubusercontent.com/57285/213904028-ffffe5ce-4c6f-4a02-9987-42c9b7b11f3c.png">

I can see at bottom right "cSpell waiting...":

<img width="237" alt="Screenshot 2023-01-22 at 12 01 40 PM" src="https://user-images.githubusercontent.com/57285/213904200-0ce5a086-4e24-426d-920d-7986b7dbf1fa.png">

It works fine for other files:

<img width="975" alt="Screenshot 2023-01-22 at 12 00 19 PM" src="https://user-images.githubusercontent.com/57285/213904045-993cd48e-512c-4cd6-b992-9e1ab0c0f56e.png">

I have disabled all other extensions (and restarted VS Code Insiders).

<img width="464" alt="image" src="https://user-images.githubusercontent.com/57285/213904214-a3d006ba-8b21-4ed4-9e1d-30499e686cd2.png">

These are my settings related to C Spell:

`"cSpell.enabled": true,
  "cSpell.checkOnlyEnabledFileTypes": false,
  "cSpell.allowCompoundWords": true,
  "cSpell.allowedSchemas": [
    "file",
    "gist",
    "sftp",
    "untitled",
    "jupyter"
  ],
  "cSpell.enabledLanguageIds": [
    "asciidoc",
    "c",
    "cpp",
    "csharp",
    "css",
    "elixir",
    "git-commit",
    "go",
    "graphql",
    "handlebars",
    "haskell",
    "html",
    "jade",
    "java",
    "javascript",
    "javascriptreact",
    "json",
    "jsonc",
    "jupyter",
    "latex",
    "less",
    "markdown",
    "php",
    "plaintext",
    "python",
    "pug",
    "restructuredtext",
    "rust",
    "scala",
    "scss",
    "swift",
    "text",
    "typescript",
    "typescriptreact",
    "vue",
    "yaml",
    "yml",
    "ipynb"
  ],
  "cSpell.enableFiletypes": [
    "ipynb",
    "jupyter",
    "markdown",
    "python"
  ],`

VS Code version: 1.75.0-insider (Universal)

<img width="238" alt="image" src="https://user-images.githubusercontent.com/57285/213904175-78611100-778e-4b1e-b24c-44023440b532.png">

Code Spell Checker version: 2.14.0

<img width="999" alt="image" src="https://user-images.githubusercontent.com/57285/213904225-be5a22f4-6684-4973-aa54-5890415ec31f.png">

Please let me know if any other information is required.

**Comment by Jason3S** [comment]
@chandresh,

The most likely cause is that the `.ipynb` file is not part of the workspace.

<img width="44" alt="image" src="https://user-images.githubusercontent.com/3740137/213908670-4086a550-c4db-4dc2-96a0-c8e93ad32988.png">

The clock, means it cannot get the settings for the file.

Open the file in the editor, then run the command: `Spell: Show Spell Checker Configuration Info`

<img width="316" alt="image" src="https://user-images.githubusercontent.com/3740137/213908998-cd0912c5-c670-4ceb-93b5-72d55740745b.png">

<img width="781" alt="image" src="https://user-images.githubusercontent.com/3740137/213909042-bba02159-e726-4f3e-b117-9a889467b3bb.png">

Make sure `Spell Check Only Workspace Files` is not enabled:

<img width="891" alt="image" src="https://user-images.githubusercontent.com/3740137/213909153-a4d2b26f-035e-4767-a11e-8ae7210ce40d.png">

The challenge is that Notebook files are "Virtual".

**Comment by Jason3S** [comment]
Note, because it is virtual, it might show `File is NOT is the workspace.` even though it is.

**Comment by chandresh** [comment]
@Jason3S Thanks for your reply.

I do not see the "File" tab when I run the command: Spell: Show Spell Checker Configuration Info

<img width="1048" alt="image" src="https://user-images.githubusercontent.com/57285/213927247-141a22f7-6618-4080-8db0-c4ffc8bf9db9.png">

Also, this is disabled:

<img width="1031" alt="image" src="https://user-images.githubusercontent.com/57285/213927304-8c1231d0-08a8-4439-bf0c-315513f89550.png">

**Comment by chandresh** [comment]
@Jason3S But I see what you mean, so when I open a py file and run the same command, I see this:

<img width="1026" alt="image" src="https://user-images.githubusercontent.com/57285/213927514-e8bf906e-7167-4bab-88fc-0991771f8568.png">

So you are in the correct direction. So the question is how do I make sure ipynb files are in the workspace? I guess that's the other issue you opened.

**Comment by chandresh** [comment]
I am sure that the spell check used to work earlier. I recently got a new MacBook and I started facing this issue. I vaguely remember that I faced this issue before but at that time it was because of some other extension that was a memory hog. That's why I disabled all the other extensions first.

**Comment by Jason3S** [comment]
I see it working in the latest Insiders build:

![image](https://user-images.githubusercontent.com/3740137/214006155-014d7bd5-a4fc-4295-bcee-ff0bbd07f12a.png)

Please check settings: `C Spell: Allowed Schemas`
![image](https://user-images.githubusercontent.com/3740137/214006900-f1b79c62-71a3-4731-9e8c-0044dab2de97.png)

if `vscode-notebook-cell` is missing, I get:

![image](https://user-images.githubusercontent.com/3740137/214008360-1bfb5c40-a015-410f-aa1e-7236eb892b4b.png)

You will need to restart VS Code (or Command: Restart Extension Host) for the setting to take effect.

**Comment by chandresh** [comment]
@Jason3S "vscode-notebook-cell" was indeed missing. Adding this makes it work. Thanks a lot!
