### ISSUE TITLE
Getting too many results when selecting a block with multiple typos

### ISSUE THREAD

**Issue by capaj** [streetsidesoftware/vscode-spell-checker#2482]
I reported similar problem before:
https://github.com/streetsidesoftware/vscode-spell-checker/issues/1290

and while it is fixed, there is still a possibility to get much more than 20 results.
When I select this whole code and invoke the action:

```

// types from https://developers.themoviedb.org/3/discover/tv-discover
export interface IMovieDBAPICallMovieResult {
  page: number
  results: IMovieDBAPIMovie[]
  total_results: number
  total_pages: number
}

export interface IMovieDBAPIMovie {
  poster_path: string | null
  adult: boolean
  overview: string
  release_date: Date
  genre_ids: number[]
  id: number
  original_title: string
  original_language: string
  title: string
  backdrop_path: string | null
  popularity: number
  vote_count: number
  video: boolean
  vote_average: number
}

export interface IMovieDBAPITVCallResult {
  page: number
  results: IMovieDBAPITV[]
  total_results: number
  total_pages: number
}

export interface IMovieDBAPITV {
  poster_path: string
  popularity: number
  id: number
  backdrop_path: null
  vote_average: number
  overview: string
  first_air_date: Date
  origin_country: string[]
  genre_ids: number[]
  original_language: string
  vote_count: number
  name: string
  original_name: string
}

async function getMoviesAndTv(moviesUrl: string, tvUrl: string) {
  return await Promise.all([
    axios.get<IMovieDBAPICallMovieResult>(moviesUrl),
    axios.get<IMovieDBAPITVCallResult>(tvUrl)
  ])
}
```
I still get more than 20 results.

![image](https://user-images.githubusercontent.com/1305378/215469074-3ffa5d04-d140-4aae-9b8b-c5f5e93776c3.png)

**Comment by Jason3S** [comment]
@capaj,

I was able to reproduce what you are seeing.

What is happening:
1. VS Code is asking for possible actions for all the issues you have selected.
2. The spell checker is generating them one by one and sending the list back to VS Code.

I'm not sure how to improve the result. 

Maybe you could provide a bit of feedback on what you were hoping for when selecting multiple issues. What were you trying to do?

In this case, most of the issues are for the same word, but what would you expect for many different words?

**Comment by capaj** [comment]
I was not trying to interact with the spell checker at all. I wanted to pull the code into a function in this module.
I was invoking code actions menu in vscode.

Spell checker provided so many things that the action I wanted to do is pushed off the screen even on a 4k monitor.

**Comment by capaj** [comment]
> I'm not sure how to improve the result.

yes, this might be tricky from your side.
Ideally VScode could limit the number of results coming from a single extension by itself, but my guess is that even if I created and issue in VSCode repo, it would take a few years for it to get implemented.

I think this issue could be worked around on your end. When providing resuilts, you could store it in an array with a timeout for example 1 second.
When 1 second passes you remove from the item from the array.
When vscode is asking the extension for code actions, you can check the array and if it has the item you are about to return already, you can return null/empty array. 

That should make sure that we don't see duplicates in the menu, even when we select multiple words with bad spelling.

**Comment by Jason3S** [comment]
@capaj,

Thank you for the explanation. I can easily see how spelling suggestions can hide other code actions. I'll have to see if there is a better option.

VS Code controls when an extension is asked for code actions, so using a timeout might not work as expected.
