### ISSUE TITLE
Where to contribute new dictionaries?

### ISSUE THREAD

**Issue by GandalfSaxe** [streetsidesoftware/vscode-spell-checker#249]
For contributing to dictionaries, which of these two repos should we use?
* [Jason3S/cspell-dicts](https://github.com/Jason3S/cspell-dicts)
* [Jason3S/vscode-cspell-dict-extensions](https://github.com/Jason3S/vscode-cspell-dict-extensions)

I was thinking about contributing to the default latex dictionary with missing commands and packages.

**Comment by Jason3S** [comment]
Please add to the [Jason3S/cspell-dicts/packages/latex](https://github.com/Jason3S/cspell-dicts/tree/master/packages/latex) dictionary.

This will get picked up during the next build of the [cspell](https://github.com/Jason3S/cspell) library / command line tool.

* `cspell-dicts` contains the dictionary packages that can be used with `cspell`.
* `vscode-cspell-dict-extensions` contains the VS Code extensions to enable dictionaries that are packaged with the VS Code Spell Checker. These extensions use the dictionaries published from `cspell-dicts`.

**Comment by GandalfSaxe** [comment]
Alright 👍

I'm also encountering quite a few words where I would expect at least most of them to be in a normal English dictionary. A sample:

- architectured
- dimensionalities
- ephemerides
- hyperparameters
- nondimensionalized
- parallelizable
- parallelization
-performant
- GPUs

Would you want words like these contributed, as long as a google search can confirm they're legit (e.g. they exist on wiktionary)? If so, in which dictionary should they go?
