### ISSUE TITLE
Feature request: force spell-checking of a file that is not in the workspace

### ISSUE THREAD

**Issue by maxbane** [streetsidesoftware/vscode-spell-checker#2492]
It would be useful to, on a file-by-file basis, force `vscode-spell-checker` to check a file being edited even if it is not in the workspace.

My use case: 
* Jupyter notebooks. I write my notebooks as `.ipynb` files, and this is where I would like spell-checking to occur, but I do not commit the `.ipynb` files into my git repo. Instead I convert the `.ipynb` files to markdown (using a tool like [`jupytext`](https://github.com/mwouts/jupytext)), and commit the markdown into my repo. This is a best practice because `.ipynb` files are full of JSON-encoded binary blobs that change frequently, causing spurious and unreadable diffs in your commits, whereas markdown is much cleaner. My `.gitignore` file therefore ignores the `.ipynb` files, which apparently causes the spell-checker not to run on them.

(Yes I can always spell-check the markdown files, but it would be much more useful to spell-check things while I am actually writing them, in the `.ipynb` files.)

**Comment by Jason3S** [comment]
@maxbane,

I think the easiest is to disable `Spell: Use Gitignore`.
<img width="1003" alt="image" src="https://user-images.githubusercontent.com/3740137/216127614-1eb4225f-6870-4e03-be7d-d5d86513e779.png">

You can then add the globs for the things you do not want checked to `Spell: Ignore Paths`:
<img width="1049" alt="image" src="https://user-images.githubusercontent.com/3740137/216127734-1b1feb0a-c447-4848-8fb4-aff5de9d0192.png">

Kind regards,
Jason

**Comment by maxbane** [comment]
Wow, yes, that handles it! For some reason Code Spell Checker did not appear at all in Settings immediately after installing the extension. I had to restart VS Code, and only then did the Code Spell Checker section exist in Settings -- I did look for settings before posting, but couldn't find any!
