### ISSUE TITLE
causing extension host process to reach high CPU levels (100%)

### ISSUE THREAD

**Issue by enicol** [streetsidesoftware/vscode-spell-checker#250]
- Extension Name: code-spell-checker
- Extension Version: 1.6.10
- OS Version: Darwin x64 17.7.0
- VSCode version: 1.25.1

 We have written the needed data into your clipboard. Please paste:

**Comment by Jason3S** [comment]
This should be fixed, if it is still an issue, please open a new issue and refer to this one with more details.
