### ISSUE TITLE
cSpell.autoFormatConfigFile does not work properly

### ISSUE THREAD

**Issue by Zamiell** [streetsidesoftware/vscode-spell-checker#2505]
Hello,

I do not think that the `cSpell.autoFormatConfigFile` setting is working properly, if at all. In a fresh repository, I encountered two problems with it.

- Start by setting up a new repository:

```bash
mkdir cspell-test
cd cspell-test
npm init --yes
npm install cspell prettier --save
echo 'console.log("HELLOZ");' > main.js
mkdir .vscode
touch .vscode/settings.json
code . # Launch VSCode with this directory.
```

- Fill in the `.vscode/settings.json` file like this:

```jsonc
{
  // Use Prettier to format "cspell.json".
  "cSpell.autoFormatConfigFile": true,

  "[json]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "editor.formatOnSave": true,
    "editor.tabSize": 2,
  },
}
```

- Next, open the "main.js" file.
- VSCode will show the word "HELLOZ" as a spelling error.
- Right click on the word --> "Spelling" --> "Create a CSpell Configuration File."
- Press enter to confirm the choice of "cspell.json".
- Right click on the word --> "Spelling" --> "Add Words to CSpell Configuration"

**Bug 1:** You are greeted with an error popup, which is confusing and unexpected. CSpell should just be automatically adding the word to the file without any popups or errors.

- Click on the "Overwrite" button to make the error popup go away.
- Right click on the word --> "Spelling" --> "Add Words to CSpell Configuration" (again).
- It works the second time, but the file isn't formatted by Prettier. It looks like this:

```json
{
  "version": "0.2",
  "ignorePaths": [],
  "dictionaryDefinitions": [],
  "dictionaries": [],
  "words": [
    "HELLOX"
  ],
  "ignoreWords": [],
  "import": []
}
```

When we open the file and press Ctrl + s to save it, Prettier auto-formats it to:

```json
{
  "version": "0.2",
  "ignorePaths": [],
  "dictionaryDefinitions": [],
  "dictionaries": [],
  "words": ["HELLOX"],
  "ignoreWords": [],
  "import": []
}
```

Thus:

**Bug 2:** CSpell is not properly invoking Prettier when we add a file to the "cspell.json" file.

**Comment by Jason3S** [comment]
@Zamiell,

I have seen this too. It happens when there is an unsaved (unformated) copy of `cspell.json` open in an editor. The spell checker writes to the disk behind the back of the editor and then tries to have the editor format the copy on the disk. That is why you see the "overwrite".

Order of events:
- The spell checker creates a cspell.json file
- The spell checker opens it in an editor (format does not match prettier).

- When you add a word, the spell check writes to the copy on the disk
- It then ask the editor to open, format, and save it. (this is where things go wrong)

I think there is a race condition going on.

This doesn't happen if the `cspell.json` file is not open in an editor.

Is this your experience?

**Comment by Jason3S** [comment]
@Zamiell,

I agree, it is not an idea experience. Thank you for bringing this up.

**Comment by Zamiell** [comment]
> This doesn't happen if the cspell.json file is not open in an editor.

I tested this, and it does appear to be true.

So, in conclusion, I guess the bug I am reporting is that "Add Words to CSpell Configuration" does not work properly if "cspell.json" happens to be currently open.

**Comment by Zamiell** [comment]
Also, here's another thing that is probably related.

Add some newlines to the "cspell.json" file, and then do Ctrl + Shift + P --> "Save without formatting", and then close the file completely.

Now, even though, the "cspell.json" file isn't even open, you will still get the error message.

So yes, there appears to be a race condition somewhere.
