### ISSUE TITLE
Difference: text vs. plaintext?

### ISSUE THREAD

**Issue by GandalfSaxe** [streetsidesoftware/vscode-spell-checker#251]
In the [extension description](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker) the available languages are listed as such:

```markdown
Enabled File Types
* TypeScript
* JavaScript
* JSON
* Text
* Markdown
* Handlebars
* LaTex
* C, C++
* C#
* Go
* PHP
* Python
* YAML
* AsciiDoc
```

In the example of configuration further down it reads:

```json
 // Specify file types to spell check.
    "cSpell.enabledLanguageIds": [
        ...
        "plaintext",
        "text",
        ...
    ],
```

What is the difference between text and plaintext? And why are both not mentioned in the language list?

**Comment by Jason3S** [comment]
There really isn't a difference. `text` files and `plaintext` files are the same. I think VS Code now detects everything as `plaintext`.

**Comment by GandalfSaxe** [comment]
Alright. Shouldn't any mention of `text` just be removed from the extension then?
