### ISSUE TITLE
Flag Words Case sensitive

### ISSUE THREAD

**Issue by nzkarit** [streetsidesoftware/vscode-spell-checker#2518]
It would be helpful is Flag Words were case sensitive.

For example my dictionary has `API`. If it type `api` I would like that show a misspelling.

I have added `api` to flag words. But when I type `API` it is showing up as a spelling mistake, when it is correct. I only want `api` to be wrong.

Similar examples
* PuTTY vs Putty
* jQuery vs JQuery
* WinRM vs Winrm
etc

Or have a way that the case in the the dictionary is the only correct case sensitivity.

Thanks

**Comment by Jason3S** [comment]
@nzkarit,

I'm not sure if you figured it out, but `flagWords` is case sensitive.

It is possible to tell `flagWords` the replacement: `word[:replacement]` or `word[->replacement]`. Like this:
- `api:API`
- `jquery->jQuery`

Dictionaries are also case sensitive.

There is a `caseSensitive` setting.

<img width="1181" alt="image" src="https://user-images.githubusercontent.com/3740137/218948360-5966f014-c351-4bd5-8403-f80ef881f4df.png">
