### ISSUE TITLE
VS code shows problems count only and does not show changed/staged files count 

### ISSUE THREAD

**Issue by udayaks** [streetsidesoftware/vscode-spell-checker#2523]
Visual studio code shows problems count only and does not show changed/staged files count in the source control. I have tested after uninstalling Code Spell Checker and I can see changed/staged files count
![image](https://user-images.githubusercontent.com/30748755/219561545-78486f7c-16e2-4c34-a983-027ae1836a33.png)
![image](https://user-images.githubusercontent.com/30748755/219561626-9267e484-0541-4fff-a9b7-fb82d3711af2.png)
![image](https://user-images.githubusercontent.com/30748755/219561747-96aaaaff-1a1b-42c1-aea5-dc8090b54702.png)

**Comment by Jason3S** [comment]
@udayaks,

Thank you.

I'm a bit confused what this has to do with the spell checker?

There are know issues source control issues with the current version (1.75.0 and 1.75.1) of VS Code. See: https://github.com/microsoft/vscode/issues/173763

Are you seeing something else?

**Comment by udayaks** [comment]
@Jason3S ,

Oh,  I thought I was not seeing git - diff because of Code Spell Checker as I got problem's count in source control ( mainly problems tagged by Code Spell Checker ) and not the git - diff.

Thank you for informing me about other issues though. I will check this once the other known issues are fixed.

Closing this one for now.
