### ISSUE TITLE
Spell checking in source control commit pane

### ISSUE THREAD

**Issue by ctsstc** [streetsidesoftware/vscode-spell-checker#2539]
I found #109 but it was closed, and said it was "partially fixed" now.

<img width="400" alt="image" src="https://user-images.githubusercontent.com/416814/220720929-bf6f9d0c-e912-4f83-a6d1-46a14bdcacf4.png">

It seems since a semi-recent version of VSCode that we're now getting spell checking in the commit pane, but when trying to access it no context pane shows up. Right clicking gives nothing but cut/copy/paste. Clicking on "View Problem" or "Quick Fix" also does nothing.

**Comment by ctsstc** [comment]
Ah dang, well that sucks, it doesn't seem like there's a follow up to the remaining issues, just that the primary ticket was closed off? 🤔

**Comment by Jason3S** [comment]
@ctsstc,

How about opening a new issue asking them?

I'm going to close this issue for now since there isn't anything I can do.

**Comment by ctsstc** [comment]
Opened: https://github.com/microsoft/vscode/issues/175613
