### ISSUE TITLE
cSpell.json?

### ISSUE THREAD

**Issue by gandalfsaxe** [streetsidesoftware/vscode-spell-checker#260]
The documentation mentions:

> Words added to the dictionary are placed in the cSpell.json file in the .vscode folder found in the workspace. Note, the settings in cSpell.json will override the equivalent cSpell settings in settings.json.

However, I never get any words added to a `cSpell.json` (which is never created), no matter which option I choose? "Add ... to workspace/folder dictionary" both adds to workspace `settings.json` and "Add ... to user dictionary" adds to user `settings.json`. How is this mythical `cSpell.json` populated?

**Comment by GandalfSaxe** [comment]
Adding to the confusion that was never resolved with #247:

`Add: "..." to folder dictionary` -> adds word to `settings.json`
`Add: "..." to workspace dictionary` -> adds word to `settings.json`

If I create an empty `cSpell.json` manually then:

`Add: "..." to folder dictionary` -> adds word to `settings.json` AND `cSpell.json`
`Add: "..." to workspace dictionary` -> adds word to `settings.json` AND `cSpell.json`

Erhm... what is the logic here?

**Comment by lando-cal** [comment]
I'm running into this as well.
Furthermore, adding words anywhere from the little inline fixes icon doesn't seem to work, I have to right click to add.

**Comment by Jason3S** [comment]
@lando-cal would you open a new issue with examples on how the inline fixes do no work?

**Comment by razzlero** [comment]
I lost track of the ticket, but there was a bug in VSCode itself where the inline 'quick fix' button was broken. That might have been the issue @lando-cal had. I had the same issue with all quick fixes, but seems to be working again now.

**Comment by Jason3S** [comment]
@razzlero inline `quck fix` should be working. I addressed that issues a couple of months ago.

**Comment by ankostis** [comment]
According to [this comment](/issues/148#issuecomment-341506383) of #148, a new word is added into both `.vscode/settings.json` & `.vscode/cspell.json`.

But the point is to isolate modifications to a single file (e.g. for git) for when adding words.
Is there some specific issue for that, ot can i open one?

**Comment by Jason3S** [comment]
Closing stale issues.
