### ISSUE TITLE
`${userHome}` does not work

### ISSUE THREAD

**Issue by PaulRBerg** [streetsidesoftware/vscode-spell-checker#2634]
I have a global personal dictionary that I use in all of my repositories across all my devices.

I have configured it like this in my VSCode settings:

```json
"cSpell.dictionaryDefinitions": [
  {
    "name": "personal",
    "path": "${userHome}/Workspace/dictionary/dict.txt"
  }
],
```

However, this does not work because VSCode Spell Checker prepends the workspace root:

<img width="578" alt="Screenshot 2023-04-24 at 10 26 24 AM" src="https://user-images.githubusercontent.com/8782666/233927721-eb5ba81c-0357-4a12-bcf0-3a5590f62c6c.png">

The question is: is `${userHome}` not meant to be used with this extension? If that is so, how can I provide a global path to my personal dictionary, other than hard-coding the home path?

Replacing `${userHome}` with `/Users/prb` works:

<img width="367" alt="Screenshot 2023-04-24 at 10 28 02 AM" src="https://user-images.githubusercontent.com/8782666/233928041-78b7d49e-4ef6-4d65-a0f2-7443fb16e68d.png">

But I don't want to hard code the path.

**Comment by Jason3S** [comment]
@PaulRBerg,

That is a VS Code variable, not an extension variable.

Please try `~` instead: `"path": "~/Workspace/dictionary/dict.txt"`

**Comment by PaulRBerg** [comment]
Oh, I see! `~` works well, thanks.
