### ISSUE TITLE
Client: Launch Extension - cannot find module

### ISSUE THREAD

**Issue by tekumara** [streetsidesoftware/vscode-spell-checker#2635]
I'm following the [Building the extension](https://github.com/streetsidesoftware/vscode-spell-checker/blob/96732fb/CONTRIBUTE.md#building-the-extension) instructions.

I start the launch config `Client: Launch Extension (Spell Checker Root)` and get:
```
Activating extension 'streetsidesoftware.code-spell-checker' failed: Cannot find module '/Users/tekumara/code/vscode-spell-checker/packages/client/dist/extension.js' Require stack: - /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js - /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js - /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js - .
```

**Comment by tekumara** [comment]
If I manually run `yarn build` first it works. Perhaps this is missing from the launch config or docs?

**Comment by Jason3S** [comment]
@tekumara,

You are right, would you please add that step to: https://github.com/streetsidesoftware/vscode-spell-checker/blob/main/CONTRIBUTE.md#building-the-extension
