### ISSUE TITLE
Context menu options depending on configuration

### ISSUE THREAD

**Issue by gandalfsaxe** [streetsidesoftware/vscode-spell-checker#264]
Reading comment https://github.com/Jason-Rev/vscode-spell-checker/issues/247#issuecomment-413284042 makes me think that I'd be great of the context menu (quick fix Cmd+.) would be adaptable to which dictionaries are defined:

1. Always show user/workspace (although there's still [confusion](https://github.com/Jason-Rev/vscode-spell-checker/issues/247) about what the difference of "folder" and "workspace" is.)
2. Show cSpell IF the file exists.
3. Show a custom defined dictionary IF it is configured in the `settings.json` or `cSpell.json`

And the only add the word to ONE of those places.

Right now, but can't add to own dictionary files (word lists) from the context menu, but have to do so manually. Also, if `cSpell.json` is present, it's added BOTH to `settings.json` and `cSpell.json` (as the referred comment pointed out).

**Comment by Jason3S** [comment]
This will be part of the V2 Release.

**Comment by agross** [comment]
How can I disable this?

![image](https://user-images.githubusercontent.com/16245/141175571-8329e4c3-318c-47a9-82f5-9d14267b7254.png)

The link you provided above leads to all releases. I have `"cSpell.showCommandsInEditorContextMenu": false`, but that didn't change the context menu above.

**Comment by Jason3S** [comment]
@agross,

That is the code actions menu. It is not a context menu. The context menu looks like this: 
![image](https://user-images.githubusercontent.com/3740137/141303131-183be51d-ed6d-4a8c-a78d-c37ddf942234.png)

Please open a new issue with the problem and what you are hoping for. 

Here are some options that might help you to reduce the number of options:
![image](https://user-images.githubusercontent.com/3740137/141303330-4859fef9-4aaf-407a-96b0-b77983c79e6d.png)

* Number of Suggestions - controls the number of suggestions given, but there might be more it the suggestions have the same change score.
* Num Change Score - controls the approximate number of letters that can be changed to make a suggestion. Making this 1 will give far fewer words.
