### ISSUE TITLE
Merge word lists of workspace and folder instead of overriding

### ISSUE THREAD

**Issue by jota0222** [streetsidesoftware/vscode-spell-checker#2679]
Hi people, so many thanks for this good extension!

I just want to know if there is a possibility to merge the word list available in both the workspace and the folder settings, so we don't need to add the same words to both places due to overriding.

Currently I have a multi-root workspace with 2 projects. I want to add some word exceptions to one of them, but the other should not have those same exceptions. However, there are also some words that are shared, but as they are in the workspace, they get overridden once I add a word to the folder of the first project.

e.g. Having  projects for code and documentation, both in Spanish, I would like to write code without tildes or "ñ", so I add some word exceptions to the code project, I cannot add it to the workspace because those same words will be probably written wrongly in the documentation project if I do that.

I tried to look this repo in case someone has asked the same, but I couldn't find a thing.

PS: Probably this is a two part feature request, merge the word lists and also make sure that one folder word lists don't affect the other folder spelling checks after the merge.

**Comment by Jason3S** [comment]
@jota0222,

You have found one of the design limitations of VS Code settings. VS Code handles the "merging" of settings between User, Workspace, and Folder. See: [VSCode: Multi-root Workspace Settings](https://code.visualstudio.com/docs/editor/multi-root-workspaces#_settings). Extensions do not have any control of these.

You can work around this by adding a `cspell.json` or `cspell.yaml` file to the `.vscode` directory in the folder you want to override: `<project>/.vscode/cspell.yaml`.

**`.vscode/cspell.yaml`**
```yaml
words:
- first
- second
```
