### ISSUE TITLE
Problem with possessive camelCase words, e.g. "PyGMO's"

### ISSUE THREAD

**Issue by gandalfsaxe** [streetsidesoftware/vscode-spell-checker#268]
I have added these two words to the workspace dictionary:

```
PyGMO's
PyGMO
```

But still I get a spelling error on `PyGMO's` in the text. Specifically, it thinks I'm writing `Gmo's`:

<img width="342" alt="image" src="https://user-images.githubusercontent.com/12127864/45237368-c1e08200-b2de-11e8-8a62-62dc335e1fa0.png">

It doesn't seem like Code Spell Checker can handle this kind of word?

**Comment by Jason3S** [comment]
This is a known issue. It has to do with how the word splitter works. Words are only checked after they have been split, not before. An enhancement to the cSpell library would be to do the checking in two steps: 1. against the full word and then 2. agains the split words.

**Comment by GandalfSaxe** [comment]
Ok. Is there a workaround until then?

**Comment by Jason3S** [comment]
The easiest thing to do for now is just to add `GMO` to your word list.

**Comment by GandalfSaxe** [comment]
Alright 👍  But for the record, I had to add `GMO's` on the list.

**Comment by Jason3S** [comment]
Yes, that is right, the `'s` is considered part of the word.

**Comment by 8bhsolutions** [comment]
Add the following to your workspace setting

`"cSpell.ignoreRegExpList": ["'s\\b"]`

[Source - Issue 232](https://github.com/Jason-Rev/vscode-spell-checker/issues/232)

**Comment by Jason3S** [comment]
This should be fixed. The User dictionary will now accept PyGMO and PyGMO's.
