### ISSUE TITLE
After deleting npm-cache it doesnt work

### ISSUE THREAD

**Issue by ezerssss** [streetsidesoftware/vscode-spell-checker#2684]
Type: <b>Bug</b>

Delete npm-cache manually

Extension version: 2.20.5
VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx   (8 x 2096)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|17.94GB (9.92GB free)|
|Process Argv|--folder-uri file:///d%3A/unihub-web --crash-reporter-id e5a547e2-957e-4ce4-9f04-360dc5933027|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263cf:30773604
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyonecf:30548226
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
showindicator:30766890
pythongtdpath:30769146
bgfeh915:30769767
dh2dc718:30776458
pythonidxptcf:30772540
pythondjangots:30772535
pythonnocebcf:30776496

```

</details>

**Comment by Jason3S** [comment]
@ezerssss,

Thank you for reaching out.

By default, the extension does not depend upon the npm-cache.

Is it possible that you installed a language dictionary globally linked it?

What do you get if you run the following from the command line:

```
npx cspell trace "hello"
```

Kind regards.

**Comment by ezerssss** [comment]
Hi,

Thank you for helping out,

I also don't understand why it broke when I deleted the npm-cache folder, same thing happened with the prettify extension - they can't run anymore.

Reinstalling the extensions and restarting VSCode did the trick for me though! Just so weird.

I'm gonna close the issue now, thanks!
