### ISSUE TITLE
Environment Variables unsupported for custom dictionary path

### ISSUE THREAD

**Issue by Hi-Dr-Nick** [streetsidesoftware/vscode-spell-checker#2696]
Trying to configure a custom dictionary resident on OneDrive to easily synchronize across multiple devices / applications (Windows 10). This does not work:
`    "cSpell.dictionaryDefinitions": [ 
        {"name": "cloud_dictionary",
        "path": "${env:onedrivecommercial}\\Dev\\Config\\Office\\custom-dictionary-user.txt",
        "addWords": true}
    ],
`

This works fine:

`    "cSpell.dictionaryDefinitions": [ 
        {"name": "cloud_dictionary",
        "path": "D:\\Path_to_OneDrive_folder\\Dev\\Config\\Office\\custom-dictionary-user.txt",
        "addWords": true}
    ],
`
Have confirmed that %OneDriveCommercial% is available in Administrator and User contexts.

**Comment by Hi-Dr-Nick** [comment]
Should add that there is a work-around in the form of additional dictionary entries, each with a different name and absolute path, depending on the where OneDrive is installed on the system. Then modify the list of working dictionaries:

`"cSpell.customFolderDictionaries": [ "cloud_dictionary", "cloud_dictionary_laptop" ],
    "cSpell.customWorkspaceDictionaries": [ "cloud_dictionary", "cloud_dictionary_laptop" ],`

Not elegant, but functional. Will ultimately require three different entries to work across all systems I use and will still get errors if adding to one of the non-existent files. The secondary purpose is to also use this as a custom dictionary for Office applications, as you might have gathered from the path. 

This would be a moot point if Spell Checker had an option to discover and use the roaming dictionary in %AppData%. Turns out that's actually a pain to find and not sure it's in scope for this project.

**Comment by Jason3S** [comment]
@Hi-Dr-Nick,

Environment variable substitution is not currently supported, but it seems like a viable enhancement.

**Comment by Hi-Dr-Nick** [comment]
@Jason3S 

Thanks for the clarification. Would be a nice addition for people with complex build environments or shared dictionaries that sync via the cloud. 

Thanks for your efforts with this project!
