### ISSUE TITLE
Extension disabled when using WebDAV Workspaces for Visual Studio Code

### ISSUE THREAD

**Issue by blairun** [streetsidesoftware/vscode-spell-checker#2701]
Can this extension be enabled when using [WebDAV Workspaces for Visual Studio Code](https://github.com/kowd/vscode-webdav)?

Curranty vscode says "This extension has been disabled because it does not support virtual workspaces."

Other spelling extensions like [grammarly](https://github.com/znck/grammarly) do work in these WebDAV Workspaces.

**Comment by Jason3S** [comment]
@blairun,

Grammarly is able to work because it runs on a Grammarly server. This spell checker uses local resources to execute.

#2971 will support virtual workspaces.
