### ISSUE TITLE
Comments in custom dictionaries

### ISSUE THREAD

**Issue by lonix1** [streetsidesoftware/vscode-spell-checker#2707]
I defined a custom dictionary:
```json
"cSpell.customDictionaries": {
  "custom": { "name": "custom", "path": "${workspaceFolder}/.vscode/dictionary.txt", "addWords": true }
}
```

In that custom dictionary, I don't want to just dump a massive word list. I'd like to separate them with comments, e.g.
```txt
// programming
foo
bar
baz
qux

// company names
google
facebook
microsoft

// weird names
bob
mike
jim
```

What can I use for those comment lines? `//`, `#`, `;` or something else? Will those comment lines be ignored?

**Comment by Jason3S** [comment]
@lonix1,

A leading `#` is used as the comment character.
