### ISSUE TITLE
Request for support of the programing language lua

### ISSUE THREAD

**Issue by DeadlyKitten37** [streetsidesoftware/vscode-spell-checker#2716]
I noticed in testing and in the docs that lua language files ( .lua) are not supported. I request that lua please be supported so I can get the spell checking my code needs.
The lua keywords are 
and, break, do, else, elseif, end, false, for, function, if, in, local, nil, not, or, repeat, return, then, true, until, while
Of these only nil and elseif are not already words, and nil is only 3 letters. With only 1 additional item lua would (hopefully) be an easy language to support.

**Comment by Jason3S** [comment]
It is possible to turn on checking even if there isn't a custom dictionary.

`F1`->`Spell: Enable Spell Checking Document Language`

<img width="593" alt="image" src="https://github.com/streetsidesoftware/vscode-spell-checker/assets/3740137/f080cae7-7f28-4774-8ee2-7ec869f197d0">
