### ISSUE TITLE
VS crash when adding section

### ISSUE THREAD

**Issue by robertson-bauercontrols** [streetsidesoftware/vscode-spell-checker#2732]
When I'm editing the file, and want to add a new section for .txt files, I'm getting a VS crash

![image](https://github.com/streetsidesoftware/vscode-spell-checker/assets/55808281/fae378a2-bf5f-4657-9d3b-72fc3287f2a3)

![image](https://github.com/streetsidesoftware/vscode-spell-checker/assets/55808281/cd576fbf-9cd9-4390-b1eb-04754bd4d6f0)

v2023.5.15.1

**Comment by robertson-bauercontrols** [comment]
Form completeness sake, here's my current solution .editorconfig

`# editorconfig.org

# top-most EditorConfig file
root = true

# Default settings:
# A newline ending every file
# Use 4 spaces as indentation
[*]
insert_final_newline = true
indent_style = space
indent_size = 4
trim_trailing_whitespace = true

# VSSPELL: Spell checker settings from TestSuite.sln.vsspell
dotnet_style_operator_placement_when_wrapping = beginning_of_line
tab_width = 3
end_of_line = crlf
dotnet_style_coalesce_expression = true:suggestion
dotnet_style_null_propagation = true:suggestion
dotnet_style_prefer_is_null_check_over_reference_equality_method = true:suggestion
dotnet_style_prefer_auto_properties = true:suggestion
dotnet_style_object_initializer = true:suggestion
dotnet_style_collection_initializer = true:suggestion
dotnet_style_prefer_simplified_boolean_expressions = true:suggestion
vsspell_section_id = 8a725214157e41da8d6edd5e4472eaff
vsspell_spell_check_as_you_type = true
vsspell_include_in_project_spell_check = true
vsspell_code_analyzers_enabled = true
vsspell_detect_doubled_words = true
vsspell_ignore_words_with_digits = false
vsspell_ignore_words_in_all_uppercase = false
vsspell_ignore_words_in_mixed_case = false
vsspell_ignore_format_specifiers = true
vsspell_ignore_filenames_and_email_addresses = true
vsspell_ignore_xml_elements_in_text = true
vsspell_treat_underscore_as_separator = true
vsspell_ignore_mnemonics = false
vsspell_ignored_character_class = NonLatin
vsspell_code_analyzer_ignore_identifier_if_private = false
vsspell_code_analyzer_ignore_identifier_if_internal = false
vsspell_code_analyzer_ignore_identifier_if_all_uppercase = false
vsspell_code_analyzer_ignore_identifiers_within_member_bodies = false
vsspell_code_analyzer_ignore_type_parameters = false
vsspell_code_analyzer_ignore_if_compiler_generated = true
vsspell_code_analyzer_ignore_xml_doc_comments = false
vsspell_code_analyzer_ignore_delimited_comments = false
vsspell_code_analyzer_ignore_standard_single_line_comments = false
vsspell_code_analyzer_ignore_quadruple_slash_comments = false
vsspell_code_analyzer_ignore_normal_strings = false
vsspell_code_analyzer_ignore_verbatim_strings = false
vsspell_code_analyzer_ignore_interpolated_strings = false
vsspell_code_analyzer_ignore_raw_strings = false
vsspell_code_analyzer_apply_to_all_c_style_languages = true
vsspell_determine_resource_file_language_from_name = false
vsspell_additional_dictionary_folders_8a725214157e41da8d6edd5e4472eaff = clear_inherited|.\.spellcheck\custom_dictionaries
vsspell_dictionary_languages_8a725214157e41da8d6edd5e4472eaff = en-US
vsspell_ignored_words_8a725214157e41da8d6edd5e4472eaff = clear_inherited|File:.spellcheck\custom_dictionaries\solution_ignored_words.dic
vsspell_cad_treat_unrecognized_words_as_misspelled = true
vsspell_cad_treat_deprecated_terms_as_misspelled = true
vsspell_cad_treat_compound_terms_as_misspelled = true
vsspell_cad_treat_casing_exceptions_as_ignored_words = true

[project.json]
indent_size = 2

# Generated code
[*{_AssemblyInfo.cs,.notsupported.cs}]
generated_code = true

# C# files
[*.cs]
# New line preferences
csharp_new_line_before_open_brace = all
csharp_new_line_before_else = true
csharp_new_line_before_catch = true
csharp_new_line_before_finally = true
csharp_new_line_before_members_in_object_initializers = true
csharp_new_line_before_members_in_anonymous_types = true
csharp_new_line_between_query_expression_clauses = true

# Indentation preferences
csharp_indent_block_contents = true
csharp_indent_braces = false
csharp_indent_case_contents = true
csharp_indent_case_contents_when_block = true
csharp_indent_switch_labels = true
csharp_indent_labels = one_less_than_current

# Modifier preferences
csharp_preferred_modifier_order = public,private,protected,internal,static,extern,new,virtual,abstract,sealed,override,readonly,unsafe,volatile,async:suggestion

# avoid this. unless absolutely necessary
dotnet_style_qualification_for_field = false:suggestion
dotnet_style_qualification_for_property = false:suggestion
dotnet_style_qualification_for_method = false:suggestion
dotnet_style_qualification_for_event = false:suggestion

# Types: use keywords instead of BCL types, and permit var only when the type is clear
csharp_style_var_for_built_in_types =false:none
csharp_style_var_when_type_is_apparent = false:none
csharp_style_var_elsewhere =false:none
dotnet_style_predefined_type_for_locals_parameters_members = true:suggestion
dotnet_style_predefined_type_for_member_access = true:suggestion

# name all constant fields using PascalCase
dotnet_naming_rule.constant_fields_should_be_pascal_case.severity = suggestion
dotnet_naming_rule.constant_fields_should_be_pascal_case.symbols  = constant_fields
dotnet_naming_rule.constant_fields_should_be_pascal_case.style = pascal_case_style
dotnet_naming_symbols.constant_fields.applicable_kinds   = field
dotnet_naming_symbols.constant_fields.required_modifiers = const
dotnet_naming_style.pascal_case_style.capitalization = pascal_case

# static fields should have s_ prefix
dotnet_naming_rule.static_fields_should_have_prefix.severity = suggestion
dotnet_naming_rule.static_fields_should_have_prefix.symbols  = static_fields
dotnet_naming_rule.static_fields_should_have_prefix.style = static_prefix_style
dotnet_naming_symbols.static_fields.applicable_kinds   = field
dotnet_naming_symbols.static_fields.required_modifiers = static
dotnet_naming_symbols.static_fields.applicable_accessibilities = private, internal, private_protected
dotnet_naming_style.static_prefix_style.required_prefix = s_
dotnet_naming_style.static_prefix_style.capitalization = camel_case

# internal and private fields should be _camelCase
dotnet_naming_rule.camel_case_for_private_internal_fields.severity = suggestion
dotnet_naming_rule.camel_case_for_private_internal_fields.symbols  = private_internal_fields
dotnet_naming_rule.camel_case_for_private_internal_fields.style = camel_case_underscore_style
dotnet_naming_symbols.private_internal_fields.applicable_kinds = field
dotnet_naming_symbols.private_internal_fields.applicable_accessibilities = private, internal
dotnet_naming_style.camel_case_underscore_style.required_prefix = _
dotnet_naming_style.camel_case_underscore_style.capitalization = camel_case

# private methods should be camelCase
dotnet_naming_rule.private_method_should_be_camel_case.severity = suggestion
dotnet_naming_rule.private_method_should_be_camel_case.symbols = private_method
dotnet_naming_rule.private_method_should_be_camel_case.style = camel_case

# Code style defaults
csharp_using_directive_placement = outside_namespace:suggestion
dotnet_sort_system_directives_first = true
csharp_prefer_braces = true:silent
csharp_preserve_single_line_blocks = true:none
csharp_preserve_single_line_statements = false:none
csharp_prefer_static_local_function = true:suggestion
csharp_prefer_simple_using_statement = false:none
csharp_style_prefer_switch_expression = true:suggestion
dotnet_style_readonly_field = true:suggestion
csharp_style_implicit_object_creation_when_type_is_apparent = false:none

# Expression-level preferences
dotnet_style_object_initializer = true:suggestion
dotnet_style_collection_initializer = true:suggestion
dotnet_style_explicit_tuple_names = true:suggestion
dotnet_style_coalesce_expression = true:suggestion
dotnet_style_null_propagation = true:suggestion
dotnet_style_prefer_is_null_check_over_reference_equality_method = true:suggestion
dotnet_style_prefer_inferred_tuple_names = true:suggestion
dotnet_style_prefer_inferred_anonymous_type_member_names = true:suggestion
dotnet_style_prefer_auto_properties = true:suggestion
dotnet_style_prefer_conditional_expression_over_assignment = true:silent
dotnet_style_prefer_conditional_expression_over_return = true:silent
csharp_prefer_simple_default_expression = true:suggestion

# Expression-bodied members
csharp_style_expression_bodied_methods = true:silent
csharp_style_expression_bodied_constructors = true:silent
csharp_style_expression_bodied_operators = true:silent
csharp_style_expression_bodied_properties = true:silent
csharp_style_expression_bodied_indexers = true:silent
csharp_style_expression_bodied_accessors = true:silent
csharp_style_expression_bodied_lambdas = true:silent
csharp_style_expression_bodied_local_functions = true:silent

# Pattern matching
csharp_style_pattern_matching_over_is_with_cast_check = true:suggestion
csharp_style_pattern_matching_over_as_with_null_check = true:suggestion
csharp_style_inlined_variable_declaration = true:suggestion

# Null checking preferences
csharp_style_throw_expression = true:suggestion
csharp_style_conditional_delegate_call = true:suggestion

# Other features
csharp_style_prefer_index_operator = false:none
csharp_style_prefer_range_operator = false:none
csharp_style_pattern_local_over_anonymous_function = false:none

# Space preferences
csharp_space_after_cast = false
csharp_space_after_colon_in_inheritance_clause = true
csharp_space_after_comma = true
csharp_space_after_dot = false
csharp_space_after_keywords_in_control_flow_statements = true
csharp_space_after_semicolon_in_for_statement = true
csharp_space_around_binary_operators = before_and_after
csharp_space_around_declaration_statements = do_not_ignore
csharp_space_before_colon_in_inheritance_clause = true
csharp_space_before_comma = false
csharp_space_before_dot = false
csharp_space_before_open_square_brackets = false
csharp_space_before_semicolon_in_for_statement = false
csharp_space_between_empty_square_brackets = false
csharp_space_between_method_call_empty_parameter_list_parentheses = false
csharp_space_between_method_call_name_and_opening_parenthesis = false
csharp_space_between_method_call_parameter_list_parentheses = false
csharp_space_between_method_declaration_empty_parameter_list_parentheses = false
csharp_space_between_method_declaration_name_and_open_parenthesis = false
csharp_space_between_method_declaration_parameter_list_parentheses = false
csharp_space_between_parentheses = false
csharp_space_between_square_brackets = false

# License header
file_header_template = Copyright © Bauer Controls. All rights reserved.
csharp_style_namespace_declarations = block_scoped:silent
csharp_style_prefer_method_group_conversion = true:silent
csharp_style_prefer_top_level_statements = true:silent
vsspell_spell_check_as_you_type = true

# C++ Files
[*.{cpp,h,in}]
curly_bracket_next_line = true
indent_brace_style = Allman

# Xml project files
[*.{csproj,vbproj,vcxproj,vcxproj.filters,proj,nativeproj,locproj}]
indent_size = 2
vsspell_spell_check_as_you_type = false
vsspell_include_in_project_spell_check = false
vsspell_code_analyzers_enabled = false
vsspell_detect_doubled_words = false

[*.{csproj,vbproj,proj,nativeproj,locproj}]
charset = utf-8

# Xml build files
[*.builds]
indent_size = 2

# Xml files
[*.{xml,stylecop,resx,ruleset}]
indent_size = 2

# Xml config files
[*.{props,targets,config,nuspec}]
indent_size = 2
vsspell_spell_check_as_you_type = false
vsspell_include_in_project_spell_check = false
vsspell_code_analyzers_enabled = false

# YAML config files
[*.{yml,yaml}]
indent_size = 2

# Shell scripts
[*.sh]
end_of_line = lf
[*.{cmd,bat}]
end_of_line = crlf
`

**Comment by Jason3S** [comment]
@robertson-bauercontrols,

I believe this is a different extension: https://marketplace.visualstudio.com/items?itemName=EWoodruff.VisualStudioSpellCheckerVS2022andLater

**Comment by robertson-bauercontrols** [comment]
Lol sorry, i googled the wrong extension name before reporting :)
