### ISSUE TITLE
Doesn't add word to workspace settings

### ISSUE THREAD

**Issue by OnkelTem** [streetsidesoftware/vscode-spell-checker#2736]
The extension won't add words to the workspace settings file when I select  "Add: `<word>` to workspace settings" resolution.

![image](https://github.com/streetsidesoftware/vscode-spell-checker/assets/114060/ac75e59e-18e8-472f-ae07-460b2d409379)

I do have `.vscode/settings.json` file and it's writable, but words don't get there.

This sometimes works, sometimes doesn't, I see no regularity.

![image](https://github.com/streetsidesoftware/vscode-spell-checker/assets/114060/3dfdd3d5-268a-4bb8-8925-f78d9b3dfda6)

**Comment by Jason3S** [comment]
@OnkelTem,

You are experiencing a VS Code oddity. In a multi-root workspace, adding to "workspace" adds the words to the `*.code-workspace` file and not to the `.vscode/settings.json` files (these are considered "folder settings"). In addition, any `cSpell.words` in a `.vscode/settings.json` file will override the words found in the `.code-workspace` file.

I hope this helps.

**Comment by OnkelTem** [comment]
Oh, I see. Thank you @Jason3S 
You're right. I had only one folder opened, then I added another one for convenience and afterwards - removed it. I didn't save the workspace and restarted VSCode but it didn't help. Then I opened a new VSCode window, closed the previous one, and reopened this particular project as a folder. After that, it continued to work. Meh, haha
