### ISSUE TITLE
One line ignore

### ISSUE THREAD

**Issue by fgarcia** [streetsidesoftware/vscode-spell-checker#277]
I am using a lot the code comment markers to disable errors for rare words that should not be added to the dictionary. However I find the current comment markers a little bit verbose.

Other linters and type checkers have a one line "ignore next line" comment. I think this would help to cleanup spell-checker errors. Currently Typescript has ts-nocheck to disable checks for a whole file and ts-ignore for a single line.

Some suggestions:
```
// cspell:skip
// cspell:ignore-line
// cspell:ignore-next
// cspell:ignore
```

I like the most the last one. It might be confusing because it is already used to give a list of words, but it is the most intuitive one. Just the double meaning of "ignore next line" when no words are given.

**Comment by Jason3S** [comment]
Sorry for responding so late. This already exists:

```
// cspell:disable-line -- disables checking for the current line.
// cspell:disable-next-line -- disables checking till the end of the next line.
```

**Comment by fgarcia** [comment]
Great! So it is just a matter of a non documented feature. I've just submitted a pull request to mention those lines. 

Just one minor UX comment. I think it would nice if the shorter version could also disable next line if it is written in a line with no code around

**Comment by Jason3S** [comment]
Thank you for the pull request.
I tried to make it follow ESLint and TSLint.
