### ISSUE TITLE
How to disable the extension in the minimap?

### ISSUE THREAD

**Issue by camilossantos2809** [streetsidesoftware/vscode-spell-checker#2879]
Is there a way to disable the extension in the minimap?
It ends up interfering with the visibility of other error/warning/git indicators, etc.

**Comment by Jason3S** [comment]
The minimap is controlled by vscode and not the extension, but by changing the diagnostic level to `hint`, they will not show up. See #872.

<img width="985" alt="image" src="https://github.com/streetsidesoftware/vscode-spell-checker/assets/3740137/4e043095-5098-46d1-807f-063c21e70f32">

**Comment by camilossantos2809** [comment]
Great, that already solves it for me. Thank you.
