### ISSUE TITLE
CSpell configuration not being found

### ISSUE THREAD

**Issue by andrewvaughan** [streetsidesoftware/vscode-spell-checker#2880]
I have the following CSpell configuration (normally used with Megalinter):

```
.config/
    dictionaries/
        ops.txt
        project.txt
    linters/
        .cspell.json
```

This works great with MegaLinter, but the VS Code extension does not find my configuration, even if I explicitly set the path `.config/linters/.cspell.json` as an extension in the settings.

For example, I have `ops.txt` full of words, such as `andrewvaughan`, and I have `addWords` set to `true` for `project.txt`.

Neither of these function - the VSCode interface flags `andrewvaughan` as a mispelling, and any adding to dictionary creates a new `.cspell` folder with a new dictionary file.

These are the workspace settings I have that differ from the defaults:

```json
  "cSpell.enabled": true,
  "cSpell.caseSensitive": true,
  "cSpell.language": "en,en-US",
  "cSpell.autoFormatConfigFile": false,
  "cSpell.diagnosticLevel": "Information",
  "cSpell.showAutocompleteSuggestions": true,
  "cSpell.checkOnlyEnabledFileTypes": true,
```

And this is my `.cspell.json` file (although it seems like it isn't being found, at all):

```json
{
  "dictionaries": ["ops", "project"],
  "dictionaryDefinitions": [
    {
      "name": "ops",
      "path": "../dictionaries/ops.txt",
      "addWords": false
    },
    {
      "name": "project",
      "path": "../dictionaries/project.txt",
      "addWords": true
    }
  ],
  "ignorePaths": [
    "**/.config/linters/**",
    "**/.git/**",
    "**/.gitattributes",
    "**/.gitignore",
    "**/.pnpm-lock.json",
    "**/*megalinter*",
    "**/node_modules/**",
    "**/vscode-extension/**",
    "**/docs/assets/**",
    "package-lock.json"
  ],
  "language": "en",
  "noConfigSearch": true,
  "version": "0.2"
}
```

It seems to me that the extension either (a) doesn't support dictionaries with relative paths to the found `.cspell.json` file or (b) the `.cspell.json` file isn't being found at all.

**Comment by andrewvaughan** [comment]
I tested item (a) further, setting my dictionary path to the project root (`.config/dictionaries/ops.txt`) but no joy.

**Comment by Jason3S** [comment]
@andrewvaughan,

I think the issue is that it is not finding the `.cspell.json` file.

<img width="975" alt="image" src="https://github.com/streetsidesoftware/vscode-spell-checker/assets/3740137/4f587ce8-84af-4913-9d46-3880fe8146df">

```jsonc
"cSpell.import": ["${workspaceFolder}/.config/linters/.cspell.json"]
```

**Comment by andrewvaughan** [comment]
Well, I take that back - I copied your exact line into my `settings.json` and it worked. I may have had a mistake in the way I wrote it.

I'll leave this issue open, as I believe the file should have been found, by default. My best guess is however the code is traversing the directory, it isn't properly including dot-folders.

**Comment by Jason3S** [comment]
@andrewvaughan,

I'm happy it worked.

The code scanning for configuration only scans up the directory tree, never down. There are a few explicit subdirectories that it will look in like `.vscode` and `.config`, but only at a single level.

This is by design. The idea is that each configuration file applies to the files deeper in the directory tree, like `.gitignore`. This allows for customization deeper in the hierarchy.

If you had a `.config/.cspell.json` like this:

```
.config/
    .cspell.json - { "import": ["./linters/.cspell.json"] }
    dictionaries/
        ops.txt
        project.txt
    linters/
        .cspell.json
```

It would have worked just fine.

**Comment by andrewvaughan** [comment]
Oh I see - thank you. I believe there may be opportunity to make that more clear in the documentation. At least my smooth-brain read it as "going deeper into your project" which, now that I think of it, makes no sense.

Given the other change worked for me, I won't be creating two config files for this (eek), and will use the built-in workspace configurations for VSCode. Thank you for taking the time to provide an alternative, though!
