### ISSUE TITLE
Where does this repository get `Makefile` support from?

### ISSUE THREAD

**Issue by andrewvaughan** [streetsidesoftware/vscode-spell-checker#2883]
I'm trying to get CSpell Makefile support. I've seen it listed in the UI for this extension, but for the life of me I can't find where the dictionary might be that I can include in my project.

I've seen Makefile listed as a languageId (which I don't fully understand the difference between that and Dictionaries). Right now CSpell is throwing every error under the sun for every make function and variable at me. Thanks!

**Comment by Jason3S** [comment]
@andrewvaughan,

Thank you for posting in `cspell-dicts`. I'm going to close this. Once the dictionary is created, the experience will be automatically improved.

Kind regards

**Comment by Jason3S** [comment]
@andrewvaughan,

Are you referring to this screen?:
<img width="720" alt="image" src="https://github.com/streetsidesoftware/vscode-spell-checker/assets/3740137/9c7b7cf1-039b-470d-ae12-b124b2eaeb34">

It is just a list of all known (to VS Code) file types to make it easier to enable spell checking.

The spell checker doesn't check file types it doesn't know about. One of the most common complaints is that it is difficult to discover how to turn on spell checking for a file type.

Enabling a file type doesn't imply that it is supported, it just tell the spell checker to try a spell check the file. It will do its best.

It doesn't take much effort to add your own dictionaries.

**Comment by andrewvaughan** [comment]
> Enabling a file type doesn't imply that it is supported, it just tell the spell checker to try a spell check the file. It will do its best.

Ok thanks for the clarification - I find that to be _super_ confusing the way it's implemented. Maybe an opportunity for explanation in the UI. I hope that feedback comes across as constructive.
