### ISSUE TITLE
Startup performance slowed down.

### ISSUE THREAD

**Issue by sbimochan** [streetsidesoftware/vscode-spell-checker#290]
Can we have a feature that will enable this plugin after a while. Around 15sec or something because this plugin is not very critical while initiating any codes. This plugin scores around 100 in duration of VScode startup performance.

**Comment by amad** [comment]
The plugin scans all the files at startup. Why is it even necessary to do it?
Perhaps the best is to add a config option to disable full scan. It breaks VSCode on a very large project.

Just scan open editor tabs is what you need most of the times. It should be optional to run a full scan.

**Comment by Jason3S** [comment]
This was nearly impossible for me to track down because it didn't happen to me. Finally someone included a startup profile in a bug report. It was an issue on how VS Code loads extensions. All the file scanning you were seeing was VS Code looking for node modules. I have no idea why the performance was so bad, but this has been fixed by bundling the extension into a single file.

**Comment by sbimochan** [comment]
How is this done or fixed? Which PR fixed it?

**Comment by Jason3S** [comment]
The core problem was how VS Code loads node_modules in an extension. If everything loads fast enough, there isn't a problem. But if it takes too long, then the module loader seems to go into a loop. The solution for this was to WebPack the extension. This is the solution give on VS Code's how to speed up extension loading time. Sadly, the Wiki page is now gone. In any case, this is the commit that enabled the extension to be WebPacked. 
https://github.com/streetsidesoftware/vscode-spell-checker/commit/f7c2ed88dd06492a50bd283c0531b8903f917971  
Note the server is not packed, just the extension. Startup time for the extension on my machine is 20ms. Are you still seeing an issue?
