### ISSUE TITLE
In 3.0, html words do not work in html file and svelte

### ISSUE THREAD

**Issue by lukaszpolowczyk** [streetsidesoftware/vscode-spell-checker#2902]
E.g. the word `rel`:
![obraz](https://github.com/streetsidesoftware/vscode-spell-checker/assets/16800535/48510917-0906-498a-8432-907280da8964)

In 2.20.05, there is no such problem.

( you can also see the lack of support for simple English words, but that's another matter)

**Comment by Jason3S** [comment]
@lukaszpolowczyk,

It looks like something else is going one, as if the dictionaries have been turned off or were unable to load.

**Comment by Jason3S** [comment]
@lukaszpolowczyk,

Were you able to get it to work?

**Comment by lukaszpolowczyk** [comment]
@Jason3S No.

**Comment by Jason3S** [comment]
@lukaszpolowczyk,

This is most likely a configuration issue.

Can you share your `.vscode/settings.json` sections containing `cSpell.` or any `cspell.*` config files you are using?

**Comment by lukaszpolowczyk** [comment]
@Jason3S Sorry, it has already started working.

(I checked the settings earlier and it didn't change anything)
