### ISSUE TITLE
Missing basic words

### ISSUE THREAD

**Issue by RDKRACZ** [streetsidesoftware/vscode-spell-checker#2907]
It's missing basic words:
-Playing
-Entries
-actively
-currently
-your ... yes YOUR

and other, like brand names:
-Emby
-Jellyfin

**Comment by Jason3S** [comment]
@RDKRACZ,

There must be something else going on. All of those words are in the dictionaries.

Likely causes are:
- `language` has been set to something besides `en` (English): `Settings`-> search: `spell language`
- A custom dictionary of the same name as the English dictionary has been used.
- A possible bad install and it isn't possible to load the dictionaries.

More information is needed to help fix the issue.
