### ISSUE TITLE
High CPU usage with code-spell-checker-3.0.1

### ISSUE THREAD

**Issue by ticklemycode** [streetsidesoftware/vscode-spell-checker#2935]
code-spell-checker-3.0.1

<img width="1834" alt="image" src="https://github.com/streetsidesoftware/vscode-spell-checker/assets/32107888/9fa44c39-caac-415f-905e-125e6f212ff9">

When I grep the process that using an incredible amount of CPU usage it's showing 

`ps aux | grep 1571`

**Output:**
```
1:55PM   3:41.44 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --type=utility --utility-sub-type=node.mojom.NodeService --lang=en-US --service-sandbox-type=none --dns-result-order=ipv4first --inspect-port=0 --user-data-dir=/Users/user/Library/Application Support/Code --standard-schemes=vscode-webview,vscode-file --enable-sandbox --secure-schemes=vscode-webview,vscode-file --bypasscsp-schemes --cors-schemes=vscode-webview,vscode-file --fetch-schemes=vscode-webview,vscode-file --service-worker-schemes=vscode-webview --streaming-schemes --shared-files --field-trial-handle=1718379636,r,7642377889115433824,15875252669824537023,262144 --disable-features=CalculateNativeWinOcclusion,SpareRendererForSitePerProcess
user           2642   1.0  0.0 408645328   1616 s000  S+    2:01PM   0:00.01 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn --exclude-dir=.idea --exclude-dir=.tox 1571
user           1601   0.1  0.2 1585120080  38528   ??  S     1:55PM   0:05.33 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /Users/user/.vscode/extensions/streetsidesoftware.code-spell-checker-3.0.1/packages/_server/dist/main.cjs --node-ipc --clientProcessId=1571
user           1598   0.0  0.2 1585078960  34816   ??  S     1:55PM   0:48.64 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /Users/user/.vscode/extensions/dbaeumer.vscode-eslint-2.4.2/server/out/eslintServer.js --node-ipc --clientProcessId=1571
```

**Comment by Jason3S** [comment]
@ticklemycode,

Why do you think it is the spell checker? The `ps aux` output says the CPU usage for the spell checker is only 0.1% of the CPU.

```
USER            PID  %CPU %MEM        VSZ    RSS   TT  STAT STARTED      TIME COMMAND
user           1601   0.1  0.2 1585120080  38528   ??  S     1:55PM   0:05.33 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /Users/user/.vscode/extensions/streetsidesoftware.code-spell-checker-3.0.1/packages/_server/dist/main.cjs --node-ipc --clientProcessId=1571
user           1598   0.0  0.2 1585078960  34816   ??  S     1:55PM   0:48.64 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /Users/user/.vscode/extensions/dbaeumer.vscode-eslint-2.4.2/server/out/eslintServer.js --node-ipc --clientProcessId=1571
```

It is the VSCode host process that seems to be going crazy.

Even so, did you just recently "update" vscode? Sometimes vscode does not properly shutdown all the processes during an update. When this happens, one or two processes hang around using a lot of CPU. Even after quitting vscode, the process might still be there and will need to be manually killed.

**Comment by levihoang** [comment]
Hi,
I have tried disable Code Spell Check, my Vscode CPU is so lower.
This extension is useful, but It makes my mac is high CPU.
After disabling this extension, my Macbook's temperature is about 60-70 °C.
But when I enable this extension, my Macbook's temperature is about 80-90 °C.

**Comment by Jason3S** [comment]
@levihoang,

I would be helpful to get more information.

> did you just recently "update" vscode? Sometimes vscode does not properly shutdown all the processes during an update. When this happens, one or two processes hang around using a lot of CPU. Even after quitting vscode, the process might still be there and will need to be manually killed.

If there are no orphaned processes running, it is possibly a regular expression causing the issue. Would you be able to share your configuration?

**Comment by levihoang** [comment]
I'm sorry about that. I realized the main cause was the Sync Setting extension instead of Code Spell Checker.
