### ISSUE TITLE
keyboard shortcut for next (and previous) misspelled word

### ISSUE THREAD

**Issue by pang-thebasement** [streetsidesoftware/vscode-spell-checker#2943]
In nvim's bultin spell checking, there are commands `[s` and `]s` for navigating mispelled words.
Regards

**Comment by Jason3S** [comment]
@pang-thebasement,

Are you referring to the VSCode Spell Checker? It is possible to assign keyboard shortcuts to previous and next spelling issues.

Bring up the keyboard shortcuts and search for `spell go to`:

<img width="639" alt="image" src="https://github.com/streetsidesoftware/vscode-spell-checker/assets/3740137/98caa2f9-25b5-433c-a4a7-559ac03f990c">

**Comment by pang-thebasement** [comment]
Thanks, and sorry, because I had another window open, and this was not were I wanted to post :$
