### ISSUE TITLE
Use Rename when fixing spelling issues.

### ISSUE THREAD

**Issue by geverges-oleg** [streetsidesoftware/vscode-spell-checker#295]
I can't use this plugin for e.g. TypeScript code, since it merely replaces the text in the file - as opposed to e.g. invoking a rename refactoring.

I don't know if there's a general API to trigger renaming a symbol in VS code, or if the API for each language is completely internal/proprietary to each language module?

**Comment by Jason3S** [comment]
I have to investigate a bit to see how to do this.

**Comment by Jason3S** [comment]
With the release of 1.7.7, I have added the option to tell the spell checker to use the rename provider.

It is still a bit experimental, so it is not on by default.

![image](https://user-images.githubusercontent.com/3740137/57189852-d4fe2d00-6f13-11e9-8917-5e8f150ab674.png)

@geverges-oleg and @alexrussell please try it out and let me know how well it works.
