### ISSUE TITLE
Feedback on VS Code proposed Code Action Auto Fix APIs

### ISSUE THREAD

**Issue by mjbvz** [streetsidesoftware/vscode-spell-checker#297]
Hi, I'm on the VS Code team. We are exploring extending VS Code's code actions to support automatic fixes and auto fix on save. You can find the two current proposal [here](https://github.com/Microsoft/vscode/issues/62110#issuecomment-454182230)

Your extension is a large user of code actions so we'd appreciate your feedback on these API proposals. The automatic fixes are probably of more interest for this extension rather than auto fix on save. A quick example use case of auto fix:

A text document contains the string `mispell` that is marked as a spelling error. The user F8's to the spelling error and then uses a single keyboard shortcut to auto fix `mispell` to `misspell`. This auto fix is suggested since it is the closest spelling match. The user can F8 through the entire document quickly applying autofixes or using the existing code actions menu if they want more control over the  fix.

[This guide](https://code.visualstudio.com/api/advanced-topics/using-proposed-api) covers how to use VS Code's proposed APIs. Please let me know if you have any questions about these proposals, feedback on the API, or ideas for other auto-fix scenarios that you would like to see supported in VS Code

**Comment by Jason3S** [comment]
Awesome!

**Comment by GammaGames** [comment]
Right now it's a little tedious to fix typos but it would be such a nice QoL improvement if this awesome feature were implemented.

**Comment by Jason3S** [comment]
@mjbvz 
I was able to get it working, but I am waiting on [Add isPreferred to the CodeAction protocol. Pull Request #489 · Microsoft/vscode-languageserver-node](https://github.com/Microsoft/vscode-languageserver-node/pull/489)
