### ISSUE TITLE
Dart/Flutter support

### ISSUE THREAD

**Issue by PhilParisot** [streetsidesoftware/vscode-spell-checker#298]
Support for Dart would be awesome!

Thanks.

**Comment by danwulff** [comment]
As a side note, I manually enabled checking .dart files following the instructions here and it's been working just fine: https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker

**Comment by WilkoV** [comment]
Dart and flutter would be great.

**Comment by Jason3S** [comment]
Fixed with #1762
