### ISSUE TITLE
[Bug] wth is seen as a valid word

### ISSUE THREAD

**Issue by DominicGBauer** [streetsidesoftware/vscode-spell-checker#2988]
I'm not sure if this is meant to be valid behaviour but `wth` is seen as a valid word e.g.

![image](https://github.com/streetsidesoftware/vscode-spell-checker/assets/46312751/249f4e2b-694e-4123-bd76-cda6dc01f5f3)

I don't think `wth` should be a valid word.

**Comment by Jason3S** [comment]
@DominicGBauer,

By default, the minimum word length is 4. If you change it to 3, it should pick it up.

<img width="793" alt="image" src="https://github.com/streetsidesoftware/vscode-spell-checker/assets/3740137/4b9cdfb5-e68a-4785-97b9-440d2cfdb15a">

**Comment by DominicGBauer** [comment]
Ah I missed that, thanks a lot @Jason3S!
