### ISSUE TITLE
Native extension setting "C Spell: Enable/disable" not working at all

### ISSUE THREAD

**Issue by carafelix** [streetsidesoftware/vscode-spell-checker#3007]
In the vscode native settings: @ext:streetsidesoftware.code-spell-checker, the checkmark for disabling Code Spell does not have any impact on the extension being enabled or not
![image](https://github.com/streetsidesoftware/vscode-spell-checker/assets/48109042/74d35637-79da-42c5-a464-3fb78a4fa792)

Steps to reproduce: 
- Open a file with spell errors
- Go to extension settings
- Mark / Unmark the "C spell: Enable" checkmark
- File problem's display spell errors in any case

**Comment by Jason3S** [comment]
@carafelix,

How VSCode works with settings can be confusing, non-intuitive, and a bit buggy.

VSCode calculates the value and passes it to the extension. You might be seeing two things:

1. User settings are NOT stronger than workspace settings. Strongest to Weakest: Folder, Workspace, and then User. Meaning, Folder settings will win against Workspace settings and Workspace settings will win against User.
2. There is a bug in VSCode, that does not update a setting if it has been set for the first time. It is necessary to restart VSCode for it to take place.

**Comment by Jason3S** [comment]
@carafelix,

Please try changing the `Workspace` setting and see if that works.

**Comment by carafelix** [comment]
Changing it from the `Workspace` tab works. Also opening a new workspace with the `User` setting changed also works
