### ISSUE TITLE
Task: Add `Spell:Enable Spell Checking Document Type` command

### ISSUE THREAD

**Issue by Jason3S** [streetsidesoftware/vscode-spell-checker#3060]
The current `Spell:Enable Spell Checking Document Language` command name is misleading.

See: [#3059](https://github.com/streetsidesoftware/vscode-spell-checker/issues/3059)

`Spell:Enable Spell Checking Document Language` should be a legacy alias of `Spell:Enable Spell Checking Document Type`

**Comment by memeplex** [comment]
We already have:
- LanguageId
- Filetype
- Language
- Locale (although not exposed to VSCode)

Document Type would add yet another name. Why not `Spell:Enable Spell Checking Filetype`?

**Comment by Jason3S** [comment]
> We already have:
> 
> * LanguageId
> * Filetype
> * Language
> * Locale (although not exposed to VSCode)
> 
> Document Type would add yet another name. Why not `Spell:Enable Spell Checking Filetype`?

You make a good point. I added `Spell: Enable Spell Checking File Type` instead of `Document Type`.

<img width="614" alt="image" src="https://github.com/streetsidesoftware/vscode-spell-checker/assets/3740137/2f99a580-bc61-4df2-960b-628ffeef5627">

**Comment by Jason3S** [comment]
Fixed with #3078

**Comment by memeplex** [comment]
Thanks!
