### ISSUE TITLE
integration with Theia

### ISSUE THREAD

**Issue by rhildred** [streetsidesoftware/vscode-spell-checker#307]
I have been using the spellchecker in VSCode with students. A lot of the mistakes that they make are case inconsistencies so it really helps. I need to use Theia with some of my students because of their lab environment. Has anyone tried to make vscode-spell-checker a Theia extension?

**Comment by Jason3S** [comment]
I hadn't heard of Theia. I have no idea if it works.

**Comment by a1994846931931** [comment]
@rhildred Theia is compatible with VSCode's extension. I've tested it on theia, and it works well.

**Comment by Jason3S** [comment]
Closing as stale.
