### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by jaydeepkarena** [streetsidesoftware/vscode-spell-checker#309]
- Issue Type: `Performance`
- Extension Name: `code-spell-checker`
- Extension Version: `1.6.10`
- OS Version: `Windows_NT x64 10.0.14393`
- VSCode version: `1.32.1`

:warning: Make sure to **attach** this file from your *home*-directory: `C:\Users\Jaydeep\streetsidesoftware.code-spell-checker-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by AlekSi** [comment]
Dupe of #303?

**Comment by Jason3S** [comment]
@jaydeepkarena would you please attach the file?
