### ISSUE TITLE
git worktree support for .gitignore

### ISSUE THREAD

**Issue by stevenliuakuna** [streetsidesoftware/vscode-spell-checker#3099]
I have been using git worktrees with the following setup:

```
- outer_repository
  - .git (folder)
  - .gitignore
  - inner_repository 
  - worktrees
     - branch_1
        - inner_repository
           - .git (worktree pointer)
           - spellchecker_target
```
The outer_repository .gitignore contains /worktrees, which matches the spellchecker_target; however the spellchecker_target is _not_ gitignored in inner_repository. However, vscode-spell-checker fails to check the file: `File is exclude by .gitignore.`

This works fine when I use a regular, non-worktree clone of the repository. But I would like to use worktree since my .git folder is rather huge.

**Comment by acenturyandabit** [comment]
Looks like this repository uses [cspell-gitignore](https://github.com/streetsidesoftware/cspell/tree/main/packages/cspell-gitignore#readme) to determine whether a file is gitignored. This package doesn't seem to stop when a `.git` file or directory is found, which is causing the issue.

Perhaps a better question is: why does _gitignore_ determine whether or not we spellcheck files? Why not just spellcheck every file regardless of .gitignore?

**Comment by acenturyandabit** [comment]
In fact there is a setting called `useGitignore` that you can turn off, which will fix your problem.

**Comment by stevenliuakuna** [comment]
Fair, thanks!
