### ISSUE TITLE
Part of word marked as misspelled

### ISSUE THREAD

**Issue by vkbo** [streetsidesoftware/vscode-spell-checker#3103]
I ran into an issue with the city name "Dusseldorf" today, where cSpell suggested it should be spelled "Düsseldorf", however after correcting it, it claimed "sseldorf" is misspelled instead.

Tested on both Windows and Linux.

![image](https://github.com/streetsidesoftware/vscode-spell-checker/assets/1619840/20ec44a2-098d-4ef3-a569-6c0ea3775b58)

I'm guessing there is some word splitting using regex `\w` without unicode support?

**Comment by Jason3S** [comment]
@vkbo,

I tried it out on a `README.md` file. This is what I got:

<img width="172" alt="image" src="https://github.com/streetsidesoftware/vscode-spell-checker/assets/3740137/2d1c7b7a-14dc-4821-945e-fa483d123b38">

It is most likely a configuration issue related to `ignoreRegExpList` or `excludeRegExpList` settings.

<img width="994" alt="image" src="https://github.com/streetsidesoftware/vscode-spell-checker/assets/3740137/f4054db9-ed94-453d-ae9e-bba7d10c296d">

**Comment by vkbo** [comment]
> It is most likely a configuration issue related to `ignoreRegExpList` or `excludeRegExpList` settings.

You're right, it seems to have been the case. Clearing those solved it. I had some regexes there to bypass some bugs in cSpell from earlier (the apostrophe issue).
