### ISSUE TITLE
Ignore paths not working?

### ISSUE THREAD

**Issue by Gruntfuggly** [streetsidesoftware/vscode-spell-checker#311]
I have the following settings:
```
    "cSpell.ignorePaths": [
        "**/package-lock.json",
        "**/node_modules/**",
        "**/vscode-extension/**",
        "**/.git/**",
        ".vscode",
        "typings",
        "/opt/qt4-asl/4.7.4/x64/include/**/",
        "/opt/qt4-asl/4.7.4/x64/include/QtCore/*.h"
    ],
```
However I'm still getting results from file that should be ignored:
![image](https://user-images.githubusercontent.com/376658/54427664-09731b00-4713-11e9-8ded-a79493a1ddcb.png)
![image](https://user-images.githubusercontent.com/376658/54427686-18f26400-4713-11e9-9982-c4c8dff9e5cd.png)

**Comment by JeffryBooher** [comment]
This setting (and supported languages `enabledLanguageIds`) seem to only get parsed from `.vscode/settings.json`; I tried adding these settings to `cSpell.json ` to no avail.  "words" and "flagWords" work from `cSpell.json`, however...
