### ISSUE TITLE
Code Spell Checker covers not the whole file

### ISSUE THREAD

**Issue by SteffenWeishaar** [streetsidesoftware/vscode-spell-checker#3110]
Hi all,
I have a very big files because of generated Code.
11000 lines of code.
Under "Problems" CodeSpellChecker detects 734 findings.
The file is covered there until the end and also the last line od code was checked.
BUT:
The blue markings in the status bar and also the markings in the Code itself under the words cover only ~30% of the file.
Unfortunately I did not found a setting to get rid of that problem.

Dou you have an idea?

Many Thanks in advance!!!!

**Comment by Jason3S** [comment]
@SteffenWeishaar,

This is an issue with VSCode Problems view. It will only show a limited number of decorations.

The new version, currently in testing, might be able to address the issue.

Please feel free to try it out and give feedback: [Releases · streetsidesoftware/vscode-spell-checker](https://github.com/streetsidesoftware/vscode-spell-checker/releases)

It no longer uses the Problems Pane to display issues.

**Comment by SteffenWeishaar** [comment]
Hi guys,
The new version is working perfect. Problem is solved. Many thanks.

But I have now another problem:
I split the windows in VSC and I have 5 groups / windows with different sources and header in it.
Spell-checker is now not analyzing all the files in the certain groups.
I have the feeling that the problem has to do with the split windows…

Best regards

Steffen Weishaar

Von: Jason Dent ***@***.***>
Gesendet: Montag, 25. März 2024 10:08
An: streetsidesoftware/vscode-spell-checker ***@***.***>
Cc: Weishaar, Steffen (RDS3_E-RI) ***@***.***>; Mention ***@***.***>
Betreff: [EXTERNAL] Re: [streetsidesoftware/vscode-spell-checker] Code Spell Checker covers not the whole file (Issue #3110)


[EXTERNAL E-MAIL]: DO NOT CLICK links or attachments unless you recognize the sender and know the content is safe.

@SteffenWeishaar<https://smex-ctp.trendmicro.com:443/wis/clicktime/v1/query?url=https%3a%2f%2fgithub.com%2fSteffenWeishaar&umid=d2ddfc71-d639-42ab-b9e2-ea86eadb8332&auth=ba0b17140c3fe009bb979bc49036fd06c41ea2b1-966a965f9d8e5028024c3ae173e872e89c289332>,

This is an issue with VSCode Problems view. It will only show a limited number of decorations.

The new version, currently in testing, might be able to address the issue.

Please feel free to try it out and give feedback: Releases · streetsidesoftware/vscode-spell-checker<https://smex-ctp.trendmicro.com:443/wis/clicktime/v1/query?url=https%3a%2f%2fgithub.com%2fstreetsidesoftware%2fvscode%2dspell%2dchecker%2freleases&umid=d2ddfc71-d639-42ab-b9e2-ea86eadb8332&auth=ba0b17140c3fe009bb979bc49036fd06c41ea2b1-3635726869cd917d5f8d72948e599491877ca7b1>

It no longer uses the Problems Pane to display issues.

**Comment by Jason3S** [comment]
> But I have now another problem: I split the windows in VSC and I have 5 groups / windows with different sources and header in it. Spell-checker is now not analyzing all the files in the certain groups. I have the feeling that the problem has to do with the split windows… 

@SteffenWeishaar,

Can you give some more detail? Maybe even a screenshot or gif recording of your screen?

Are you having the same document open in multiple windows and only some of the windows are updating?

**Comment by SteffenWeishaar** [comment]
Hi,
I cannot provide a screenshot etc because the content is confidential.
I split the windows in VCS. Means I have 4 windows/groups and I can so easily switch between the modules.
In every window I have one or 2 source-files (*.c) and the corresponding headers opened (*.h) .
Some of the files are checked, some not. Up to now I didn’t find a “rule” which files are checked and which not.

Best regards

Steffen Weishaar


Von: Jason Dent ***@***.***>
Gesendet: Mittwoch, 27. März 2024 12:06
An: streetsidesoftware/vscode-spell-checker ***@***.***>
Cc: Weishaar, Steffen (RDS3_E-RI) ***@***.***>; Mention ***@***.***>
Betreff: [EXTERNAL] Re: [streetsidesoftware/vscode-spell-checker] Code Spell Checker covers not the whole file (Issue #3110)


[EXTERNAL E-MAIL]: DO NOT CLICK links or attachments unless you recognize the sender and know the content is safe.

But I have now another problem: I split the windows in VSC and I have 5 groups / windows with different sources and header in it. Spell-checker is now not analyzing all the files in the certain groups. I have the feeling that the problem has to do with the split windows…

@SteffenWeishaar<https://smex-ctp.trendmicro.com:443/wis/clicktime/v1/query?url=https%3a%2f%2fgithub.com%2fSteffenWeishaar&umid=fe129571-42a5-40f8-afb0-ff905d04eda8&auth=f20d17e50f87929f669ee7c71dccac2ef3341d58-b8214d408838110cafc04f50ecf531fe9d3cc861>,

Can you give some more detail? Maybe even a screenshot or gif recording of your screen?

Are you having the same document open in multiple windows and only some of the windows are updating?

**Comment by SteffenWeishaar** [comment]
Hi all,
Update:
I rechecked that point in the moment.
Now everything looks fine, every file is checked.
I don’t know the difference or since when it is working.
But you can close that ticket.
Many thanks!!!!!!

Best regards

Steffen Weishaar

Von: Weishaar, Steffen (RDS3_E-RI)
Gesendet: Mittwoch, 27. März 2024 15:25
An: streetsidesoftware/vscode-spell-checker ***@***.***>
Betreff: AW: [EXTERNAL] Re: [streetsidesoftware/vscode-spell-checker] Code Spell Checker covers not the whole file (Issue #3110)

Hi,
I cannot provide a screenshot etc because the content is confidential.
I split the windows in VCS. Means I have 4 windows/groups and I can so easily switch between the modules.
In every window I have one or 2 source-files (*.c) and the corresponding headers opened (*.h) .
Some of the files are checked, some not. Up to now I didn’t find a “rule” which files are checked and which not.

Best regards

Steffen Weishaar


Von: Jason Dent ***@***.******@***.***>>
Gesendet: Mittwoch, 27. März 2024 12:06
An: streetsidesoftware/vscode-spell-checker ***@***.******@***.***>>
Cc: Weishaar, Steffen (RDS3_E-RI) ***@***.******@***.***>>; Mention ***@***.******@***.***>>
Betreff: [EXTERNAL] Re: [streetsidesoftware/vscode-spell-checker] Code Spell Checker covers not the whole file (Issue #3110)


[EXTERNAL E-MAIL]: DO NOT CLICK links or attachments unless you recognize the sender and know the content is safe.

But I have now another problem: I split the windows in VSC and I have 5 groups / windows with different sources and header in it. Spell-checker is now not analyzing all the files in the certain groups. I have the feeling that the problem has to do with the split windows…

@SteffenWeishaar<https://smex-ctp.trendmicro.com:443/wis/clicktime/v1/query?url=https%3a%2f%2fgithub.com%2fSteffenWeishaar&umid=fe129571-42a5-40f8-afb0-ff905d04eda8&auth=f20d17e50f87929f669ee7c71dccac2ef3341d58-b8214d408838110cafc04f50ecf531fe9d3cc861>,

Can you give some more detail? Maybe even a screenshot or gif recording of your screen?

Are you having the same document open in multiple windows and only some of the windows are updating?

**Comment by Jason3S** [comment]
@SteffenWeishaar,

Thank you for the update. I'll close it. If you see it again, please open a new issue and refer to this one.
