### ISSUE TITLE
Can you also support spell checking for directories and files in object explorer? Or expose a CLI for that purpose?

### ISSUE THREAD

**Issue by Nefcanto** [streetsidesoftware/vscode-spell-checker#3111]
This is a real image of our source code:

![Screenshot from 2024-03-16 08-40-05](https://github.com/streetsidesoftware/vscode-spell-checker/assets/12782347/f7727fb2-0a96-4d97-8f44-ebfb123b7436)

As you can see the `Recipies` directory is misspelled.

Can you also extend your support to check directory and file names?
Another option is to expose a CLI. That way we can use your `CLI` to check it ourselves. Something like:

```
user@local:/$ spell-check text-here
```

**Comment by Jason3S** [comment]
@Nefcanto,

It is not possible for extension to decorate VS Code's explorer.

This spell checker is based upon [cspell](https://www.npmjs.com/package/cspell) cli. You can use it as part of your CI/CD process. This extension will read cspell configuration files.

The cspell cli does not spell check directory names, but with a bit of creativity, you can use `ls` to echo the directory names to the spell checker.

```sh
ls -1 | cspell stdin
```

**Comment by Nefcanto** [comment]
@Jason3S, thank you. I'll check it.
