### ISSUE TITLE
How to not spell check certain files?

### ISSUE THREAD

**Issue by A7medMajed16** [streetsidesoftware/vscode-spell-checker#3146]
Spell Checker in VsCode scan unnecessary file like the flutter team packages like (framework.dar,material.dart,...) so it gives me more than 1k spell error.
i got this error a few days ago

**Comment by Jason3S** [comment]
@A7medMajed16,

Have you tried ignoring those files? There is a setting `"cSpell.ignorePaths": []`.

<img width="1020" alt="image" src="https://github.com/streetsidesoftware/vscode-spell-checker/assets/3740137/8ca69036-9eb1-4770-86db-1ff5aac7bc3a">
