### ISSUE TITLE
Found by VS Code bisect

### ISSUE THREAD

**Issue by petevb** [streetsidesoftware/vscode-spell-checker#3211]
Type: <b>Bug</b>

I've been using this for a while without issue.  Just recently, I got a consistent error on vscode (insiders) startup.  Bisect says this is the culprit.

https://code.visualstudio.com/blogs/2021/02/16/extension-bisect#_welcome-extension-bisect

Extension version: 3.0.1
VS Code version: Code - Insiders 1.89.0-insider (6d23b7f11a3d7292b9458f0de7160048089398f9, 2024-04-24T05:49:19.433Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i9-13900 (32 x 1997)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.70GB (22.86GB free)|
|Process Argv|. --crash-reporter-id 8ad0b8ab-7ca3-45a7-9f2b-9192a13aab12|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscod805cf:30301675
vsaa593cf:30376535
py29gd2263:31024238
c4g48928:30535728
a9j8j154:30646983
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
fegfb526:30952798
bg6jg535:30979844
ccp1r6:30958151
pythonait:30973460
gee8j676:31009450
showvideot:31016890
chatpanelt:31014475
724cj586:31013169
pythoncenvpt:31022790
a69g1124:31018687
j0bi8933:31021562

```

</details>

**Comment by Jason3S** [comment]
@petevb,

Can you give some more detail? What is the issue?

There isn't much to go on here.

Kind regards,
Jason

**Comment by petevb** [comment]
Thanks @Jason3S - sorry, but there's not a lot for me to go on either!  

My extension host was crashing on vscode startup.  Bisect blames this extension.  I just tried to re-enable it and get this:
![image](https://github.com/streetsidesoftware/vscode-spell-checker/assets/5563334/d9c8eaaa-c120-44ee-b921-c72169ba56df)

Please let me know if there's anything you want me to do to help diagnose.
Thanks,
Pete

**Comment by Jason3S** [comment]
@petevb,

Sorry about taking so long to get back to you. If the extension doesn't start up, it is generally caused by a bad install (For some reason VS Code doesn't download everything). The only way I know to fix it is to delete the extension and re-install it. Uninstall on VS Code doesn't work. It just disables the extension, but the code is still there. "Re-installing" just re-enables the broken extension.

On my machine they extensions are stored at:
- `~/.vscode/extensions`
- `~/.vscode-insiders/extensions`

I'm not sure about Windows.

**Comment by petevb** [comment]
@Jason3S Thanks!  

> I'm not sure about Windows.

`%USERPROFILE%\.vscode\extensions`  (and/or `.vscode-insiders`)

I've had a "cull" from that folder and reinstalled cSpell and all seems fine now.  Presumably something else wasn't playing nicely or there's an incompatibility.  Thanks again for your help.
