### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Sayantansinharay451** [streetsidesoftware/vscode-spell-checker#3238]
- Issue Type: `Performance`
- Extension Name: `code-spell-checker`
- Extension Version: `3.0.1`
- OS Version: `Linux x64 6.5.0-28-generic`
- VS Code version: `1.89.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///tmp/streetsidesoftware.code-spell-checker-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by Jason3S** [comment]
@Sayantansinharay451,

Please attach the requested file, otherwise there is not enough information to do anything.

Please see also: #650
