### ISSUE TITLE
How to disable extension by default, and only enable it for specific projects?

### ISSUE THREAD

**Issue by laurent22** [streetsidesoftware/vscode-spell-checker#3268]
Is it possible to disable the extension by default, and only enable it for specific projects? The blue lines on most files I open are distracting and almost never useful. I only need CSpell to be enabled for projects that support the tool. Any idea if that can be done?

**Comment by Jason3S** [comment]
@laurent22,

There is a configuration setting, `cSpell.enabled`:

<img width="603" alt="image" src="https://github.com/streetsidesoftware/vscode-spell-checker/assets/3740137/5a1c8b3a-6ea7-4daf-841d-e0a348324343">

If you turn it off at the User level and then back on in the Workspaces (projects), the it should work as you expect.
