### ISSUE TITLE
Request: Add Persian language

### ISSUE THREAD

**Issue by fakhamatia** [streetsidesoftware/vscode-spell-checker#327]
Please add Persian/Farsi language to VSCode Spell Checker

**Comment by Jason3S** [comment]
Thank you for the suggestion.
Dictionaries are created here: [cspell-dicts: Various cspell dictionaries](https://github.com/Jason3S/cspell-dicts)

**Comment by Jason3S** [comment]
[Persian - Code Spell Checker - Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker-persian)
