### ISSUE TITLE
feat: codecov

### ISSUE THREAD

**Issue by rbalet** [streetsidesoftware/vscode-spell-checker#3289]
## Description
Add the [codecov](https://about.codecov.io/) text

**Comment by Jason3S** [comment]
@rbalet,

It is very possible the dictionary bundled with the extension is out of date. I see that `codecov` was added about 6 months ago.

There is a new version of the Extension coming out very soon, it will have the updated dictionary.

**Comment by rbalet** [comment]
@Jason3S Like always, thx Jason for your quick answers. 

Kind regards
