### ISSUE TITLE
custom decorators settings are not synced

### ISSUE THREAD

**Issue by sapphi-red** [streetsidesoftware/vscode-spell-checker#3315]
I switched to the prerelease version (4.0.0) to try out #2887. (BTW thanks for implementing it)

The settings added in that PR seems to be not synced.
![image](https://github.com/streetsidesoftware/vscode-spell-checker/assets/49056869/d1b27eed-5a60-4668-ab7e-6e9d40519f0b)
These settings are not machine-specific so I think it should be syncable.

The workaround is to set `settingsSync.ignoredSettings`.

**Comment by Jason3S** [comment]
@sapphi-red,

Thank you for the feedback. I'll take another look at those settings. Originally I was worried that they would conflict between Windows and non-Windows systems. But, as you point out, it is more useful to carry the settings between systems.
