### ISSUE TITLE
Error - validateTextDocument 

### ISSUE THREAD

**Issue by JuliaMathias** [streetsidesoftware/vscode-spell-checker#3343]
I'm not sure when this started occurring, probably some time in the past week. But my extension is just not working at all and when I look at the output in vscode I get this:

```
[Error - 2:14:27 PM] 91	2024-06-04T17:14:26.767Z	validateTextDocument: {}	
[Error - 2:14:27 PM] 116	2024-06-04T17:14:27.662Z	validateTextDocument: {}	
[Error - 2:14:27 PM] 124	2024-06-04T17:14:27.669Z	validateTextDocument: {}	
[Error - 2:14:27 PM] 131	2024-06-04T17:14:27.676Z	validateTextDocument: {}	
[Error - 2:14:27 PM] 139	2024-06-04T17:14:27.734Z	validateTextDocument: {}	
[Error - 2:14:27 PM] 147	2024-06-04T17:14:27.785Z	validateTextDocument: {}	
[Error - 2:16:09 PM] 198	2024-06-04T17:16:09.789Z	validateTextDocument: {}	
[Error - 2:16:11 PM] 213	2024-06-04T17:16:09.884Z	validateTextDocument: {}	
[Error - 2:16:11 PM] 228	2024-06-04T17:16:11.056Z	validateTextDocument: {}	
[Error - 2:16:11 PM] 238	2024-06-04T17:16:11.161Z	validateTextDocument: {}	
[Error - 2:16:11 PM] 248	2024-06-04T17:16:11.696Z	validateTextDocument: {}	
[Error - 2:16:11 PM] 258	2024-06-04T17:16:11.958Z	validateTextDocument: {}	
[Error - 2:16:15 PM] 285	2024-06-04T17:16:15.076Z	validateTextDocument: {}	
```

The main repo I use vscode on is in Elixir, but I opened other repos in other languages and I always get the same error.

**Comment by Jason3S** [comment]
@JuliaMathias,

Thank you for the report.

What happens if you install 4.0.3? If it is already 4.0.3, you might need to delete it and reinstall because sometimes VS Code fails to install the entire extension.

It is necessary to delete the actual files.
See for locations: https://code.visualstudio.com/docs/editor/extension-marketplace#_where-are-extensions-installed

Delete all directories starting with: `streetsidesoftware.code-spell-checker-`

**Comment by JuliaMathias** [comment]
I remembered that I was using vs-code insiders and switched back to vs-code. The extension is working there! But on vs-code insiders it's still broken even after uninstalling and deleting all the directories. But I'm ok with just using normal vs-code

**Comment by Jason3S** [comment]
@JuliaMathias,

code-insiders stores the extensions in a different location: `~/.vscode-insiders/extensions`

**Comment by JuliaMathias** [comment]
@Jason3S ah, that fixed it! Thank you
