### ISSUE TITLE
[Feature Request] "Add to dictionary" missing in Code Actions

### ISSUE THREAD

**Issue by Stanzilla** [streetsidesoftware/vscode-spell-checker#3357]
Please add the "add to dictionary" functions to the Code Actions popup as well, I always have to trigger the quick fix panel separately to use them, would be nice if it was available in both.

https://github.com/streetsidesoftware/vscode-spell-checker/assets/75278/5cbf3b2f-0038-4757-bfd6-ff866fa95cb8

**Comment by Jason3S** [comment]
@Stanzilla,

Thank you for the report. Please try v4 and see if that works as you expect.

**Comment by Stanzilla** [comment]
> @Stanzilla,
> 
> Thank you for the report. Please try v4 and see if that works as you expect.

can confirm it works in v4 preview!
