### ISSUE TITLE
Should monitor and automatically reload user dictionaries

### ISSUE THREAD

**Issue by solidpixel** [streetsidesoftware/vscode-spell-checker#337]
It would be useful for the tool to have an option to monitor user dictionaries for changes. I often have a user dictionary file which I maintain by hand with project-specific terminology, but you have to either close and reopen VSCode or disable/enable the extension to force the dictionary to be reloaded.

**Comment by Jason3S** [comment]
@solidpixel, I don't have a perfect solution yet, but you do not need to restart VS Code.
Try this instead:
`F1` `Toggle Spell Checking`

![image](https://user-images.githubusercontent.com/3740137/56947461-93453f00-6b2d-11e9-87c7-8d98e9ac6df9.png)

Do it twice to turn off the spell checker and back on again. This will cause all the dictionaries to be reloaded.

**Comment by Jason3S** [comment]
You can even assign a keyboard shortcut to do it.

**Comment by solidpixel** [comment]
Thanks, that sounds like a great workaround.

**Comment by art-in** [comment]
Workaround with `Toggle Spell Checking` doesn't work for me.  
(vscode v1.38.0, code-spell-checker v1.7.18, win10)

Also there's no option to add new word directly to custom dictionary file. So it requires editing the file by hand each time.

My motivation to use custom dictionary file with new-line separated words over `cspell.json` is that it's more portable cross-IDE solution. E.g. I can [configure](https://www.jetbrains.com/help/webstorm/spellchecking.html#configure-the-dictionaries-to-use) webstorm to use same dictionary file, so as a result whole project team using it.

**Comment by henrikq** [comment]
First of, thanks for the great plugin!

`Toggle Spell Checking` workaround doesn't work for me either. My work around is to `Add Word to User Dictionary`, and then periodically transfer from my settings.json to my dictionary.
