### ISSUE TITLE
[FAQ] Is it possible to enable spell checher only for a a single file despite global setting ?

### ISSUE THREAD

**Issue by malickf** [streetsidesoftware/vscode-spell-checker#341]
Hi, thank you for your extension.

 I would like to know if it is possible to deactivate the spell checker for a certain file type ( thanks to global settings) but activate the spell checker to work on a single file of the same type ?

The only way I see for the moment is to activate this file type globally and to place `/* cSpell:disable */` in every file of this type except the one I want to spell check. It seems inefficient.

Thank you

**Comment by Jason3S** [comment]
How about using the command line tool? [cspell](https://github.com/streetsidesoftware/cspell/tree/master/packages/cspell#cspell)

The other option is to tell spell checker to ignore all files but the one you want: `settings.json`
``` jsonc
  "cSpell.ignorePaths": [
    "src/**",                   // ignore everything in source
    "!src/index.ts",            // We want to check the index.ts file.
    "**/package-lock.json",
    "**/node_modules/**",
    "**/vscode-extension/**",
    "**/.git/**",
    ".vscode"
  ],
```

**Comment by malickf** [comment]
Thank you, the option with `ignorePaths` works, great ! I have excluded all files except the one I want. For the next readers use the following : 

```
    "cSpell.ignorePaths": [
        "**.myextension",               
        "!*stillchecked.myextension"
      ],
```
