### ISSUE TITLE
No Spellcheck in Commit Message

### ISSUE THREAD

**Issue by mjmatthiesen** [streetsidesoftware/vscode-spell-checker#3421]
I used to have spell checking in the git commit message box. My coworkers have the spell check. For some reason, for me, it does not work.

Here you can see a please typo in action:

![image](https://github.com/streetsidesoftware/vscode-spell-checker/assets/16603906/6a8086ac-541e-4eda-802d-89a92f63017b)

Get the underline and suggestion in markdown, but not the git commit message box. I've looked through the config, but don't see anything crazy.

Code Spell Checker: v3.0.1

Version: 1.90.1 (system setup)
Commit: 611f9bfce64f25108829dd295f54a6894e87339d
Date: 2024-06-11T21:01:24.262Z
Electron: 29.4.0
ElectronBuildId: 9593362
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by Jason3S** [comment]
@mjmatthiesen,

Please try out v4. Let me know if that works for you.

If you want to stay on v3, it is necessary to enable the scheme by adding `vscode-scm` to `cSpell.allowedSchemas`.

**Comment by mjmatthiesen** [comment]
> @mjmatthiesen,
> 
> Please try out v4. Let me know if that works for you.
> 
> If you want to stay on v3, it is necessary to enable the scheme by adding `vscode-scm` to `cSpell.allowedSchemas`.

That's already in my allowed schema, but I switched to the pre-release and that appears to have resolved it! I did have to close vs code entirely, but after that it was active. Awesome, thanks.
