### ISSUE TITLE
disable for a single file is needed

### ISSUE THREAD

**Issue by xinx1n** [streetsidesoftware/vscode-spell-checker#3458]
such as settings.json but not all json files

**Comment by Jason3S** [comment]
There is a setting to ignore paths:

<img width="1214" alt="image" src="https://github.com/user-attachments/assets/48711adf-40eb-48c5-8322-10cc5274a050">

**Comment by xinx1n** [comment]
> There is a setting to ignore paths:
> 
> <img alt="image" width="1214" src="https://private-user-images.githubusercontent.com/3740137/350398998-48711adf-40eb-48c5-8322-10cc5274a050.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2MjA3NjQsIm5iZiI6MTcyMTYyMDQ2NCwicGF0aCI6Ii8zNzQwMTM3LzM1MDM5ODk5OC00ODcxMWFkZi00MGViLTQ4YzUtODMyMi0xMGNjNTI3NGEwNTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjJUMDM1NDI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWM3YTAyNDU2MThmODc5OTgyNzczYzFmYzFiZmY0YzZmNGFkM2IwN2ZkZTZjNmUwOGEyYjZmNmUzOGJjZDQ0ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.heddZXSNX0stLRNFr27Kic7fK990EKbNWyDEibn2rSU">

Thank you, this has solved some of my problems.
