### ISSUE TITLE
Add option to disable autocomplete popups

### ISSUE THREAD

**Issue by matklad** [streetsidesoftware/vscode-spell-checker#347]
Hi!

In the latest version, cspell started suggesting autocomplete variants for inserting suppression comments:

![image](https://user-images.githubusercontent.com/1711539/58458925-f5945e00-8132-11e9-8cd2-7957a3a3394a.png)

I would like to have an option to disable this behavior. I've looked through existing ones, and didn't find any.

**Comment by Jason3S** [comment]
You make a very good point.

**Comment by Jason3S** [comment]
I have turned them off for now. It is not easy to make them configurable. It is possible, it just takes more work than I am willing to do at the moment.

**Comment by Jason3S** [comment]
I'm closing this for now.
