### ISSUE TITLE
Connection to server got closed

### ISSUE THREAD

**Issue by wesamly** [streetsidesoftware/vscode-spell-checker#348]
Hello,
After upgrading to latest VS code version 1.34.0, I keep getting this message and the extension it not working.

```
Error: Cannot find module '/Users/wesam/.vscode/extensions/streetsidesoftware.code-spell-checker-1.7.12/server/server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:753:10)
    at startup (internal/bootstrap/node.js:241:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:579:3)
[Error - 1:49:48 PM] Connection to server got closed. Server will not be restarted.
```

I tried uninstall/install but got the same issue.

Help please.

**Comment by Jason3S** [comment]
@wesamly,
Sometimes when VS Code is updated, sometimes it leaves orphaned processes. Please quit VS Code and look for any processes called `Code Helper` and kill them.
Then you can restart VS Code.

**Comment by wesamly** [comment]
@Jason3S 
No such processes. Thank you.

**Comment by wesamly** [comment]
Now I reinstalled the extension, and  it is working. May be I didn't close all windows before. Thanks @Jason3S
