### ISSUE TITLE
Error - validateTextDocument

### ISSUE THREAD

**Issue by ili101** [streetsidesoftware/vscode-spell-checker#351]
Issue Type: <b>Bug</b>

After updating to 1.7.14 if VSCode don't have a folder open and you create a new file (Untitled-x) the Output panel starts throwing errors like
```
[Error - 14:39:50] 26	2019-06-03T11:39:50.257Z	validateTextDocument: {}	
```
![image](https://user-images.githubusercontent.com/6960531/58799512-26cacd80-860e-11e9-96a3-262dab481ad5.png)

Extension version: 1.7.14
VS Code version: Code 1.34.0 (a622c65b2c713c890fcf4fbf07cf34049d5fe758, 2019-05-15T21:59:37.030Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (7.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details>

**Comment by masilver99** [comment]
Same problem here.  Reverting to the previous version is a workaround.

**Comment by Jason3S** [comment]
Please update to 1.7.16

**Comment by jacobian** [comment]
Thanks for the quick fix! 🤗
