### ISSUE TITLE
Add settings option to disable cSpell entry in status bar

### ISSUE THREAD

**Issue by janosh** [streetsidesoftware/vscode-spell-checker#353]
![cSpell options](https://user-images.githubusercontent.com/30958850/58950002-aaf39100-8785-11e9-9439-b68053a55fff.png)

**Comment by Jason3S** [comment]
It is available in VS Code Settings. Search for `showstatus`.
![image](https://user-images.githubusercontent.com/3740137/58956565-f1091e80-879e-11e9-9a9f-7e4c4e401a52.png)

**Comment by janosh** [comment]
Oops, sorry about the spam.
