### ISSUE TITLE
Issue on unsaved files

### ISSUE THREAD

**Issue by Stanzilla** [streetsidesoftware/vscode-spell-checker#3535]
I sometimes abuse unsaved files in an open project as a notepad, when I do that, CSC seems to try to run on them which fails with the following message

![image](https://github.com/user-attachments/assets/f935f0dd-916a-4b5d-a864-cd9149291d19)

CSC Version: v4.0.7 (pre-release)

**Comment by Jason3S** [comment]
@Stanzilla,

Thank you. That should not happen.
