### ISSUE TITLE
Unnecessary creation of .vscode folder

### ISSUE THREAD

**Issue by werunom** [streetsidesoftware/vscode-spell-checker#354]
Whenever a word is added to `folder dictionary` (through the `Show fixes` command > `Add: <unrecognised-word> to folder dictionary`),  a dot folder `.vscode` is getting created under the project folder. In this folder, a `settings.json` is getting created and the added words are getting appended here. 

Is it not creation of this dot folder and file unncessary duplication? Because the same word is added to `cspell.json` and also to `Notes.code-workspace`, both under the project folder (which had already been mentioned [here](https://github.com/streetsidesoftware/vscode-spell-checker/issues/335)).

**Comment by Jason3S** [comment]
VS Code is creating the `.vscode` folder. But I can check to see if a `cspell.json` file exists to avoid having VS Code create the `.vscode/settings.json` file.
