### ISSUE TITLE
Unable to get extension working in VS-Code for PowerShell (US English)

### ISSUE THREAD

**Issue by PNW-Hacker** [streetsidesoftware/vscode-spell-checker#3541]
Hello Team,

I hope this is an easy fix and I am just missing something super simple that someone can help with directing me to a resolution.

I am submitting this new issue since I did not find a previous issue already created about this and I see newer issues where it seems like this extension is working (just other issues with the extension, but not completely non-functional)

OS I'm running: Win 10 22H2

Vs-Code Version I'm on:

Version: 1.92.2 (user setup)
Commit: fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
Date: 2024-08-14T17:29:30.058Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.19045

Version of extension: Code Spell Checker v3.0.1

![No Underlining](https://github.com/user-attachments/assets/736b3f73-1cf7-4624-8044-d0bd98e19c31)

Per the image I uploaded, there is no underlining.

Thing's I've tried:

Reinstalling the extension and reloading the window
Completely uninstalling and reinstalling the extension
Closing and reopening VS-Code
Rebooted system

I have not completely reinstalled VS-Code yet

**Comment by Jason3S** [comment]
@PNW-Hacker,

That sounds very frustrating. Please try out the [v4.0.9 preview](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker) version and see if that fixes the issue.

Possible causes:
1. Spell Checking is turned off. Please run the Enable Spell Checking command:
   <img width="618" alt="image" src="https://github.com/user-attachments/assets/69f33a84-ade1-4089-a2c4-bd145dcb18ab">
1. The extension did not fully install.
2. The scheme is not enabled
3. The file type (LanguageId) is not enabled.

(I'll add a bit more detail later)

**Comment by PNW-Hacker** [comment]
Hi @Jason3S 

Thank you for the reply and assistance, much appreciated :)

![Switched to Pre-release version](https://github.com/user-attachments/assets/7edbfced-2377-49bf-b2fb-8e9d26333670)

I was on the Released version, switched to the Pre-release version and did a Reload Window command, still didn't seem to make a difference. Per screenshot above of pre-release

I tried your screenshot suggestion, but per the below screenshot, the command does not exist even though within the extension Settings, it is Enabled

![Unable to find command, but is Enabled](https://github.com/user-attachments/assets/3bba9154-9949-4c1e-b15c-ad70facbf6aa)

There's a possibility with number 2 considering that the command does not show up within VS Code, but if that is the case, I do not know off hand how to get it to fully install if it is truly corrupt

I am not sure how to do 3 or 4, when I installed it I just left all of the defaults since the main portion of this repo basically says that that's all that needs to be done to get it working

There is this section that seems to me to show that English is enabled

![C Spell Language](https://github.com/user-attachments/assets/c28c19ab-3095-4693-95ef-f170ed23948a)

**Comment by Jason3S** [comment]
@PNW-Hacker,

There might be a couple of things happening. Do you have any files open in the editor? Or just the `Untitled-1`? Please save it to disk or try opening a file, any text file, code or markdown. Does it start spell checking? If that doesn't work, then try **How to fully reinstall the extension** below.

My guess is that because there are no files open, the Spell Checker is having problems determining the settings.

This is what I see on the status bar when I hover over `{}`: 

<img width="528" alt="image" src="https://github.com/user-attachments/assets/175c8d30-71b7-48af-8123-f7e3f669b3ef">

To be clear, the spell checker is not working as expected when no files are open. I'll open a related issue.

## How to fully reinstall the extension

If the command doesn't run or show up, then it is most likely not installed correctly. This is a known VSCode bug.

To manually delete the extension:
- Use the UI to uninstall the Extension
- Find the extension directory, see: [Where are extensions installed?](https://code.visualstudio.com/docs/editor/extension-marketplace#_where-are-extensions-installed).
- Remove all directories starting with: `streetsidesoftware.code-spell-checker`
- Use the UI to install the Extension

**Comment by Jason3S** [comment]
Please try 4.0.11

<img width="652" alt="image" src="https://github.com/user-attachments/assets/06958959-d18f-4b8b-97ff-16b4502cf75e">

**Comment by PNW-Hacker** [comment]
@Jason3S 

Good Evening :)

So it does work if I create a file, save it, and try again. (This isn't my normal process since I am a beginner coder at best and only save things towards the end when I know I want to keep them, but I also run mini code scripts for testing my larger scripts I'm in the process of building in Untitled tabs) But now there is something wrong with seeing the latest versions of the ext (should I completely reinstall VS Code at this point?). I did uninstall the ext and also delete the ext folder within my user directory per the hyperlinked article (appreciate it) before trying to reinstall, but this is what I see

![Listed Versions of Ext](https://github.com/user-attachments/assets/560f216f-f831-4e45-b757-5f5d1266cf27)

![Typing in 4 0](https://github.com/user-attachments/assets/00cfa4cb-91eb-4c4e-9c9a-5fa5b509355e)

![Newest version I see](https://github.com/user-attachments/assets/f2ce88aa-a485-4772-a7ff-c52a78b43f43)

**Comment by Jason3S** [comment]
@PNW-Hacker,

I think you must first install the normal version before switching to the prerelease version.

**Comment by Jason3S** [comment]
By the way, thank you. You helped me find an edge case issue that happened only when `untitled` files were opened with out any other files.

**Comment by PNW-Hacker** [comment]
@Jason3S 

You are welcome, and thank you very much for fixing this :) The Pre-release version now works on untitled files

![Pre-release version](https://github.com/user-attachments/assets/5a7f79c4-eaf4-4290-b0f5-3a4607fa5abd)

![Pre-release Works](https://github.com/user-attachments/assets/932e6f50-fb2c-448f-85f6-7f1cf5fe1e27)

**Comment by Jason3S** [comment]
Wonderful.

I'm going to close this as completed.
