### ISSUE TITLE
Lightbulb is tiny, appears far away from text

### ISSUE THREAD

**Issue by mikemaccana** [streetsidesoftware/vscode-spell-checker#355]
See below:

![image](https://user-images.githubusercontent.com/172594/59434656-e88a9680-8de3-11e9-871c-86503629f29d.png)

Would it be possible to ditch the lightbulb and just add the suggestions to right click instead?

**Comment by Jason3S** [comment]
I intend to add suggestions to the right click menu, I just need to figure out a clean way to do it.

In the mean time, there are other ways to get suggestions.

**Hover over the word:**
![image](https://user-images.githubusercontent.com/3740137/59548968-8dc57c00-8f56-11e9-923b-a821bc172ef0.png)

and click *quick fix*.

When the cursor is on the word, you can type: `cmd-.` or `ctrl-.` depending upon your OS.

**Comment by Jason3S** [comment]
Related to #320
