### ISSUE TITLE
Spell cheker

### ISSUE THREAD

**Issue by samurai-prog** [streetsidesoftware/vscode-spell-checker#3558]
Only English spell checker works other languages (for ex: Russian) are not working

**Comment by Jason3S** [comment]
@samurai-prog,

Please provide the following information:
- What version of the spell checker have you installed?
- What language extension did you install?
- Did you enable the language locale?
  It is necessary to [Enable the Dictionary](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker-russian#enable-dictionary) before it gets used.
