### ISSUE TITLE
Add Solidity language

### ISSUE THREAD

**Issue by ilanolkies** [streetsidesoftware/vscode-spell-checker#358]
Spelling is similar to JavaScript

**Comment by Jason3S** [comment]
I need to take a look at turning it on by default, but you can turn it on yourself:
1. Open a `Solidity` file
1. `F1` `Enable Spell Checking Document Language`

![image](https://user-images.githubusercontent.com/3740137/60172520-225c9380-980d-11e9-864c-4d78201136cd.png)

**Comment by ilanolkies** [comment]
It works, thanks.
