### ISSUE TITLE
cSpell doesn't understand python r strings

### ISSUE THREAD

**Issue by david-waterworth** [streetsidesoftware/vscode-spell-checker#359]
Is there any way of telling cSpell that r'train' isn't a word, i.e. ignore the r'' delimiter and only check the string contents when spell checking a py file?

**Comment by Jason3S** [comment]
Good catch. I'll fix it in the next release.

In the mean time you can change your settings to ignore the `r'`.

`F1` `Preferences Open Settings JSON`

add the following to the `settings.json` file:

``` jsonc
{
    // ... Other settings already in the file.

    "cSpell.languageSettings": [
        {
            "languageId": "python",
            "ignoreRegExpList": [ "raw_string" ],
            "patterns": [
                { "name": "raw_string", "pattern": "\\bu?r'" }
            ]
        }
    ]
}
```

**Comment by Jason3S** [comment]
Raw strings are now part of the Python dictionary.

**Comment by Jason3S** [comment]
See: [cspell-dicts python](https://github.com/streetsidesoftware/cspell-dicts/blob/master/packages/python/cspell-ext.json)
