### ISSUE TITLE
Q: Markdown

### ISSUE THREAD

**Issue by neilyoung** [streetsidesoftware/vscode-spell-checker#360]
Hi,
I'm convinced this spell checker is able to check markdown files, at least there is no indication that it wouldn't work. However, not only, that my MD file does not have any single failure (which is unlikely), even if I explicitly create a wrong spelling it is not marked as such. What is going wrong?

**Comment by Jason3S** [comment]
It does check `markdown` files by default. But there might be a reason it is not working.

You should see something like this in the status bar at the bottom of VS Code:
![image](https://user-images.githubusercontent.com/3740137/60975167-caa14a80-a32b-11e9-8ad7-611b827c1513.png)

That means that spell checking is turned of for `markdown` and for the file `README.md`.

**Comment by neilyoung** [comment]
Yes, this is checked.

**Comment by neilyoung** [comment]
But doesn't work either

**Comment by neilyoung** [comment]
That being said: Tried again with the June edition of VSCode. Works! Thanks
