### ISSUE TITLE
💡: Separate Diagnostic Level for forbidden words

### ISSUE THREAD

**Issue by tjzel** [streetsidesoftware/vscode-spell-checker#3612]
### Problem

Sometimes when I edit a file that has a large amount of unknown words I can make a fatal mistake, i.e. putting in `node-modules` instead of `node_modules`. `node-modules` is on my forbidden words list, but the squiggle is the same for the rest of the unknown words, so I subconciously ignore it and later on debug vague errors.

### Solution

An option to set forbidden words diagnostic level to `error` would allow the users to distinguish between simple unknown words and fatal typos.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Jason3S** [comment]
@tjzel,

Thank you for the enhancement idea.

The v4 preview version has more control related to flagged / forbidden words. 

- By default, the spell checker no longer adds words to the Problems pane, they are instead added to the Spell Checker pane. It is possible to change this in the settings and change the diagnostic level for flagged words.
   <img width="427" alt="image" src="https://github.com/user-attachments/assets/2c4e7021-b840-48ef-a779-eb95a33ae941">
   <img width="963" alt="image" src="https://github.com/user-attachments/assets/41b756eb-778c-446e-b09a-f7647973e96f">

- If custom decorations are used, by default, the flagged words are drawn with a different color.
   <img width="431" alt="image" src="https://github.com/user-attachments/assets/72e4fdb7-f16e-471f-968f-afd7f670d416">

Please try it out and let me know if it works as you expect.

**Comment by tjzel** [comment]
Hey I just tried it and it's awesome! Thank you for your outstanding work! I'll keep using the preview version and report any issues I encounter ❤️
