### ISSUE TITLE
Spell correction doesn't fully function

### ISSUE THREAD

**Issue by Leakbang** [streetsidesoftware/vscode-spell-checker#362]
This function used to work normally but at some point maybe after an update, it stopped working. As it can be seen in the gif I attached if I hover on the word then click quick-fix then select one of the options, it won't work and it'll do nothing. However, if I click on the bulb icon when I hover on the word, it corrects the word just fine.
I tried uninstalling and reinstalling and I looked around in the settings to see if something is wrong on my side.
https://i.imgur.com/D72tMLU.gifv

**Comment by MatthewAugier** [comment]
Just come to report same issue, fresh install on plugin on vsCode 1.36.1, windows.

**Comment by Jason3S** [comment]
Both methods use the same code in the extension. Something must have changed with the latest release of VS Code. I'll check it out when I get the chance.

**Comment by Leakbang** [comment]
I just figured a few hours ago that the quick-fix button does not work at all, this is an issue with vscode not with your addon.

**Comment by Leakbang** [comment]
Here people seem to have found a solution, recommend checking it out
https://github.com/microsoft/vscode/issues/77018

**Comment by Leakbang** [comment]
This issue has been fixed in the latest VSCode Update
