### ISSUE TITLE
Does not recognize escape character, `\b`, `\t` for example.

### ISSUE THREAD

**Issue by JounQin** [streetsidesoftware/vscode-spell-checker#365]
`\bvuex\b`

![image](https://user-images.githubusercontent.com/8336744/61585828-24a9d780-ab98-11e9-9bff-33e04c168ae4.png)

**Comment by Jason3S** [comment]
Are you seeing an issue if it is a known word?

`\bhouse\b` should be fine. But with `\bhouze\b` it will report `bhouze`.

**Comment by JounQin** [comment]
Oh, `vuex` itself was an unknown word at that moment which I didn't realize before.

**Comment by Jason3S** [comment]
I'm going to close this for now.

**Comment by JounQin** [comment]
@Jason3S But the message is wrong.

**Comment by Jason3S** [comment]
I agree that it doesn't show what you expect.
