### ISSUE TITLE
Shows spelling errors for a whole project

### ISSUE THREAD

**Issue by petoknm** [streetsidesoftware/vscode-spell-checker#3666]
Hi,

I found that in a previous issue you suggest using `cspell` npm package for doing a spell check of the whole project/directory. (https://github.com/streetsidesoftware/vscode-spell-checker/issues/1978)

I think it would be nice if the vscode extension could do that as well, since I am assuming the extension already depends on `cspell`.

That way I wouldn't need to do extra manual install steps and learning a new cmdline tool.

**Comment by Jason3S** [comment]
@petoknm,

The new version (v4, still in preview) has a REPL that allows you to search for spelling issues. It is missing some features, but the basics work.

![image](https://github.com/user-attachments/assets/e55d4963-8352-467e-a6ea-224be93340ea)

![image](https://github.com/user-attachments/assets/2902d0df-0e0e-4608-bbe7-2080839429d2)

It is not yet as full featured as the command line (and a bit slower), but it does remove the need to install the command line tool.

Please try it out. Feedback is welcome.

The REPL supports spell checking remote repositories, which is not possible with the command line tool.

**Comment by petoknm** [comment]
Nice, the REPL worked great for me, thanks
