### ISSUE TITLE
Disable for other languages ?

### ISSUE THREAD

**Issue by ahmadyousefdev** [streetsidesoftware/vscode-spell-checker#367]
Hi, I was wondering if there is a way to disable the spell checker for other languages that doesn't have the same latin characters, for example Arabic or Bengali or Japanese.

**Comment by Jason3S** [comment]
There is an indirect way of doing it by having the spell checker ignore it.

If you add `ignoreRegExpList` to `cspell.json` or in the VS Code settings `cSpell.ignoreRegExpList`.

Example for Arabic:
``` javascript
"ignoreRegExpList": [
    "/[\\u0621-\\u064A]+/"
]
```

**Comment by ahmeed83** [comment]
Thanks Jason, that solved the problem!

**Comment by Alirezanet** [comment]
> There is an indirect way of doing it by having the spell checker ignore it.
> 
> If you add `ignoreRegExpList` to `cspell.json` or in the VS Code settings `cSpell.ignoreRegExpList`.
> 
> Example for Arabic:
> 
> ```js
> "ignoreRegExpList": [
>     "/[\\u0621-\\u064A]+/"
> ]
> ```

Works for Persian too. thanks
