### ISSUE TITLE
Obtain Verified Publisher Status with VSCode Marketplace

### ISSUE THREAD

**Issue by alcarcdr** [streetsidesoftware/vscode-spell-checker#3677]
Where I work we are only permitted to use extensions that have the blue tick indicating a verified publisher. This is a hard and fast rule with absolute no exceptions, if is assumed by cyber security team that unless a publisher is verified by VS Code Marketplace then they are not to be trusted.

As I would very much like to use this spellchecker I must ask if Steet Side Software would please undertake to obtain verified publisher confirmation in VS Code Marketplace.

**Comment by Jason3S** [comment]
@alcarcdr,

Thank you for letting me know. We had the blue check mark from the beginning. I'm not sure what had happened.

Here is an image from a few weeks ago:
![Switched to Pre-release version](https://github.com/user-attachments/assets/7edbfced-2377-49bf-b2fb-8e9d26333670)

https://github.com/streetsidesoftware/vscode-spell-checker/issues/3541#issuecomment-2298051065

I'll try to find out what happened.

**Comment by Jason3S** [comment]
I have gone through the process to have them re-verify the domain. Hopefully, the issue will get fixed soon.

**Comment by Jason3S** [comment]
Thank you for letting me know. It has been fixed:

[![image](https://github.com/user-attachments/assets/82d17579-7cbc-434a-8b01-93830a70074d)](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker)
