### ISSUE TITLE
Support cascading per-folder configurations

### ISSUE THREAD

**Issue by alexolog** [streetsidesoftware/vscode-spell-checker#3684]
Some tools support per-folder cascading configuration files, for example:
- `.gitignore`
- `.clang-tidy` and `.clang-format`
- etc.

Please support similar functionality.

Example use case: ignoring words heavily used in some files without adding them to global dictionaries, disabling globally, or polluting the code with tool-specific comments.

**Comment by Jason3S** [comment]
@alexolog,

The spell checker uses the [CSpell](https://www.npmjs.com/package/cspell) library to do the spell checking. It has always supported local configuration files. The spell checker will search up the directory hierarchy looking for CSpell config files. The nearest one found will be used.

<details>
<summary>Config Search Locations</summary>

- `package.json`
- `.cspell.json`
- `cspell.json`
- `.cSpell.json`
- `cSpell.json`
- `.cspell.jsonc`
- `cspell.jsonc`
- `.vscode/cspell.json`
- `.vscode/cSpell.json`
- `.vscode/.cspell.json`
- `.cspell.config.json`
- `.cspell.config.jsonc`
- `.cspell.config.yaml`
- `.cspell.config.yml`
- `cspell.config.json`
- `cspell.config.jsonc`
- `cspell.config.yaml`
- `cspell.config.yml`
- `cspell.config.mjs`
- `cspell.config.cjs`
- `cspell.config.js`
- `.cspell.config.mjs`
- `.cspell.config.cjs`
- `.cspell.config.js`
- `.cspell.yaml`
- `.cspell.yml`
- `.config/.cspell.json`
- `.config/cspell.json`
- `.config/.cSpell.json`
- `.config/cSpell.json`
- `.config/.cspell.jsonc`
- `.config/cspell.jsonc`
- `.config/cspell.config.json`
- `.config/cspell.config.jsonc`
- `.config/cspell.config.yaml`
- `.config/cspell.config.yml`
- `.config/cspell.config.mjs`
- `.config/cspell.config.cjs`
- `.config/cspell.config.js`
- `.config/.cspell.config.json`
- `.config/.cspell.config.jsonc`
- `.config/.cspell.config.yaml`
- `.config/.cspell.config.yml`
- `.config/.cspell.config.mjs`
- `.config/.cspell.config.cjs`
- `.config/.cspell.config.js`
- `.config/cspell.yaml`
- `.config/cspell.yml`


</details>

Each file can specify its own list of words and dictionaries.

What are you hoping for?

**Comment by alexolog** [comment]
> What are you hoping for?

```
vscode workspace/
├── src/
│   ├── server/
│   │   ├── file1.cpp
│   │   └── cspell.json [1]
│   ├── client/
│   │   ├── file2.js
│   │   └── cspell.json [2]
│   ├── readme.txt
│   └── cspell.json [3]
├── db/
│   ├── file3.sql
│   └── cspell.json [4] 
├── license.txt
└── cspell.json [5]
```
When spell-checking a.cpp, I would like the effective settings to be taken from [1], [3], and [5], with single-value options overriding the upper-level ones, and list options combining.

Alternatively, only [1] could be used for `file1.cpp`, [3] for `readme.txt`
I mostly want to ignore certain words in some files/folders but flag them in different ones, without adding cspell comments in the files themselves.

Speaking of which, is it possible to have something like `cSpell:ignoreRegExp` in the config instead of a file comment?

**Comment by Jason3S** [comment]
@alexolog,

CSpell config has an `import` option to import other configuration files. This is how all dictionaries are loaded.

**`src/server/cspell.json`**

```jsonc
{
  "import": ["../cspell.json"],
  "ignoreRegExpList": ["/\\b[A-Z]{4,}\\b/g"] // Ignore ALL CAPS words 4 or longer. 
}
```

See: [Exclude / Include Patterns | CSpell](https://cspell.org/configuration/patterns/)

**Comment by alexolog** [comment]
This works. Thank you!
