### ISSUE TITLE
CSpell "problems" not cleaned after closing file [intermittent]

### ISSUE THREAD

**Issue by alexolog** [streetsidesoftware/vscode-spell-checker#3692]
CSpell complained on misspellings in the user `settings.json`.

After closing the file, the messages remained:

![image](https://github.com/user-attachments/assets/baee6486-5380-4599-88c5-ff027325739d)

I expected them to be cleared.

The interesting part is that the issue is intermittent.  Right now I have 2 vscode instances running concurrently, and it only happens in one of them.

**Comment by Jason3S** [comment]
VS Code opens files in the background. When it opens the files, it triggers the spell checker.

There are two work arounds:

1. Use custom decorations: `cSpell.useCustomDecorations`
   <img width="554" alt="image" src="https://github.com/user-attachments/assets/109a0b85-3864-4793-a4d5-1631926c5769">
   The spell checker will handle rendering issues and files opened by VS Code in the background will not show up.
1. The `Spell: Toggle Show Spelling Issues`, `Spell: Show Spelling Issues`, and `Spell: Hide Spelling Issues` commands can be used to show/hide spelling issues. Using these command will clean up and left over issues in the problem pane.
   <img width="380" alt="image" src="https://github.com/user-attachments/assets/a4bbd743-6e39-457b-a41f-304e189856f2">
