### ISSUE TITLE
"checkboxes" is detected incorrectly as wrong

### ISSUE THREAD

**Issue by i5heu** [streetsidesoftware/vscode-spell-checker#370]

**Comment by Jason3S** [comment]
Thank you.

**Comment by Jason3S** [comment]
It will be fixed in the next release.

[Update en_US Dictionary](https://github.com/streetsidesoftware/cspell-dicts/commit/bfbd178f7a270bedb789dcb6c180c23bee1dbc5e)

**Comment by i5heu** [comment]
Thank You <3
