### ISSUE TITLE
multi folder workspace: Add to workspace dictionary does not work

### ISSUE THREAD

**Issue by derekwallace** [streetsidesoftware/vscode-spell-checker#374]
Hi
Im using the latest version 1.7.18

If i have a workspace that has just 1 folder , when i add a new word i have 2 option
Add Word to user dictionary
Add Word to folder dictionary

If i have a workspace that has 2 folder , when i add a new word i have 3 option
Add Word to user dictionary
Add Word to workspace dictionary
Add Word to folder dictionary

If i select "Add Word to workspace dictionary" it does not work. the word is not added to the <name>.code-workspace file.
If i select "Add Word to folder dictionary" it does work. 

Thx
derek

**Comment by samtsai** [comment]
I've recently been encountering this myself, and as the OP mentions, when I have two folders in my workspace it works.

**Comment by Jason3S** [comment]
@samtsai Would you be clean on the behavior you are seeing and what you are expecting.

If you have a `cspell.json` file in the first folder, I suggest you import it into your workspace:

![image](https://user-images.githubusercontent.com/3740137/76060315-461dcf00-5f81-11ea-8916-8957e75ea57e.png)

`${workspaceFolder}` is replaced by the path to the *current* workspace folder. I suggest choosing the exact folder to read the `cspell.json` from. To do this use `${workspaceFolder:<folder name>}/cspell.json` where `<folder name>` is the name of the folder containing the file. In the image above, `${workspaceFolder:vscode-spell-checker}/cSpell.json` the folder name is `vscode-spell-checker`.

**Comment by samtsai** [comment]
Hi @Jason3S sure.

I currently do not import any C Spell and have been trying to use workspace settings.
![Screenshot 2020-03-06 09 58 26](https://user-images.githubusercontent.com/225526/76094992-88e7a300-5f91-11ea-9138-856824bb3ee0.png)

When I have a workspace with only one directory:
![Screenshot 2020-03-06 09 57 11](https://user-images.githubusercontent.com/225526/76094922-6e152e80-5f91-11ea-9cd5-deff8f98db41.png)

I do not see the option to add words to workspace dictionary:
![Screenshot 2020-03-06 10 00 17](https://user-images.githubusercontent.com/225526/76094953-7cfbe100-5f91-11ea-9774-a27f037b19d4.png)

Then, when I update my workspace to add another folder:
![Screenshot 2020-03-06 09 59 09](https://user-images.githubusercontent.com/225526/76095062-a583db00-5f91-11ea-99d6-98288d4c5f7d.png)

Reload the workspace window and retry the same word, I can now see the workspace dictionary option:
![Screenshot 2020-03-06 10 00 58](https://user-images.githubusercontent.com/225526/76095072-a9176200-5f91-11ea-8e44-cb96c954244a.png)
