### ISSUE TITLE
Option to run spell check on entire files/folders

### ISSUE THREAD

**Issue by millergd** [streetsidesoftware/vscode-spell-checker#376]
There needs to be an option to run spell check on an entire file/folder either through the command line or through the interface. The same way linting can be run or spell check in MS Word. The npm package doesn't integrate with any of the VS Code plugin settings

**Comment by Jason3S** [comment]
The VS Code spell checker is based upon [cspell](https://www.npmjs.com/package/cspell). If you install it, is should be possible to check all your files with a single command.

**Comment by millergd** [comment]
The CMD line tool cspell can check entire directories, but it doesn't integrate with any of the VS Code settings in place. My suggestion is to either make the VS Code settings compatible with the CMD line tool cspell, or create an option in VS Code to check entire directories through the application.

I have the issue where I see misspelled words in VS Code, so I add them to the dictionary or ignore them which adds them to a list under the hood in VS Code. But cspell has its own list of custom/ignored words. So my solution is either to continuously sync settings between the two manually, or only use the cspell CMD line tool and remove the VS Code plugin.

**Comment by Jason3S** [comment]
@millergd If you have a `cspell.json` file at the root of your project, both the `cspell` cmd line tool and the extension will use it. Are you seeing a different behavior?

**Comment by millergd** [comment]
> If you have a cspell.json file at the root of your project, both the cspell cmd line tool and the extension will use it.

Awesome! It works just as you have described. If I right-click and add a word to the "folder" dictionary through the app, it creates a `settings.json` at my root even if I already have a `cspell.json`. Regardless, the fact that the `cspell.json` file is updated synchronously is sufficient. Thanks for clarifying this @Jason3S

**Comment by fsanzv** [comment]
@Jason3S Please, can you tell me how to get this working with several dictionaries?. I have installed `Spanish - Code Spell Checker` and I wonder if is it possible to run cspell against whole project with same configuration as it runs on every file in VS Code.

**Comment by Jason3S** [comment]
It is a bit annoying, but you need to install the Spanish Dictionary separately. 
See: [cspell-dict-es-es - npm](https://www.npmjs.com/package/cspell-dict-es-es)

**Comment by fsanzv** [comment]
Working!, thank you very much!!!

**Comment by echarrod** [comment]
Although you seem to have answered @millergd's problem which he mentioned in a subsequent comment, the original suggestion of being able to scan a whole directory from within the VS Code extension would be very valuable, and as far as I understand, still isn't possible. 

Are there any plans to add this?

**Comment by nickchomey** [comment]
I'd also like to be able to spell check a folder

**Comment by Nosh-Ware** [comment]
So, is this on the list for implementation any time soon?

**Comment by xansh** [comment]
Hi!
Any plans to add this soon?

**Comment by Jason3S** [comment]
@xansh,

Because there is a command line alternative, there isn't any urgency to do this. 

`cspell <directory>`:

```sh
npx cspell .
```

I'm going to close this issue as not planned, since the original request was answered.

Please open an new issue if the command line tool is insufficient.
