### ISSUE TITLE
Not working with java files.

### ISSUE THREAD

**Issue by cyberxander90** [streetsidesoftware/vscode-spell-checker#379]
I am currently working with java in vs-code and have already installed this extension, but the extension is ignoring my `.java` files.
I search in the code speller configuration and aggregate the `java` keyword to the Enabled Language Ids section.
![image](https://user-images.githubusercontent.com/8105754/64192412-ff73de80-ce50-11e9-9123-4ee2c40026cd.png)

**Comment by Jason3S** [comment]
Something else might be preventing them from being checked. Do you have a `cspell.json` file. The settings in that file override the settings from VS Code.

Not checked looks like this: 
![image](https://user-images.githubusercontent.com/3740137/64478203-42151e00-d1a5-11e9-836f-f8799360ead9.png)

**Comment by Jason3S** [comment]
Closing due to no response.
