### ISSUE TITLE
[Question] Where are the dictionaries?

### ISSUE THREAD

**Issue by lonix1** [streetsidesoftware/vscode-spell-checker#380]
When I click the button in the toolbar, it shows me that there are various different types of dictionaries, and implies I can add more.

Where do I find them? For example, where do I find the "companies" dictionary?

All the words I added to the custom dictionary appear in my user or workspace settings. What I prefer is to add separate dictionaries e.g. "common", "company", "products", etc. I can't find docs for that.

**Comment by Jason3S** [comment]
The spell checker comes with a set of dictionaries.

You can add your own: [how-to-add-your-own-dictionaries](https://github.com/Jason-Rev/vscode-spell-checker/blob/master/packages/client/README.md#how-to-add-your-own-dictionaries)
