### ISSUE TITLE
Color in v4.0.18

### ISSUE THREAD

**Issue by JingTongsh** [streetsidesoftware/vscode-spell-checker#3804]
After updated to v4.0.18, the color for text decoration in the editor and that in the scroll bar became yellow, easily confused with other warnings or errors. Even when I configure it blue:
```
"cSpell.textDecorationColorFlagged": "#0080ff",
"cSpell.textDecorationColorSuggestion": "#0080ff",
"cSpell.textDecorationColor": "#0080ff",
```
It only works for the editor, while the lines are still yellow in the scrollbar:
<img src="https://github.com/user-attachments/assets/c6f31557-40dd-4a0c-a0d4-4671439fc4b1" width="320" />

Here's what the same file looks like in v3.0.1.Note how the rightmost scrollbar differs from above:
<img src="https://github.com/user-attachments/assets/dc6c52a4-a9a7-4c93-85a4-9940ebe454d0" width="320" />

Hope you can change the default color, and make the scrollbar consistent with the editor.

**Comment by Jason3S** [comment]
@JingTongsh,

Thank you. The setting is called: `cSpell.overviewRulerColor`.

**Comment by JingTongsh** [comment]
OK, thank you.

**Comment by Jason3S** [comment]
I agree that it is not obvious. I'll add a link in the description, maybe that will make it easier.

The challenge is that the ruler color generally has alpha while the text color does not.

I'm also thinking about adding a toggle setting for the ruler.

**Comment by SamirMishra27** [comment]
Before this update what colour was cSpell using to highlight those lines? I need the exact config

**Comment by GaurangTandon** [comment]
It looks like the colors were set again to blue in v4.0.19. Updating the extension and resetting the setting `cSpell.overviewRulerColor` to default fixed it for me.

**Comment by bluenote10** [comment]
I'm on version `v4.0.21` and for me they are still yellow instead of blue, and I constantly confuse them with warnings. I have not configured the ruler color explicitly, and the settings show a default value of `#fc4c`, which is a yellow.

Has there been another regression regarding the color?

**Comment by Jason3S** [comment]
@bluenote10,

There is a bug in VS Code at the moment that does not correctly update the settings. Restarting VS Code should fix the issue.

See: https://github.com/microsoft/vscode/issues/234476
