### ISSUE TITLE
Ignore paths do not work with folders

### ISSUE THREAD

**Issue by Gruntfuggly** [streetsidesoftware/vscode-spell-checker#381]
If I specify a filename in the ignorePaths it gets ignored. However, if I add any sort of path to the filename it is no longer ignored.

I have tried using '**' and '*' and the explicit path and none of them seem to work.

**Comment by Jason3S** [comment]
@Gruntfuggly are you on Windows or another OS?

Can you give me an example path?

**Comment by Gruntfuggly** [comment]
Here's my settings:

```
    "cSpell.ignorePaths": [
        "**/package-lock.json",
        "**/node_modules/**",
        "**/vscode-extension/**",
        "**/.git/**",
        ".vscode",
        "/home/nscott/.config/Code/User/settings.json",
        "typings",
        "/home/nscott/workspace/asldev/aslcore/gtest/googletest/",
        "/opt/qt4-asl/4.7.4/x64/include/**/",
        "/home/nscott/workspace/asldev/aslcore/jcop/**",
        "/opt/qt4-asl/4.7.4/x64/include/QtCore/*.h",
       "/home/nscott/workspace/asldev/aslcore/emcs/asl-emcs-vipet-gui/**",
    ],
```
If I open a file in last path I still get spellings shown.

I have tried nothing on the end of the path, as well as '*' and '**'

**Comment by Jason3S** [comment]
I'll take a look. It might not match against full path names.
Watch out for the trailing `,`. VSCode won't correctly parse the `.json` file.

Did you try:
`"**/home/nscott/workspace/asldev/aslcore/emcs/asl-emcs-vipet-gui/**"`

**Comment by Gruntfuggly** [comment]
Adding ** at the front didn't make any difference. 

I removed the trailing ',' after posting the settings. Thanks for the warning though  8-)

**Comment by mgabeler-lee-6rs** [comment]
I'm having a similar(?) issue, but mine is even simpler -- the default `"**/node_modules/**"` doesn't work -- I get spelling warnings about text in `.d.ts` files under `node_modules` folders.

If it's relevant, I use multi-folder workspaces for everything -- I've seen some other extensions have file matching issues in this case is why I point it out

**Comment by jwikman** [comment]
I'm having the same issue.

I'm using a multi folder workspace and I want to exclude one of the folders in the workspace - but it just don't work.

It works if I set the filter to individual files in the same folder...

**Comment by jwikman** [comment]
I've attached a repro project:
[cSpellMultiFolder.zip](https://github.com/streetsidesoftware/vscode-spell-checker/files/4769754/cSpellMultiFolder.zip)


This sample gets problems on
- \Folder1\file1.txt
  - OK, since it should not be ignored
- \Folder2\file2.txt
  - Not OK, any of these should find this:
    - "\*\*/Folder2/**",
    - "Folder2/**",
    - "/Folder2/**",

And ignores problems in 
- Folder2\subfolder1\fileinsubolder1.txt
  - Ok because of "\*\*/subfolder1/**"


So it seems as if the matching ignores the root folder when using multi folder workspace.

**Comment by jwikman** [comment]
Btw, I'm running on Windows - don't know if that's related though.

**Comment by jwikman** [comment]
Thanks @Jason3S!

`"${workspaceFolder:Folder2}/**"` worked like a charm, case closed. 😀

**Comment by lonix1** [comment]
@Jason3S I've seen multiple examples of ignore paths, and unsure which is the currently supported format?

e.g.
````json
"**/package-lock.json",
"**/node_modules/**",
"**/vscode-extension/**",
"**/.git/objects/**",
".vscode",
".vscode-insiders",
"**/SomeDirectory/**",
````

vs

````json
"package-lock.json",
"node_modules",
"vscode-extension",
".git/objects",
".vscode",
".vscode-insiders",
"SomeDirectory",
````
