### ISSUE TITLE
Spelling errors no longer shown in problems pane

### ISSUE THREAD

**Issue by Markus537** [streetsidesoftware/vscode-spell-checker#3814]
Type: <b>Bug</b>

Code Spell checker no longer shows spelling errors in the problems pane, only in the spell checker pane, although "cSpell.diagnosticLevel" is set to "Information".

Steps to reproduce:
* Create some new file in e.g. Python, save it as test.py.
* Add a comment with a spelling error.

Expected result:
* Spelling error should show in problems pane.

Actual result:
* Spelling error in only shown in spell checker pane.

Extension version: 4.0.19
VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Linux x64 4.18.0-553.27.1.el8_10.x86_64
Modes:

**Comment by Jason3S** [comment]
The `cSpell.diagnosticLevel` setting gives a link, but the implications are not clear.

<img width="917" alt="image" src="https://github.com/user-attachments/assets/2d670fc3-cc06-40a0-bb10-76715a0b8c4f">

<img width="991" alt="image" src="https://github.com/user-attachments/assets/afb9484f-4eef-47fc-93b2-b53435e3b79f">

Please set `cSpell.useCustomDecorations` to `false`.

I have updated the description to make it a bit clearer.

<img width="938" alt="image" src="https://github.com/user-attachments/assets/e2655c31-360c-4bd1-bb20-c7ad7acbbaeb">

**Comment by Markus537** [comment]
Can confirm that this resolves the issue, thanks. It also appears to be the cause for #3809, after setting `cSpell.useCustomDecorations` to `false` the squiggly lines are back to their former appearance.

Maybe it would be a good idea to set `cSpell.useCustomDecorations` to `false` by default?
