### ISSUE TITLE
Spell checking is NOT enabled for this file. SSH remote linux machine Jupyter notebook

### ISSUE THREAD

**Issue by atticusmatticus** [streetsidesoftware/vscode-spell-checker#3819]
Spell checking is not working in only one situation: on my remote linux machine when using a Jupyter notebook. 

In all other situations with the same synced account / workspace / User settings / etc. the spell checking is working as expected. For example, I am working on the remote machine via my MacBook where if I open the same Jupyter project locally the spell checking works. If I open a normal `file_name.py` python file locally or remotely that spell checking also works as expected. However, when working on any Jupyter notebook on my remote machine the spell checker says it is not enabled.

I have tried clicking the `{}` icon in my status bar and enabling the spell checking for the file type explicitly, (both python and markdown file types), with no effect.

**Comment by Jason3S** [comment]
I think it is connected to #3787

**Comment by atticusmatticus** [comment]
#3826 seems to have fixed the issue for me.

Thank you!
