### ISSUE TITLE
Too many updates in too short a time

### ISSUE THREAD

**Issue by Toddler-Boy** [streetsidesoftware/vscode-spell-checker#3830]
Every time I open VS code, it shows me an update badge for this extension. This badge disappears after I allow it to restart the extension, but a couple of hours later, it comes right back.

Does this get updated multiple times a day? Do you maybe use the main branch for active development instead of having a development branch and only merging into the main when something is complete? This is very distracting and unnecessary. I've uninstalled the extension altogether to get rid of it. That's how annoying it is.

**Comment by jverce** [comment]
These releases seem to be triggered by every change that's pushed to the `main` branch.
Perhaps that could be changed so that trivial/non-functional updates don't produce a new release/version?

**Comment by Jason3S** [comment]
Thank you for the feedback.

Releases are deliberate and address real issues. 

I realize that it can be annoying to get frequent updates.

The upgrade from v3 to v4 was substantial. Even though v4 had been available as a `prerelease` for many month, some general usability issues didn't surface until the `prerelease` flag had been removed. To unblock users and and reduce the number of new "me too" issues coming in, it was decided to releases the fixes as they were available.

In general, most changes are released behind a `prerelease` flag. I don't expect there to be many new updates to the `release` version in the coming weeks.
