### ISSUE TITLE
[Bug]: unable to activate cspell in VS Code when using workspace from UNC path and / or running VS Code portable from E: USB drive

### ISSUE THREAD

**Issue by zabka1971** [streetsidesoftware/vscode-spell-checker#3840]
### Kind of Issue

Crash / Error

### Tool or Library

cspell

### Version

4.0.21

### Supporting Library

Other

### OS

Windows

### OS Version

11 24H2

### Description

When running portable VS Code from USB drive mapped as E: and open workspace located in UNC server path (not mapped as WIndows drive), spell check is not enabled and there is no possibility to enable it.
When i map UNC server path as Windows Drive, i am able use spell check anyway error about user setting file (see below) remains.

### Steps to Reproduce

1. run VS Code from USB flash drive mapped as E:
2. open workspace located on UNC path e.g. \\zabkanas\software\develop\docs\zabka1971.github.io\
3. open file in editor (e.g. MD file)
4. put mouse on Spell widget - file type Markdown is not enable
5. try to enable spell check for MD files using Spell Checker File Information, select to put it into workspace setting
6. corresponding setting is written into workspace settings.json
7. spell checking is still not enabled

### Expected Behavior

After enabling of spell check for filetype, spell check will be enabled

### Additional Information

Code Spell Checker Output:
![Screenshot 2024-11-23 153519](https://github.com/user-attachments/assets/8255de77-6cc3-484c-8de8-3fdfae0f9f1b)
Code Spell Checker Server Output:
![Screenshot 2024-11-23 153856](https://github.com/user-attachments/assets/0dcb30ab-f49b-4904-9715-3b4f490def7e)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Jason3S** [comment]
@zabka1971,

Thank you. It seems to be an issue with UNC files. It is having trouble resolving the path into a URL.

It might be a while before I can fix this since I won't have easy access to a Windows machine for the new few weeks.

**Comment by zabka1971** [comment]
Thank you for quick response. It would be great to have it working one day, indeed it is not urgent as workaround exists.
