### ISSUE TITLE
Considering to support custom scheme

### ISSUE THREAD

**Issue by Sneezry** [streetsidesoftware/vscode-spell-checker#385]
Currently, Code Spell Checker only supports `file` and `untitled` scheme:

https://github.com/streetsidesoftware/vscode-spell-checker/blob/384637e696e7667ef3c58098572521c4c9a82e08/packages/client/src/util/uriHelper.ts#L4

This design makes sense in most scenario.

Recently, I made an extension for DEV Community (https://dev.to/sneezry/write-posts-in-dev-community-using-visual-studio-code-2l4o), which uses custom scheme (`devto:`). I noticed some users suggest this extension (Code Spell Checker) to use together, however, I found this extension cannot work together with my extension.

Could you please add custom scheme support? Thanks very much.

**Comment by Jason3S** [comment]
It is already possible to add a new schema in VS Code preferences. See image.

![image](https://user-images.githubusercontent.com/3740137/67384494-890e7580-f591-11e9-95b7-b565435bcdfc.png)

Open preferences and search for `allowed schemas`. Add new item: `devto`.

**Comment by Jason3S** [comment]
You will need to restart VS Code for it to take effect.

**Comment by Sneezry** [comment]
Wow, I have confirmed that works! Thanks.
