### ISSUE TITLE
[Bug]: Long URLs disable spell checking

### ISSUE THREAD

**Issue by mhetacc** [streetsidesoftware/vscode-spell-checker#3859]
Long URLs (eg: [URL example](https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/29e25571-eb24-4381-9a2d-bde0ba52be2e/df3uxma-90078aec-f043-423b-8adf-68b0db323607.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzI5ZTI1NTcxLWViMjQtNDM4MS05YTJkLWJkZTBiYTUyYmUyZVwvZGYzdXhtYS05MDA3OGFlYy1mMDQzLTQyM2ItOGFkZi02OGIwZGIzMjM2MDcucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.Pap7EkIxDlgZ1dFLyEK_MOlPIQGjvJVm5T8adKtnAn0)) make spell checker unable to recognize spell errors in the file.
Problem persists for all files with the same name until extension is reinstalled.
To clarify: if in file _report.md_ there is the above mentioned link, spell checker stops working on _report.md_, and if we delete said file and re-create it (without copying the URL) it still does not recognize spell mistakes.

**Comment by Jason3S** [comment]
The updated version will do a better job of notifying you that a file is blocked.

**Comment by Jason3S** [comment]
Code was also added to ignore urls and tries to ignore random strings.
