### ISSUE TITLE
cSpell not working

### ISSUE THREAD

**Issue by DarkLite1** [streetsidesoftware/vscode-spell-checker#386]
After installing the extension and restarting `vscode-insiders` it seems I can't enable the `cSpell` extension for spell checking in the bottom taskbar: 

![image](https://user-images.githubusercontent.com/10828570/66376372-cd095400-e9af-11e9-8db9-2736c4d24cf8.png)

I have no `cSpell.json` file in my `.vscode` folder. When clicking on the icon to try to enable it nothing happens. I tried to use the `command palette` to `Enabell spell checking for workspaces` but that doesn't do anything.

![image](https://user-images.githubusercontent.com/10828570/66376493-16f23a00-e9b0-11e9-92ed-5a926504693f.png)

The config says `File enabled` and the correct language is indicated `PowerShell`. 

![image](https://user-images.githubusercontent.com/10828570/66376574-4c972300-e9b0-11e9-848c-e692d714bbb9.png)

What should be done do enable the spell checking?

**Comment by Jason3S** [comment]
Sorry for taking so long to respond.
Search in VS Code preferences for `spell enable`. It is most likely disabled at the `User` level.

![image](https://user-images.githubusercontent.com/3740137/67385127-c293b080-f592-11e9-9f0d-b990a6ab02d5.png)

**Comment by DarkLite1** [comment]
Thank you Jason, it was indeed dsiabled on the workspace level and enabled on user level. I also checked the box on workspace level, restarted vscode-insders and it is fixed now. Thanks for the help.
