### ISSUE TITLE
`Invalid file change` console log errors

### ISSUE THREAD

**Issue by RedCMD** [streetsidesoftware/vscode-spell-checker#3861]
My console is being spammed with `Invalid file change` errors

`Invalid file change: '/e:/VSCode-win32-x64/data/user-data/User/globalStorage/streetsidesoftware.code-spell-checker/eventLog.json' !== '/E:/VSCode-win32-x64/data/user-data/User/globalStorage/streetsidesoftware.code-spell-checker/eventLog.json'`

![image](https://github.com/user-attachments/assets/4deded97-eef8-4c43-8768-0a306f9b52f7)

```json
"cSpell.language": "en,en-gb",
"cSpell.numSuggestions": 3,
"cSpell.ignorePaths": [
	"package-lock.json",
	"node_modules",
	".git/{info,lfs,logs,refs,objects}/**",
	".git/{index,*refs,*HEAD}",
	".vscode",
	".vscode-insiders",
	".vscode-test-web",
	"**/extensions",
	"UNICODE_PROPERTIES.ts",
	"unicode_property_data.ts",
	"**/vscode-main"
],
"cSpell.userWords": [
	"abdefhnorstuvwxyz",
]
```

**Comment by Jason3S** [comment]
Sorry about that. I know how annoying that can be when other extensions span the console. 

A PR is welcome. It is a single line change. Even possible from the GitHub Web UI. 

In any case. I'll make sure it is fixed soon.

**Comment by caaat1** [comment]
Sorry, I got annoyed by the similar output persisting at a debug session on the VS code debug console.

**Comment by Jason3S** [comment]
Please try 4.0.23
