### ISSUE TITLE
"Commerce" and "GDPR" is detected incorrectly as wrong

### ISSUE THREAD

**Issue by i5heu** [streetsidesoftware/vscode-spell-checker#389]
- Commerce
- GDPR (https://eugdpr.org/)

**Comment by Jason3S** [comment]
Thank you. `Commerce` is in the dictionary both English dictionaries. `GDPR` is not currently in any of the dictionaries. I'll add GDPR in the next build.

**Comment by i5heu** [comment]
Thank you for your hard Work <3

**Comment by cjwijtmans** [comment]
Words that are capitalized in the middle of sentences should not be spell checked at all. These are names or abbreviations not dictionary words.

**Comment by Jason3S** [comment]
Closing as stale.
