### ISSUE TITLE
add a new line to the end of the file when reformatting cspell.json

### ISSUE THREAD

**Issue by thorn0** [streetsidesoftware/vscode-spell-checker#391]
Please do so in order to not conflict with code formatters like Prettier, which always adds this new line.  

Ideally, this extension should format `cspell.json` the same way VS Code would do if the user pressed Alt+Shift+F (so if the Prettier extension is enabled, it'll be used).

**Comment by fisker** [comment]
Has this been fixed? It seems adding trailing new line now.

**Comment by Jason3S** [comment]
This should be fixed: See #1316.
