### ISSUE TITLE
Word `blocks` is misspell for description of setting cSpell.checkLimit

### ISSUE THREAD

**Issue by msftrncs** [streetsidesoftware/vscode-spell-checker#3937]
The word `blocks` is misspelled as `bocks` in the setting description for `cSpell.checkLimit`

![image](https://github.com/user-attachments/assets/e65c86b2-4484-46ce-a2e2-ef5d9cb879fb)

Version:
```
Identifier: streetsidesoftware.code-spell-checker
Version: 4.0.21
Last Updated : 2024-11-21, 10:10:35
```

**Comment by Jason3S** [comment]
@msftrncs,

Thank you.
