### ISSUE TITLE
how to set Chinese checker

### ISSUE THREAD

**Issue by ColorFuzzy** [streetsidesoftware/vscode-spell-checker#402]
I tried `spellright.language` with `cn, zh, zh-cn, zh-chs` , they all didn't work.

- `"spellright.language": ["en", "zh"]` doesn't work
- vscode 1.40.0
- windows 10 insider preview weekly

**Comment by Jason3S** [comment]
The spell checker does not support Chinese. Since this spell checker is `word` based and not context based, it is not possible to spell check Chinese.

Thank you for asking.
