### ISSUE TITLE
Disable auto complete of words?

### ISSUE THREAD

**Issue by sprite-1** [streetsidesoftware/vscode-spell-checker#404]
If I've written a long document, the auto completion kicks in and it suggests previous words I've typed. This should normally not be a problem but pressing Enter selects the suggestion so if say I type `three` + the Enter key for a new line and it's suggesting `there`, my word gets replaced by the suggestion

**Comment by Jason3S** [comment]
I guess you figured out this is a VS Code issue, not the spell checker.

**Comment by sprite-1** [comment]
@Jason3S yeah, I didn't see any option to delete the issue so I just closed it
