### ISSUE TITLE
Add support for remote dictionary with right click "add to <dict>" option.

### ISSUE THREAD

**Issue by schperplata** [streetsidesoftware/vscode-spell-checker#409]
This feature request is already briliantly written on your marketplace Q&A site (by someone, but I assume this is a better place to move it forward:

> If I have a dictionary that is not in my .vscode folder, can the suggestion add new words to that dictionary? Currently, the tool only adds new words to the settings.json (user) or the cspell.json (workspace) file in my .vscode folder. **Ideally, I would like to have my settings.json point to a dictionary which is in its own git repo. Then I can share this dictionary between vs workspaces/projects. And when I add new words from vs code I can commit my dictionary to share with my team.**
By matt.ruhland18 7/23/2019

Last few sentences explain exactly what I need: 
* custom dictionary that can be specified by path (which is not in the workspace folder)
* option to add/remove words to only this dictionary (and not creating `cSpell` settings in `settings.json` and `.code-workspace`)

**Comment by janosh** [comment]
I think this issue can be closed. [Custom dictionaries landed in v1.9](https://github.com/streetsidesoftware/vscode-spell-checker/blob/master/CHANGELOG.md#190-alpha0-2020-05-09). 🎉
