### ISSUE TITLE
Specifying languageId for a certain kind of file

### ISSUE THREAD

**Issue by nip3o** [streetsidesoftware/vscode-spell-checker#411]
We have some Django templates in our project, which has a custom file extension to separate them from regular HTML files. I want these to use words from both the Django and the HTML dictionaries, which I have accomplished for the CLI by adding the config below to our `cspell.json`.

    "overrides": [
        {
            "filename": "**/*.html.dj",
            "languageId": "html"
        },
    ]

However, this does not get picked up when using the vscode plugin. Is there a better way of doing this?

**Comment by Jason3S** [comment]
The overrides are not currently working for VS Code.

It is possible to take another approach.
I assume VS Code detects Django files as something like `django`.

You can do the following:
1. Open a Django template
2. `F1` `Enable Spell Checking Document Language` -- this should add `django` to the set of documents to be checked.
3. Define the dictionaries to be used:
```
    "cSpell.languageSettings": [
        {
            "languageId": "django",
            "dictionaries": ["html", "fonts", "css"] 
        }
    ]
```
or in the cspell.json
```
    "languageSettings": [
        {
            "languageId": "django",
            "dictionaries": ["html", "fonts", "css"] 
        }
    ]
```

4. You might need to restart VS Code.

**Comment by Jason3S** [comment]
@nip3o what OS are you on? I just checked. Overrides should be working.

**Comment by Jason3S** [comment]
@nip3o I just realized what might be happening. VS Code didn't know what type of file it was. By default, VS Codes does not know what a `*.html.dj` file is.

In the lower right of VS Code, you might see:
![image](https://user-images.githubusercontent.com/3740137/72891382-674d9780-3d14-11ea-914b-a78d8acfe14b.png)

If you tell VS Code to treat a `*.html.dj` file as an `html` file, then the spell checker will do the right thing.

If you click on `Plain Text`, VS Code will give you the option to assign a file type.

If you also want to add other dictionaries for those files the overrides will work:
``` json
"overrides": [
    {
        "filename": "**/*.html.dj",
        "languageId": "html",
        "dictionaries": ["html", "python"]
    },
]
```

**Comment by nip3o** [comment]
@Jason3S Thanks for your input! It seems like the cspell plugin always uses the language mode selected in VSCode, regardless of the "overrides" setting. In this case I had `django-html` as language mode set in VSCode, which results in a slightly different set of dictionaries compared to using `html`. I guess the correct thing would be to use `django-html` as mode for these files also in the overrides (which are picked up when we run the CLI).

Also `django-html` should probably have all dictionaries as `html` has by default, but I'll dig deeper into that and open a separate issue/MR if relevant.
