### ISSUE TITLE
How to specify a custom path to cspell.json?

### ISSUE THREAD

**Issue by nip3o** [streetsidesoftware/vscode-spell-checker#412]
I'm currently building a CI checker that runs cspell on our project. The CLI version of cspell is installed with yarn. At the same time I would like to run cspell using the vscode plugin. It seems like the plugin now installs its own version of cspell and runs as the server.

One issue with this is that we might accidentally use different versions of cspell in the two checks. Another issue is when using imports in the `cspell.json` file (like this `"import": ["node_modules/cspell-dict-sv/cspell-ext.json"],`). In our case that works fine when running the CLI, but not for the vscode plugin as it is run from another installation of cspell. Since `cspell.json` is checked into git we cannot use an absolute path either.

Would it be technically feasible to allow specifying a path to the cspell installation to use with the plugin?

**Comment by Jason3S** [comment]
Good suggestion. I would have to think about how to do that.

**Comment by Jason3S** [comment]
@nip3o 
Since the extensions does not know where VS Code stores it settings, it is not possible to use relative paths in VS Code settings. (Future enhancement is to allow for [${workspaceFolder}](https://code.visualstudio.com/docs/editor/variables-reference#_variables-scoped-per-workspace-folder) substitution.

But, a `cspell.json` file can have paths relative to `cspell.json` location. Those will get correctly resolved by the Extension.

**Comment by nip3o** [comment]
Ah, it seems like imports are relative to `cspell.json` if they are imported as `./node_modules/somemodule`, but not if they are imported as `node_modules/somemodule` (which I had in my config file). Maybe we could change that, or clarify it somehow?

**Comment by Jason3S** [comment]
Update:

From VS Code Settings (single folder opened):
``` json
"cSpell.import": [ 
  "${workspaceFolder}/relative/path/to/cspell.json"
]
```

VS Code with multiple folders called `client`, `server`, `common`
``` json
"cSpell.import": [ 
  "${workspaceFolder:common}/relative/path/to/cspell.json"
]
```

From `cspell.json`, relative files should start with `.`
``` json
"import": [
  "./node_modules/company_config/cspell.json"
]
```
