### ISSUE TITLE
Ignore words (through regex) by case?

### ISSUE THREAD

**Issue by REMjn832** [streetsidesoftware/vscode-spell-checker#419]
I feel stupid, but I cant figure out how to get the "Ignore Reg Exp List" to ignore words that are in all caps. It seems to be case-insensitive, so when I put rules in, it applies to all words, regardless of case. I am trying to ignore words like "HSTS, or XCOORD, or CTLP" or any acronym for example. 

Here are a few I have tried with no success:
`\b[A-Z]+\b` - seems to disable all spell checking (applies to all case)
`[A-Z\s]+` - same as above.

its a great extension, just stumped by this and I would appreciate the help. Thanks.

**Comment by Jason3S** [comment]
If you try adding the `/` at the ends, it should work.

![image](https://user-images.githubusercontent.com/3740137/73698092-7ce19a80-46e0-11ea-9bbc-6c421db30a7b.png)

If you are editing the `.json` file yourself, remember to escape the `\b`:

```
"/\\b[A-Z]+\\b/"
```

In-document:
```
// cspell:ignoreRegExp /\b[A-Z]+\b/
```
