### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by peanutsbrat** [streetsidesoftware/vscode-spell-checker#421]
- Issue Type: `Bug`
- Extension Name: `code-spell-checker`
- Extension Version: `1.7.22`
- OS Version: `Windows_NT ia32 10.0.18363`
- VSCode version: `1.41.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by Jason3S** [comment]
@peanutsbrat What was the issue? Would you please provide some more information?

**Comment by Jason3S** [comment]
Closed due to no response and inability to reproduce.
