### ISSUE TITLE
How to increase the number of misspellings reported

### ISSUE THREAD

**Issue by mantier** [streetsidesoftware/vscode-spell-checker#422]
I am having a large tex file with a lot of uncommon words. Somewhere around half of the document, spellchecking stops. As soon as I add untypical words to the local dictionary, the "next" spelling error is being detected.

Windows 10 Enterprise 1809
Code Spell Checker 1.7.22 with no altered settings
VSCode  1.42.0

**Comment by Jason3S** [comment]
There are a couple of settings that limit the number of issues listed:

`Max Number of Problem` and `Max Duplicate Problems`

![image](https://user-images.githubusercontent.com/3740137/74081354-5a3be280-4a4e-11ea-8213-0b1a40d05c0b.png)

**Comment by mantier** [comment]
Thanks a lot, that was it. 

I'd suggest to reconsider the standard setting. It took me some time until I understood the problem and it would probably save some other users' time or prevent them even giving up on the extension if they didn't run into the same problem. Actually, most of the time I was thinking the extension wasn't working at all since I was trying it out in the middle of my ~1000 lines document. 

IMHO the best solution would be to raise a message to the user if the max number of problems is hit without reaching EOF.

**Comment by Jason3S** [comment]
Thank you for the feedback. I'm going to close this issue for now.
