### ISSUE TITLE
Q: Markdown

### ISSUE THREAD

**Issue by Denis-net** [streetsidesoftware/vscode-spell-checker#423]
Hey Street Side Software team ! 😊👋🏼
Congratulations for the awesome Extension ! 👏🏼
It helps me a lot !

I have a question: 
With this snippet

``` markdown
commands: **c**ompile
```
The extension can't recognize "ompile"
In this situation what is the best method ?
Add to folder workspace ?
Could it be possible on your side to remove all the symbols between words before doing the checks?
Because "ompile" is not a word, but "**c**ompile" is.
If it's too hard i can safely add to ws folder 👍🏼

Thanks in advance

**Comment by Jason3S** [comment]
The best I can come up with is to add the following to the bottom of your document:

```
<!---
    cSpell:ignore ompile
-->
```

**Comment by Denis-net** [comment]
It worked ! 🎉🎊
Thank you.
