### ISSUE TITLE
How to enable spell checking of .gql (GraphQL) files

### ISSUE THREAD

**Issue by murthymuddu** [streetsidesoftware/vscode-spell-checker#442]
I am working on some .gql files. Identified that for gql files spell checker not working.

**Comment by Jason3S** [comment]
There are several ways to do this:

1. Open a GraphQL file and then `F1` `Enable Spell Checking Document Language`
  ![image](https://user-images.githubusercontent.com/3740137/75225927-c2f3c080-57ab-11ea-8387-a24d257f7675.png)
1. Use VS Code Settings, cspell Enable Filetypes
  ![image](https://user-images.githubusercontent.com/3740137/75226115-149c4b00-57ac-11ea-85d8-c7d889e2570d.png)
1. Use the Spell Checker Preferences screen:
  ![image](https://user-images.githubusercontent.com/3740137/75226384-942a1a00-57ac-11ea-96dd-85ea1a3f1b5c.png)
  ![image](https://user-images.githubusercontent.com/3740137/75226507-c0de3180-57ac-11ea-889a-7b4ddd1f98c5.png)
