### ISSUE TITLE
Recipe terminated with fatal error: spawn latexmk ENOENT.

### ISSUE THREAD

**Issue by yannickkirschen** [streetsidesoftware/vscode-spell-checker#445]
Hey guys,

when trying to view the LaTeX PDF file in VS-Code, I get this error. Does anyone of you know what I did wrong?

Regards

Yannick

**Comment by Jason3S** [comment]
This ins't an error the spell checker would generate.
It looks like another VS Code extension is trying to start `latexmk` but it is not able to find it.
