### ISSUE TITLE
PHP error when using quickfix to fix spelling

### ISSUE THREAD

**Issue by alystair** [streetsidesoftware/vscode-spell-checker#446]
`[Error - 12:18:19 AM] Request textDocument/rename failed.
  Message: Only a variable, a function or a class can be renamed. Other changes might corrupt your code.
  Code: 102`

It worked just fine tho'. For reference this was an HTML file with embedded PHP (so .PHP)

**Comment by Jason3S** [comment]
Thank you.  Looks like to PHP rename function is too sensitive. Too bad they made that choice.

There is a workaround:
You can turn it off in VS Code settings. Search for `spell rename`
![image](https://user-images.githubusercontent.com/3740137/76678435-3f720600-65d8-11ea-9976-8ccfefd7d447.png)

**Comment by alystair** [comment]
Thanks, sounds good.
