### ISSUE TITLE
How to recognize errors in words with 3 characters?

### ISSUE THREAD

**Issue by leosdad** [streetsidesoftware/vscode-spell-checker#450]
Hi,

I wonder if there is some way to recognize errors in words with 3 characters. Is there some setting to do that?

Thanks in advance,

**Comment by Jason3S** [comment]
![image](https://user-images.githubusercontent.com/3740137/77819617-7702a700-70dc-11ea-944a-538c10768730.png)

Open VS Code preferences and search for `spell min word length`.

From there you can set it to a different value.

**Comment by leosdad** [comment]
Somehow I missed that.... Maybe because the doc says 'Only words longer than 3 characters are checked'. Didn't read further down, sorry.

Thanks a lot for the quick answer!

**Comment by Jason3S** [comment]
You welcome. I'm going to close this issue. If there is a problem, please open a new issue.
