### ISSUE TITLE
Pug2 files

### ISSUE THREAD

**Issue by BananaAcid** [streetsidesoftware/vscode-spell-checker#459]
It does a spellcheck on URLs and class names and does not like the html attributes `defer`, `integrity` 

```
command                             error highlight
PUG:

a.jump(name="aboutus")              jump
section.aboutus somehting           aboutus
<svg class="divider" ...            divider
img.logo(src="...")                 logo
script(src="//cdnjs.cloudflare.com/ajax/libs/Swiper/4.5.1/js/swiper ...", integrity="...", crossorigin="..", defer)
               '-> highlights:     cdnjs   libs   Swiper  swiper  integrity crossorigin  defer

LESS:
 &.hero                             hero
.logo                               logo
//pick it up, if .hero is shown     pick   hero   shown
```

**Comment by Jason3S** [comment]
Thank you for the feedback. It seems like there are more things going on here. Do you have English turned off? 

I agree that the URL should not be checked. But most of the other words are in the dictionaries.

**Comment by BananaAcid** [comment]
Hi, english is on. The textblocks are somewhat fine (in the `pugjs` files). Seems like class names (`a.jump` -> a-tag + jump-class) get highlighted in `.pug` and `.less` files most of the time. And attributes like defer/integrity.

**Comment by Jason3S** [comment]
Would it be possible to upload a sample file?

Are you using a `cspell.json` file or are the settings stored in VS Code?

Would you be able to upload your settings?

**Comment by BananaAcid** [comment]
Every one of my students had the same problem. Should be simple to replicate. I removed everything. Sorry.

**Comment by Jason3S** [comment]
I am not able to replicate it. So it is not simple to replicate. There is something in `.vscode/settings.json` or `cspell.json` that is changing how the spell checker works. I am happy to help, but so far I do not have enough information to understand the issue.
