### ISSUE TITLE
Request ability to check shell scripts

### ISSUE THREAD

**Issue by unacceptable** [streetsidesoftware/vscode-spell-checker#462]
It would be nice if I could catch my bad spelling in .sh files.

**Comment by Jason3S** [comment]
You have some options:
1. You can use the command `F1` `Enable Spell Checking Document Language`
1. VS  Code settings: 
  ![image](https://user-images.githubusercontent.com/3740137/79143239-2ae28280-7dbd-11ea-8085-b312184df4e0.png)
