### ISSUE TITLE
Workspace dictionary is not considered for spellchecking

### ISSUE THREAD

**Issue by mhaaz** [streetsidesoftware/vscode-spell-checker#466]
**Reproduction steps**

1. Have a multi-root workspace open.
1. In a spellchecked file, type something that is not a word. cSpell underlines this a word that is not in the dictionary.
1. Use the command "Add to workspace dictionary"
    - Looking at the workspace definition file, the adding is working fine; the word is now under the cSpell section of the workspace settings
1. **The word is still being underlined as non-existent.** It appears the extension is not pulling from the wordlist in the multi-root workspace settings when spellchecking.

**Comment by samtsai** [comment]
This is very similar to #374

**Comment by Jason3S** [comment]
@samtsai and @mhaaz Thank you for the feedback.

The challenge here is that VS Codes settings at the Workspace level are overwritten at the Folder level. This is how VS Code works.

Please check the local folder settings to make sure it isn't overwriting the workspace setting.

**Comment by samtsai** [comment]
> @samtsai and @mhaaz Thank you for the feedback.
> 
> The challenge here is that VS Codes settings at the Workspace level are overwritten at the Folder level. This is how VS Code works.
> 
> Please check the local folder settings to make sure it isn't overwriting the workspace setting.

So I've just tried checking if I had a local `.vscode` folder and I didn't. I just have a single folder of my project as part of a workspace.  But still I only see options to add words to User or Folder.

**Comment by mhaaz** [comment]
I have also since tried what you suggested @Jason3S , with a similar result. Meaning, even though not a single folder in my multi-root workspace contains a `.vscode` folder, any words I add into the workspace's settings (via the option which does appear for me) are still not considered by cSpell when spellchecking.

Any other info I could provide to help with analyzing?

**Comment by Jason3S** [comment]
Thank you. I'll take a deeper look.

**Comment by Jason3S** [comment]
I have been investigating. It seems to be acting strange.

**Comment by niem94** [comment]
@Jason3S any update?

**Comment by Jason3S** [comment]
With V2, adding a word to a dictionary is a bit more specific. It will give the option to add it to all the available dictionaries.

I'm closing this for now. If things still do not work as expected, please open a new issue.
