### ISSUE TITLE
Support for GistPad (and other virtual filesystems)

### ISSUE THREAD

**Issue by franklin-ross** [streetsidesoftware/vscode-spell-checker#468]
I recently moved a markdown file from local disk into a Git gist, and use the GistPad extension to edit it in VSCode. Spell checking doesn't seem to work now that it's a gist, though the file has Markdown syntax highlighting from VSCode.

I assume it's related to this [GistPad issue](https://github.com/vsls-contrib/gistpad/issues/30), which seems to be caused by other extensions (like spell checker) not supporting virtual file systems. It'd be great if it did!

**Comment by lostintangent** [comment]
Would it be as simple as adding the “gist”
scheme to these lists: [client](https://github.com/streetsidesoftware/vscode-spell-checker/blob/master/packages/client/src/util/uriHelper.ts#L4), [server]().

**Comment by Jason3S** [comment]
@lostintangent and @franklin-ross the extension allows you to add file schemas:

Please take a look at [#326](https://github.com/streetsidesoftware/vscode-spell-checker/issues/326#issuecomment-485069414)

**Comment by franklin-ross** [comment]
Ahh, that's handy, let me try.

**Comment by franklin-ross** [comment]
That did work. I suppose that's good enough, although I would not have had the faintest idea that I needed to add that without asking. Are you opposed to just adding some like this to the default list? Unless it's likely to cause an issue?

**Comment by Jason3S** [comment]
I'm fine with adding `gist` to the default list.
I wish there was a better way to discover how to support this type of thing.
The problem is that other extensions have hidden files they work with, if the spell checker allowed ALL schemas, then the hidden files get checked and reported on too. Some of them are very large and change in the background all the time. This leads to poor performance.

**Comment by franklin-ross** [comment]
Yeah, that makes sense. Thanks to both of you for the extremely prompt help. At least it seems like an easy enough thing to just add specific cases to the default list as they come up.

**Comment by franklin-ross** [comment]
In the interests of posterity, I'm happy to change the name of this issue (or for someone else to change it) to make it a bit more general if that would help other people with similar issues? It's probably on you two to suggest the keywords though, as I only have a vague idea of what's actually going on here ;-)

**Comment by lostintangent** [comment]
@Jason3S Are the two locations I mentioned above the only spots that I’d need to add the “gist” scheme too? If so, I’d be happy to send a quick PR. I’d love to have gists supported out-of-the-box for folks if possible 👍

**Comment by Jason3S** [comment]
@lostintangent Thank you! 

The important one is in the client and [package.json](https://github.com/streetsidesoftware/vscode-spell-checker/blob/master/packages/client/package.json#L435). The server one is there in case the value isn't passed in from the client.

Would you please add `sftp` in addition to `gist`?

Thank you.
