### ISSUE TITLE
problems loading reference 

### ISSUE THREAD

**Issue by fx2013013** [streetsidesoftware/vscode-spell-checker#472]
When I was editing setting.json, the following error occurred. This is not a spelling error. I did not find relevant information in issues and settings, and I hope to find a solution (it appears in the Warnings and Errors below, does not affect the use, but I am very uncomfortable)

problems loading reference 'https://raw.githubu software/cspell/cspell96404.0.53/cspellschema.json#/definitions/ DictionaryDefinition'：Unable to load schema from 'https://raw.githubusercontent.co cspell.schema.json'：getaddrinfo ENOENT  raw.githubusercontent.com.

**Comment by Jason3S** [comment]
It is trying to load the json-schema file from: https://raw.githubusercontent.com/streetsidesoftware/cspell/cspell%404.0.53/cspell.schema.json

Are you able to access that location?

**Comment by fx2013013** [comment]
can't

**Comment by Jason3S** [comment]
Is it blocked in your country or by your company?

**Comment by fx2013013** [comment]
yes,Are there other solutions, such as downloading files locally

**Comment by Jason3S** [comment]
I have attached the file

If you are using Nix type machine, you can change your etc/hosts to be able to serve it locally.

[cspell.schema.json.zip](https://github.com/streetsidesoftware/vscode-spell-checker/files/4521462/cspell.schema.json.zip)

It is too bad that VS Code doesn't allow `file:` reference to schemas.

**Comment by fx2013013** [comment]
Which folder should I put it in and what other settings should I put it in?

**Comment by Jason3S** [comment]
You can save the file locally and follow the instructions at: https://code.visualstudio.com/docs/languages/json#_json-schemas-and-settings
