### ISSUE TITLE
Disable spell checking at the comment lines

### ISSUE THREAD

**Issue by trancanh1102** [streetsidesoftware/vscode-spell-checker#478]
How can I disable spell checking in comment lines ?
Help me please

**Comment by Jason3S** [comment]
I'm not sure exactly what you are wanting here:
1. Do not check comments?
1. How to disable spell checking via a comment?

You can Turn Off Spell Checking of comments in the settings by adding `comments` and `CStyleComment` to `C Spell Ignore Reg Exp List`:

![image](https://user-images.githubusercontent.com/3740137/80857250-fa219a80-8c50-11ea-83b0-809d225db10d.png)

See also #116 

To be able to disable Spell Checking via comments:
[In Document Settings](https://github.com/streetsidesoftware/vscode-spell-checker/blob/master/packages/client/README.md#disable-checking)

**Comment by trancanh1102** [comment]
Thank you very much, it worked as expected xD

**Comment by theredwillow** [comment]
This issue should be closed. Looks like the requested feature already existed.
