### ISSUE TITLE
Spell checker checks files in vcs diff view despite being configured not to

### ISSUE THREAD

**Issue by khoitd1997** [streetsidesoftware/vscode-spell-checker#483]
User Config:
![image](https://user-images.githubusercontent.com/20428458/81436966-37899a80-911f-11ea-8bd1-48fd148c1369.png)

In VCS Diff view:

![image](https://user-images.githubusercontent.com/20428458/81437017-4c662e00-911f-11ea-9cf7-0f71f32f3b15.png)

Interestingly, it only checks the file on the right.

**Comment by Jason3S** [comment]
Please check the file type:
![image](https://user-images.githubusercontent.com/3740137/81472966-d08de380-91fb-11ea-8029-1096a88ad784.png)

In this case, it is `jsonc` and not `json`.

**Comment by khoitd1997** [comment]
Thank you for the fast response, adding ```jsonc``` works. Although one thing that still bugs me is that before adding ```jsonc```, it only checks the files when in diff mode:

![image](https://user-images.githubusercontent.com/20428458/81476657-eaadce80-91c7-11ea-9d7f-2398a169e4aa.png)

![image](https://user-images.githubusercontent.com/20428458/81476665-f7322700-91c7-11ea-91ea-49104162d86e.png)

**Comment by Jason3S** [comment]
That is because it is the user settings. If you were editing the workspace folder settings, it would have checked them.
