### ISSUE TITLE
Code Spell Checker still works after being uninstalled from vscode

### ISSUE THREAD

**Issue by oncicaradupopovici** [streetsidesoftware/vscode-spell-checker#486]
I have uninstalled the extension from vscode but the extension is still running.
Is there a way to do some manual cleanup?

**Comment by Jason3S** [comment]
The uninstall is totally controlled by VS Code. Manual steps should not be necessary.

It is possible that VS Code did not fully shutdown and restart. In that case you might need to kill and running processes.

It is also possible that another extension includes the Spell Checker.

#278 discusses where the extension might be found if you want to manually delete it.

**Comment by Jason3S** [comment]
Closing for now.
