### ISSUE TITLE
Spell checker does not work on .svelte extension

### ISSUE THREAD

**Issue by SubhajitS** [streetsidesoftware/vscode-spell-checker#502]
Spell Checker is unable to highlight mistakes in svelte file extension. Would like to have the same feature in it too.

**Comment by Jason3S** [comment]
To turn on spell checking for a Document Type:
1. Open a file of the type you want to check
1. `F1` `Enable Spell Checking Document Language`

![image](https://user-images.githubusercontent.com/3740137/84563539-9a90d180-ad5c-11ea-9b92-5c0abc0c85ce.png)
