### ISSUE TITLE
Ignore vscode-insiders global extensions library by default

### ISSUE THREAD

**Issue by baruchiro** [streetsidesoftware/vscode-spell-checker#505]
I see these warnings when I just installed the extension:

![image](https://user-images.githubusercontent.com/17686879/84589070-dac38300-ae34-11ea-9804-51adad1259a4.png)

VSCode version:
```
Version: 1.46.0-insider (system setup)
Commit: a5d1cc28bb5da32ec67e86cc50f84c67cc690321
Date: 2020-06-09T17:34:47.110Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19608
```

**Comment by Jason3S** [comment]
`node_modules` should be ignored by default.

**Comment by baruchiro** [comment]
> `node_modules` should be ignored by default.

Yeah, please see #506 , the problem is with `.vscode-insiders` folder.
