### ISSUE TITLE
Overheat while typing

### ISSUE THREAD

**Issue by FMuro** [streetsidesoftware/vscode-spell-checker#507]
I've been using this wonderful extension to type LaTeX in vscode. I usually do this while listening music with the headphones. Yesterday I was without them in a silent room and noticed the fan noise. I checked and, while typing the CPU reaches 95C. This doesn't happen with the extension disabled. I've also tested this happens with all other extensions disabled, so it really seems to be due to this extension. Please, let me know how I can help to improve this.

**Comment by Jason3S** [comment]
This is most likely due to an expensive regular expression.

**Comment by phawxby** [comment]
I recently had to uninstall the extension as the CPU load was getting so bad typing was beginning to lag. There is definitely some kind of performance issue with the extension.

<img width="199" alt="image" src="https://user-images.githubusercontent.com/1090602/201329600-3be421eb-3fab-4fa1-afc7-3f0de0ff122c.png">

You might be able to notice when I uninstalled it.

**Comment by Jason3S** [comment]
This issue is stale.
