### ISSUE TITLE
add command to refresh external dictionary contents

### ISSUE THREAD

**Issue by KyleMit** [streetsidesoftware/vscode-spell-checker#509]
I believe the dictionary is only read on load.  If the contents have changed, it would be helpful to manually kick off a refresh without having to close and re-open vscode.  It could be added as an available option in the command palette. 

For example, changes to `words.txt` in the following dictionary:

```
"cSpell.dictionaryDefinitions": [
  { "name": "words", "path": "~/AppData/Roaming/Code/User/words.txt"},
],
```

I suppose any dictionaries could also attach a watcher to the file and automatically reload when updated, but that probably seems like more work (even if it's a better final UX)

I'd be down to attempt a PR if that sounds like the type of thing that's not already being handled and would be useful

**Comment by Jason3S** [comment]
It does check to see if dictionaries have changed. But there is a hitch, it will not re-check the documents.

**Comment by KyleMit** [comment]
@Jason3S , thanks for the clarification - updated the ticket to provide the correct scope to the request.  My workflow is typically that I'll go fix a lot of spelling suggestions all at once, so I'll open the dictionary so I can paste real words directly into the dictionary, and it would be nice to see the problems list slowly resolve as I manually update the dictionary.  

Currently, I'm just reloading VS Code every so often, but also might leverage the whole dictionary refresh by just modifying the dictionary file in settings to have that kick off a fresh upload

**Comment by Jason3S** [comment]
It is possible to get the spell checker to evaluate all the open files by turning of / on the spell checker.
If you assign a keyboard short cut to enable / disable spell checking by default commands, it will make it easier.

![image](https://user-images.githubusercontent.com/3740137/90077229-eda5e700-dd01-11ea-8f9b-248a08c48737.png)

**Comment by Jason3S** [comment]
@KyleMit A file watcher was added to watch all dictionaries. If a dictionary changes, all files should be re-checked.

**Comment by KyleMit** [comment]
That's awesome - thanks @Jason3S !! 🎉

Guess I won't need this [vs code extension helper](https://github.com/KyleMit/vs-utils/blob/master/src/commands/refreshCspell.ts#L4-L11) I made anymore :)
