### ISSUE TITLE
-ing, -ed not working well, -s not cooperating with custom words

### ISSUE THREAD

**Issue by hugeliveux** [streetsidesoftware/vscode-spell-checker#510]
"favorited" and "favoriting" are marked out.
Please note that "favorited" is a distinct word from "favored". The English version "favourited" is also marked out.
<img width="199" alt="image" src="https://user-images.githubusercontent.com/65123894/86353215-c3014280-bc1b-11ea-91f0-cbacdd717b90.png">

Also, if I add "aka" in the `"cSpell.words"`, "akas" would still be marked out.

Thanks!

**Comment by Jason3S** [comment]
The extension does not automatically add stems to words. It strictly compares against words in the dictionaries.

**Comment by Jason3S** [comment]
Closing as stale.
