### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by ernestob** [streetsidesoftware/vscode-spell-checker#513]
- Issue Type: `Performance`
- Extension Name: `code-spell-checker`
- Extension Version: `1.9.0`
- OS Version: `Darwin x64 18.7.0`
- VSCode version: `1.46.1`

[streetsidesoftware.code-spell-checker-unresponsive.cpuprofile.txt](https://github.com/streetsidesoftware/vscode-spell-checker/files/4921686/streetsidesoftware.code-spell-checker-unresponsive.cpuprofile.txt)

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by Jason3S** [comment]
Please see #431
If that is not the case, please let me know.
