### ISSUE TITLE
Doesn't work in big JSON files

### ISSUE THREAD

**Issue by rori4** [streetsidesoftware/vscode-spell-checker#518]
The spell check doesn't work in big JSON files.

If you add and misspelled word on top of the file it will underline it but after around line 1000 the spell check doesn't work any more.
![image](https://user-images.githubusercontent.com/22402693/87763601-b71d9f00-c81d-11ea-826e-11cf0134ea65.png)
![image](https://user-images.githubusercontent.com/22402693/87763635-c997d880-c81d-11ea-911f-81c204c9ab0a.png)

**Comment by Jason3S** [comment]
There is a default size limit to prevent the spell checker from taking too long.

![image](https://user-images.githubusercontent.com/3740137/90074750-280c8580-dcfc-11ea-8efe-a12fb9749902.png)

You can also use the cli tool: [cspell - npm](https://www.npmjs.com/package/cspell)

**Comment by rori4** [comment]
Thanks that solves it 👍
