### ISSUE TITLE
ability to allow combined words

### ISSUE THREAD

**Issue by ssbarnea** [streetsidesoftware/vscode-spell-checker#522]
Very often in programming we have keys that are made from concatenating two words and I used spellcheckers that were able to recognize such combinations and to ignore them.

Having to add a huge amount of words to ignore lists is not only annoying but also decreases the performance of the spelling.

Practical examples `is****`, `list***`, `match***`, and these come from public API of famous libraries, even stdlibs.

**Comment by BenHocking** [comment]
This is already supported. See the "camelCase" discussion. See also the "enableCompoundWords" setting to allow not just "isFound" but also "isfound".

**Comment by Jason3S** [comment]
The challenge with `enableCompoundWords` is that it considers some clearly misspelled words to be considered correct. See #345 

It might be nice to allow for common patterns like `is*` and `error*` to pick up `isset` or `errorcode` while being able to avoid

**Comment by Jason3S** [comment]
Closing as stale.

Note:
It is possible to add compoundable words to your dictionary:

**`cspell.config.yaml`**
```yaml
words:
  - *error*
  - *code*
```

This will allow compounds like: `errorcode`, `codeerror`, `codecode`.
