### ISSUE TITLE
extension saving into `.vscode/settings.json` of the root folder instead of repo

### ISSUE THREAD

**Issue by gocarlos** [streetsidesoftware/vscode-spell-checker#523]
I have two repos:

* /home/user/repo/backend
* /home/user/repo/frontend

normally I have two instances of code with each repo open.
then the spell checker will save to `/home/user/repo/fronend/.vscode/settings.json` or `/home/user/repo/backend/.vscode/settings.json`

but from time to time I open `/home/user/repo` which contains both repos.
then the dictionary if the repos are ignored and the new words are saved in  `/home/user/repo/.vscode/settings.json` -> those are duplicates of the previous ones...

could this be fixed the same way as e.g. `package.json` or `.gitignore` work e.g. just go recoursivelly up until finding a `.vscode/settings.json` and check if this word is there, otherwise give a warning...

**Comment by Jason3S** [comment]
The `.vscode/settings.json` files are created by VS Code. If you create a VS Code workspace and open that instead, it should do what you expect.
