### ISSUE TITLE
Search for typos in the whole repo

### ISSUE THREAD

**Issue by pedro-lb** [streetsidesoftware/vscode-spell-checker#528]
Hey there,

First of all this extension is amazing! Love it!

So, can we search for typos in the whole repo? Something by a command that lists all typos in all files or by running something in the command line...

Since it's easy to detect typos in the file we're currently editing, but apparently there is no way to detect typos in all files.

**Comment by Jason3S** [comment]
This extension uses the cspell library to do the checking. It is possible to use [cspell](https://www.npmjs.com/package/cspell) cli to check whole directories.

**Comment by pedro-lb** [comment]
Thanks!
