### ISSUE TITLE
Bulk "Add to User Dictionary" option

### ISSUE THREAD

**Issue by ctjlewis** [streetsidesoftware/vscode-spell-checker#529]
Love this plugin, but it's common for a project to have a lot of words the Spell Checker doesn't recognize. This isn't a big deal, but I can't manually add 100 words to the User Dictionary. If I could Ctrl+A, right click > Add to User Dictionary in bulk, it would be a huge benefit.

![image](https://user-images.githubusercontent.com/1657236/89823863-cc81a280-db17-11ea-8510-b2ccc7858f93.png)

Love the spell checking functionality, don't love the "Problems" panel filling up.

**Comment by Jason3S** [comment]
Being able to select multiple problems in the Problems panel is not something an extension has any control over.

However, it is possible to add All the issues in a document to your dictionary.

1. Select the whole document (or the part with the errors you care about).
2. Bring up the Context Menu (right click).
3. Select Add All Spelling Issues to Dictionary
    ![image](https://user-images.githubusercontent.com/3740137/133894543-43aadddf-754d-4a44-acd0-9b863f05d611.png)
    It should give you a choice on where to save them.

**Comment by glasser** [comment]
Another way to solve this problem (getting everything in a file or project into your project dictionaries) is via the command-line version (https://www.npmjs.com/package/cspell)
