### ISSUE TITLE
description of checkLimit option is wrong

### ISSUE THREAD

**Issue by tjx666** [streetsidesoftware/vscode-spell-checker#540]
Now the description is `The limit in K-Bytes to be checked in a file.`, but I see the [source code](https://github.com/streetsidesoftware/vscode-spell-checker/blob/075ec875fab13a6912529c067c0f85e2ba3f5e67/packages/_server/src/validator.ts#L28) represent how many k chars to be checked, not the byte.

Source code:

```typescript
 const limit = (options.checkLimit || defaultCheckLimit) * 1024;
 const text = textDocument.getText().slice(0, limit);
```

**Comment by Jason3S** [comment]
You are right.
