### ISSUE TITLE
A word with accents adds several entries in dictionary

### ISSUE THREAD

**Issue by Wingjam** [streetsidesoftware/vscode-spell-checker#541]
When adding for example `sécuritéss` to the dictionary, here is the following entries added: 

```json
"cSpell.words": [
    "curit",
    "s",
    "ss",
    "sécuritéss"
]
```

**Comment by Jason3S** [comment]
Thank you.

**Comment by Nokel81** [comment]
I have run into this as well. I also have found that words that match with accents stripped still "pass" the spell checking.

**Comment by Jason3S** [comment]
This fix will be in the 2.x release.
