### ISSUE TITLE
Status bar flashes while typing in version 1.9.1

### ISSUE THREAD

**Issue by bradym** [streetsidesoftware/vscode-spell-checker#552]
First, thanks for the great extension!

In the latest version (1.9.1) while typing, updates flash in the status bar which is very distracting. Perhaps a debug flag was left enabled when publishing the latest version? Can this be disabled?

![spellcheck-bug](https://user-images.githubusercontent.com/289182/94186278-5765f480-fe5b-11ea-96dd-52b29cac72a2.gif)

![image](https://user-images.githubusercontent.com/289182/94186729-e5da7600-fe5b-11ea-8253-b3dbb8cd1b51.png)

**Comment by Jason3S** [comment]
Thank you, that should not be happening.

**Comment by bradym** [comment]
Just installed 1.9.2 and this is no longer happening. Thank you for such a speedy fix! :)
