### ISSUE TITLE
Add link to the github repo on the official extension page

### ISSUE THREAD

**Issue by jerabaul29** [streetsidesoftware/vscode-spell-checker#553]
This page:

https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker#overview

Has not link to this repo. Maybe it would be a good idea to add?

**Comment by Jason3S** [comment]
Thank you. It had been there.

**Comment by Peter-Darton-i2** [comment]
I've just checked and the overview page (both within VSC and at the URL above) has a link called "Repository" that links to this repo.

I think this can be closed.
