### ISSUE TITLE
Regular Expressions Check

### ISSUE THREAD

**Issue by kingeke** [streetsidesoftware/vscode-spell-checker#555]
Sometime, the plugin runs a regular expression check when i'm using vscode, this process hangs my vscode and makes things like linting or function helpers or even prettier all hang, and makes my vscode inoperable.

I think this issue started with the new update, cause i never experienced this before.

Please look into it as its a serious bug.

**Comment by Jason3S** [comment]
@kingeke
Thank you. What type of files are you editing?
Please include a bit of information about you system: OS, etc. Please copy the about dialog:

The result will look something like this:
```
Version: 1.49.1
Commit: 58bb7b2331731bf72587010e943852e13e6fd3cf
Date: 2020-09-16T23:21:17.533Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
```

**Comment by kingeke** [comment]
@Jason3S its a PHP file

Version: 1.49.2 (user setup)
Commit: e5e9e69aed6e1984f7499b7af85b3d05f9a6883a
Date: 2020-09-24T16:29:41.983Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.17763

had to downgrade back for the issue to stop.

basically that running regular expressions check icon just stays on my notification bar even after i'm done typing, and causes my whole vscode to hang

**Comment by Jason3S** [comment]
@kingeke is it still happening with the latest release?

**Comment by kingeke** [comment]
@Jason3S sorry for the late response, no its not.. haven't noticed it again.

**Comment by Jason3S** [comment]
Thank you.
