### ISSUE TITLE
correleation and correlation

### ISSUE THREAD

**Issue by zztalker** [streetsidesoftware/vscode-spell-checker#560]
When I type `correleation correlation correlaation` in MD file both first and last wrong typed word detected. But in python file only the last word detected.

How to check why does it happen? 

Step to reproduce:

1. Open new python file (*.py)
2. Type: correleation correlation correlaation 

![image](https://user-images.githubusercontent.com/1027857/95155458-dd0f6b80-079c-11eb-9eb4-434db7299232.png)

3. Open  new markdown file (*.MD)
4. Type same string

![image](https://user-images.githubusercontent.com/1027857/95155245-63777d80-079c-11eb-8426-6759b1e95ea7.png)

**Comment by Jason3S** [comment]
It is because word compounding is turned on for Python by default.

See #383, #345

**Comment by zztalker** [comment]
Thank you, this change in config helps.

```json
    "cSpell.languageSettings": [
        {
            "languageId": "python",
            "allowCompoundWords": false
        }
    ],
```


> It is because word compounding is turned on for Python by default.
> 
> See #383, #345
