### ISSUE TITLE
Feature Request - Ability to navigate list with VIM shortcuts or alternatives

### ISSUE THREAD

**Issue by account-sxf** [streetsidesoftware/vscode-spell-checker#565]
At present after pressing ctrl+. to see the suggested fixes, you have to leave the home row and press the up or down arrow or mouse to choose another option. It would be nice to press j or k (vim-style) or Ctrl+n (also vim-style) or repeat press ctrl+. to cycle.

**Comment by Tandolf** [comment]
im also looking for this, or at least the exposure of the navigation as parameters that we can map.

**Comment by b1m1nd** [comment]
I would love to see this too... I was actually banging my head over and over trying to figure out how to bind it my self. Why type of window is it and what command can we use to change the binding our self? 

I have been trying a few things but nothing seems to work..
It seems that `quickFixWidgetVisible` is the window? I can expose it with `when` trying to rebind but using cmd `selectNextSuggestion` is not working just closes the window 😂 ....

**Comment by Jason3S** [comment]
The support for this will go out with V2.
You can check it out now: [Releases · streetsidesoftware/vscode-spell-checker](https://github.com/streetsidesoftware/vscode-spell-checker/releases)

See: 
## Previous and Next Issue Commands

| Command                                      | Description                               |
| -------------------------------------------- | ----------------------------------------- |
| `cSpell.goToNextSpellingIssue`               | Go to Next Spelling Issue                 |
| `cSpell.goToPreviousSpellingIssue`           | Go to Previous Spelling Issue             |
| `cSpell.goToNextSpellingIssueAndSuggest`     | Go to Next Spelling Issue and Suggest     |
| `cSpell.goToPreviousSpellingIssueAndSuggest` | Go to Previous Spelling Issue and Suggest |
