### ISSUE TITLE
Publish extension and dictionary add-ons on open-vsx.org, so it can be used in VSCodium, etc

### ISSUE THREAD

**Issue by geekley** [streetsidesoftware/vscode-spell-checker#567]
Firstly, thanks for the amazing extension. You guys are awesome!

Can you please publish the dictionary extensions on Open-VSX, so it can reach more users?
https://open-vsx.org is an alternative to VS Marketplace, [that can legally be used](https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions-marketplace) in Visual Studio Code forks like [VSCodium](https://github.com/VSCodium/vscodium#why-does-this-exist).
Of course, you don't have to change anything in the extension itself.
Except maybe some README URLs that point to VS Marketplace, if you care about these details.

[The process](https://github.com/eclipse/openvsx/blob/master/cli/README.md) is pretty much the same as publishing to VS Marketplace.
It can even be automated, see:
https://github.com/open-vsx/publish-extensions/issues/195
> Ideally the original maintainers would publish the extensions themselves. Could you create an issue at vscode-spell-checker? In case they are not willing to do it, we can add the extensions to the list here.

You can [claim ownership](https://github.com/eclipse/openvsx/wiki/Namespace-Access) of your namespace `streetsidesoftware`, and officially support the main extension there:
https://open-vsx.org/extension/streetsidesoftware/code-spell-checker

**Comment by Jason3S** [comment]
I will
