### ISSUE TITLE
Auto completion as you type

### ISSUE THREAD

**Issue by Jason3S** [streetsidesoftware/vscode-spell-checker#57]
# Autocomplete
Offer word completion as you type.

Based upon how suggestions for spelling errors is generated.  It is possible to suggest word completions as someone types.

## Ideas
* Only suggest after  the first *n* characters.  (n = 3 could be a good start).
* Based upon word frequency in the workspace, rank for frequent words higher in the suggestion list.
* The number of suggestions needs to be limited (max of 10?).

## Config Options
* enable / disable autocomplete
* min word length before suggesting.
* set the number of suggestions.
* enable / disable spelling suggestions (exact matches are faster at searching)
* set the level of fuzziness allowed (edit distance).
* Use frequency analysis in workspace to improve the quality of the suggestions.

**Comment by jens1o** [comment]
As long as when I explicitly do not choose something it won't be overwritten. That would annoy really hard.

**Comment by Jason3S** [comment]
You would have to hit *tab* or click with the mouse, just like the normal code completion.

**Comment by jens1o** [comment]
Nice, thank you.

**Comment by BillDenton** [comment]
How would this interact with the normal code completion. Would it be mutually exclusive?

**Comment by Jason3S** [comment]
It just adds to the code completion list.

**Comment by Jason3S** [comment]
Too many other things to do that are more important.
