### ISSUE TITLE
disable-next-line not working

### ISSUE THREAD

**Issue by vaaski** [streetsidesoftware/vscode-spell-checker#573]
I'm including a publicly available client_id in my source code and I want to disable cspell for the line where I set the variable, but disable-next-line doesn't seem to work.

![image](https://user-images.githubusercontent.com/17879327/98240218-5dc2b280-1f69-11eb-9259-70316e7e0e83.png)

When I try to disable it before the line and re-enable it after the fact it works as expected, but it's a little verbose for what I need it for.

![image](https://user-images.githubusercontent.com/17879327/98240735-27396780-1f6a-11eb-91df-9d0be4687930.png)

I tried it in TypeScript and native JavaScript, but no luck.
Using vscode 1.50.1 and vscode-spell-checker v1.9.2.

**Comment by mjmatthiesen** [comment]
Can confirm that this stopped working

**Comment by Jason3S** [comment]
I will publish a fix today.

**Comment by vaaski** [comment]
works again, thanks :)
