### ISSUE TITLE
set spell checker language per-file

### ISSUE THREAD

**Issue by MinnieTheMoocher** [streetsidesoftware/vscode-spell-checker#578]
I do not want to enable multiple languages for spell checking for my whole project.

Instead, there are just some few files which use a different language than English: the localization files.

In those, I would like to explicitly enable a specific language, for example
- for the "German" localization file I would like to be able to additionally enable "German" spellchecking in addition to English
- for the "French" localization file I would like to be able to additionally enable "French" spellchecking in addition to English

Can we get a config setting please which allows me to enable these individual settings per-file?

The existing global config switch 
```
"cSpell.language": "en,de,fr",
```
is not sufficient here, because it enables the 3 dictionaries in ALL files, which I would like to avoid

**Comment by Jason3S** [comment]
Overrides allow you to do that.
Example: [cspell-dicts/cSpell.json](https://github.com/streetsidesoftware/cspell-dicts/blob/master/cSpell.json)

Using VS Code settings:
```js
    "cSpell.overrides": [
        {
            // the language setting is applied to files matching the glob defined in `filename`
            "filename": "**/nl_NL/**",
            "language": "en,nl"
        }
    ]
```

**Comment by MinnieTheMoocher** [comment]
awesome! will try it!

**Comment by MinnieTheMoocher** [comment]
works as a charm. thanks
