### ISSUE TITLE
Q: How to spell check large files?

### ISSUE THREAD

**Issue by bshoshany** [streetsidesoftware/vscode-spell-checker#580]
I'm writing a huge Markdown file (currently 573 KB and 12,823 lines long) using VS Code. After a certain point in the file, the spell checker doesn't recognize any more spelling mistakes.

If I add a misspelled word before the cutoff point, it gets detected, but if I add a misspelled word after the cutoff point, it does **not** get detected.

Interestingly, if the cutoff is in the middle of a word, the first half of the word will be detected as an unknown word. For example, if the cutoff is in the middle of the word "keyboard", then "keyb" will be detected as an unknown word.

I tried my best, but could not find a specific number of bytes where the cutoff begins. It seems to change dynamically, and I could not find any patterns.

This seems to be independent of the type of file (I tried both Markdown and Plain Text). It's unlikely to be due to VS Code limiting the number of messages from the extension, as there are exactly zero messages (I do not have any spelling mistakes in the file prior to the cutoff point).

Currently, in order to find spelling mistakes in new content I add to the end of the file, I must copy the last few thousand lines to a new editor window, and only then the spelling mistakes are detected, which is very inconvenient. Would it be possible to solve this issue?

**Comment by Jason3S** [comment]
There is a limit to the size of the file checked. You can make it larger.

In VS Code Settings -> cspell limit

It defaults to 500K characters.

![image](https://user-images.githubusercontent.com/3740137/99140882-d8fd2600-2645-11eb-9e72-8c90186bae49.png)

**Comment by bshoshany** [comment]
Well, now I feel stupid 😅 I swear checking the options was the first thing I did, but for some reason I missed that.
