### ISSUE TITLE
"actual command NOT FOUND"

### ISSUE THREAD

**Issue by bshoshany** [streetsidesoftware/vscode-spell-checker#581]
I right click on one spelling mistake and choose one of the suggestions. This works. Then, I immediately right click on another spelling mistake and choose one of the suggestions. This doesn't work, and the mysterious error "actual command NOT FOUND" appears:

![image](https://user-images.githubusercontent.com/61846320/99147971-fd133400-2652-11eb-9efe-f75c98130503.png)

This error happens all the time, and it seems that the only way to avoid it is to wait a few seconds before correcting each subsequent misspelling. Can this be fixed?

**Comment by Jason3S** [comment]
What programming language are you using?

The spell checker tries to use each languages rename provider. But sometimes they are not robust enough.

You can turn if off: Settings -> cspell rename provider
![image](https://user-images.githubusercontent.com/3740137/99155543-0afba000-26b9-11eb-9b2a-67c678e63ddf.png)

**Comment by bshoshany** [comment]
This is a Markdown document. If I turn off the rename provider, it doesn't offer any spelling suggestions. Is there no way to get suggestions but also avoid this error?

**Comment by Jason3S** [comment]
Hmm. It should show them. How do you get the suggestions? `ctrl-.` or `cmd-.`?

**Comment by bshoshany** [comment]
Sorry, my bad - for some reason I thought there were no suggestions after I turned off the rename provider, but now I checked again and they do appear. I must have used right-click instead of `Ctrl+.`.

I can also confirm that the weird "actual command NOT FOUND" error does not appear anymore.

What exactly does turning off the rename provider do? (Or... what is a rename provider?)

Thanks!

**Comment by Jason3S** [comment]
VS Code uses rename providers to help with changing variable names in code. It will change all related occurrences of it.
