### ISSUE TITLE
Error: Failed to read config file

### ISSUE THREAD

**Issue by inwardmovement** [streetsidesoftware/vscode-spell-checker#601]
When I load a file with spell check I have this error:

![image](https://user-images.githubusercontent.com/9438102/99178779-f3530480-2716-11eb-9ce5-c8f63c70de77.png)

The link `c:\Users\...\inwardmovement.github.io\c:\Users\...\cspell-dicts\packages\fr_FR_90\cspell-ext.json` seems not correct.

**Comment by Jason3S** [comment]
Thank you.

Does the file exist at `c:\users\arkay\Documents\cspell-dicts\packages\fr_FR_90\cspell-ext.json`?

**Comment by inwardmovement** [comment]
No, I have no `cspell-dicts` folder at `c:\users\arkay\Documents\`

**Comment by Jason3S** [comment]
Did you ever have them there?

There is a configuration file telling the extension to load `c:\users\arkay\Documents\cspell-dicts\packages\fr_FR_90\cspell-ext.json`

Please take a look at your `cspell.json` files or in VS Code settings under "imports"

**Comment by inwardmovement** [comment]
I deleted `cspell.json` and reinstalled cspell + dict and the error is not here anymore.

But I still have the issue https://github.com/streetsidesoftware/cspell-dicts/issues/92, can you have a look at it please?
