### ISSUE TITLE
Please add lorem ipsum to dictionary

### ISSUE THREAD

**Issue by theredwillow** [streetsidesoftware/vscode-spell-checker#602]
Lorem ipsum text is not in the dictionary, creating dozens of false positive linting problems.

More information is available [here](https://www.lipsum.com/).

**Comment by theredwillow** [comment]
Disregard. This feature is available as an add-on. Click [here](https://github.com/streetsidesoftware/cspell-dicts/tree/master/packages/lorem-ipsum) for more information.

**Comment by Jason3S** [comment]
The lorem-ipsum dictionary is installed by default, but it is not enabled. See https://github.com/streetsidesoftware/cspell-dicts/pull/214#issuecomment-730623538

**Comment by Jason3S** [comment]
You can also use the add-on.
