### ISSUE TITLE
Make it possible to store User Words into a dictionary file instead of settings.json

### ISSUE THREAD

**Issue by denis-ko** [streetsidesoftware/vscode-spell-checker#61]
Is it possible to store words that currently appear in "cSpell.userWords" in a separate file?
After couple of days pressing "Add to dictionary" my user settings file became pretty large and is still growing.

**Comment by Jason3S** [comment]
Yes, this is possible.  Just copy the words into a text file and follow the step:  [how-to-add-your-own-dictionaries](https://github.com/Jason-Rev/vscode-spell-checker/blob/master/client/README.md#how-to-add-your-own-dictionaries)

The documentation is new, so if you have any feedback on how to improve it for understanding, please make some suggestions.

**Comment by denis-ko** [comment]
Oh. I wasn't clear enough. The documentation is pretty clear regarding dictionaries. However, I was talking about overriding the behavior of "Add to dictionary".

Here is my scenario. I'm trying to use cSpell with LaTeX files. Apparently there is a lot of text and specific terminology that is unknown in advance. So I cannot create a static custom dictionary and add it via the current mechanism. Of course, I can manually copy/paste from the settings file each time it grows beyond some point, but it is a bit awkward.

**Comment by Jason3S** [comment]
Ahh. you want to be able to configure the target for adding words from the UI.

Something like:
```javascript
// At the user level
"cSpell.userDictionaryLocation": ".../dictionaries/my_personal_dictionary/words.txt",
// or at the project level
"cSpell.projectDictionaryLocation": "./words.txt",
```

And have the extension add to that dictionary instead of the settings.json file.

**Comment by denis-ko** [comment]
Yes. Though at the project level it may be meaningless.

**Comment by memeplex** [comment]
A problem with cluttering settings file like that is that new settings get added at the end of the file, so you have to scroll down to the end each time new settings are added.

**Comment by janosh** [comment]
@Jason3S Another option would be to follow the example of [Settings Sync](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync) and allow users to store their custom dictionary in a private gist on GitHub. I assume you could recycle much of their implementation and it would make away with having to handle local files on different OS's.

**Comment by DerekNonGeneric** [comment]
Please implement a something `cSpell.projectDictionaryLocation` that accepts a path to a dictionary relative to the project/workspace root! 🙏 Also, it would be great to be able to have the option to "Add to a project dictionary" via the lightbulb tooltip. 💡 I'm not sure what the expected workflow is, but the current behavior of having "Add to folder dictionary" via the lightbulb tooltip add words to both the `.vscode/settings.json` and `cSpell.json` files no bueno! Maintaining the exact same dictionaries in two separate locations is bound to eventually desync. This dictionary should be able to be appended to via the VS Code UI and referenced from a `cSpell.json` file, which can likewise be used by the `cspell` CLI tool. I'd be willing to make the PR if given the green light. 🚥

/to @Jason3S Thanks for all the hard work on these tools! 👋

**Comment by Jason3S** [comment]
@DerekNonGeneric a pull request would be awesome!

**Comment by Jason3S** [comment]
With 1.9.0, it will be possible to add a custom dictionary location. Would you try out: [v1.9.0-alpha.0](https://github.com/streetsidesoftware/vscode-spell-checker/releases/tag/v1.9.0-alpha.0)

**Comment by DerekNonGeneric** [comment]
Thanks, @Jason3S, you're the best! I was able to get it working perfectly! 🚀✨

**Comment by denis-ko** [comment]
Works great. Thank's!

**Comment by janosh** [comment]
@Jason3S Your work is much appreciated! Looking forward to the public release.

**Comment by Jason3S** [comment]
I have made it slightly easier to use with [v1.9.0-alpha.5](https://github.com/streetsidesoftware/vscode-spell-checker/releases/tag/v1.9.0-alpha.5)

The custom dictionaries can refer to a predefined dictionary:

### Example with a dictionary reference

`cspell.json`
``` jsonc
"dictionaryDefinitions": [
    {
        "name": "cities",
        "path": "./sampleDictionaries/cities.txt"
    },
    {
        "name": "project-terms",
        "path": "./words.txt"
    }
]
```

VS Code `settings.json`
``` jsonc
"cSpell.customWorkspaceDictionaries": ["project-terms"]
```

**Comment by muuvmuuv** [comment]
@Jason3S I would also add `"cSpell.customWorkspaceDictionaries": ["*"]` which would add all. So I don't need to edit two places if not needed.

**Comment by Jason3S** [comment]
What would "*" mean? There are a lot of active dictionaries. You want to write words to all of them? Please describe the behavior you are looking for.

You can also add `customWorkspaceDictionaries` to the `cspell.json` file.

**Comment by muuvmuuv** [comment]
The asterisk would mean to use all dictionaries. But anyway I think I misunderstood `customWorkspaceDictionaries`. I will try a few things out and if my use-case does not fit I will come back ^^.
