### ISSUE TITLE
"Add Word to Workspace Dictionaries" has stopped working

### ISSUE THREAD

**Issue by Zamiell** [streetsidesoftware/vscode-spell-checker#617]
Greetings,

In my repository, I have a ".cspell.json" file in the root directory that contains the following:

```
{
    "version": "0.1",
    "language": "en",
    "dictionaries": [
        "en_US",
        "companies",
        "softwareTerms",
        "html"
    ],
    "words": [
        "apple",
        "bubble",
        "coffee",
        [more words, snip]
    ]
}
```

Historically, when I see a new word with a blue squiggly underline on it, then I would right click that word and select "Add Word to Workspace Dictionaries". Then, the extension would add the word to the ".cspell.json" file (and automatically sort it alphabetically).

Now, the extension no longer functions like this, perhaps due to a recent update or some other change.

Steps to reproduce:

- Install a fresh Windows 10.
- Install Git and VSCode.
- Install the Spell Checker extension.
- Clone my repo: `git clone https://github.com/Zamiell/hanabi-live.git`
- Open it in VSCode: `code hanabi-live`
- Open the ".cspell.json" file and observe that there are hundreds of entries in the "words" array.
- Type "asdf" into a new file. (A blue line will now appear underneath "asdf".)
- Right click on "asdf" and select "Add Word to Workspace Dictionaries".
- The "asdf" word will *still* have a blue line underneath it, with nothing appearing to have changed.
- In the ".cspell.json", *every* entry is deleted from the words array.

**Comment by SanchithHegde** [comment]
I have been able to reproduce this issue on my Arch Linux system as well. For now, I have downgraded to version `1.9.4` and adding words to the workspace dictionary works as expected.

**Comment by Jason3S** [comment]
This should be fixed with version 1.10.2

**Comment by Zamiell** [comment]
Thank you Jason for your work on this excellent extension, it is greatly appreciated!

**Comment by SanchithHegde** [comment]
Thanks for the quick fix!
