### ISSUE TITLE
Problems Panel: Spell Checking looping

### ISSUE THREAD

**Issue by adampatterson** [streetsidesoftware/vscode-spell-checker#618]
I'm new to VS Code and not 100% sure if this issue is even related to this extension.

I noticed the problems panel flashing at me so I had a look, I then closed the file and it continued to loop like this.

https://d.pr/v/UY9Ss5.gif

**Comment by Jason3S** [comment]
Would you check to see if it is problem with the spell checker vs a problem with VS Code? 

One thing to try is to see if the spell check keeps running:

1. Increase the spell checkers log level to Debug:
![image](https://user-images.githubusercontent.com/3740137/100468172-2bbdef80-30d4-11eb-9b9d-f4a40173be32.png)

2. Watch the Output for the spell checker to see if it is constantly re-checking the file:
![image](https://user-images.githubusercontent.com/3740137/100468759-5492b480-30d5-11eb-85a7-a400b5832efb.png)

If it is constantly checking the file, then something is triggering the spell checker. If the spell checking is not always running, then it is most likely an issue with VS Code.

**Comment by adampatterson** [comment]
Today it seems to be acting fine, I wonder if it was something that was indexing the project?

I don't remember if the project I had open had been open before but as it is right now everything seems fine.

I will close this and if I notice it again try to add some more details.
