### ISSUE TITLE
A definition for the selected symbol could not be located.

### ISSUE THREAD

**Issue by krsinghshubham** [streetsidesoftware/vscode-spell-checker#649]
Every time I correct a wrong input, VSC pops up a error in bottom right with 
"A definition for the selected symbol could not be located."
How to fix this ?

**Comment by Jason3S** [comment]
I guess you are using PHP (If not, please let me know).

The PHP rename provider is a bit too sensitive. A workaround can be found here: #446 .

**Comment by krsinghshubham** [comment]
no, i am using cpp. attached a screenshot. 
how to get rid of this notification in bottom right every time after making corrections.
![Screenshot 2020-12-26 175542](https://user-images.githubusercontent.com/47324260/103151380-8a59a600-4732-11eb-96a6-4ec4a8dfe423.png)

**Comment by Jason3S** [comment]
Try this:

Turn it off in VS Code settings. Search for `spell rename` and uncheck the box.
![image](https://user-images.githubusercontent.com/3740137/76678435-3f720600-65d8-11ea-9976-8ccfefd7d447.png)

**Comment by krsinghshubham** [comment]
thanks.
