### ISSUE TITLE
Open VSX Listing: Signing the Publisher Agreement

### ISSUE THREAD

**Issue by spoenemann** [streetsidesoftware/vscode-spell-checker#660]
Thank you for being part of the Open VSX community by adding your extensions to the Open VSX Registry. Please note that the service was recently transferred to the Eclipse Foundation and urgent action on your part is needed so we can continue to list your extensions. To ensure uninterrupted service, please sign the [Eclipse Publisher Agreement](https://www.eclipse.org/legal/documents/eclipse-openvsx-publisher-agreement.pdf) **on or before January 8, 2021**. If not signed by that date, your extensions will be delisted and will no longer appear on the site nor be available via the API. If you sign at a later date, your extensions will then be re-activated. The signing process is [explained in the Wiki](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions) (steps 1 and 2).

Please also note that all extensions MUST have a license in order to be listed.

More details are in these recent blog posts:
https://blogs.eclipse.org/post/brian-king/open-vsx-registry-under-new-management
https://blogs.eclipse.org/post/brian-king/new-era-open-vsx-registry

Today, there’s growing momentum around open source tools and technologies that support Visual Studio (VS) Code extensions. Leading global organizations are adopting these tools and technologies. This momentum has spurred demand for a marketplace without restrictions and limitations. Thanks for joining us on this journey as we continue to build the Open VSX community. We look forward to continued innovation from you in 2021!

**Comment by mclang** [comment]
Any update on this?

**Comment by Jason3S** [comment]
@mclang this should be done. 
Is there an issue?

**Comment by Jason3S** [comment]
It just took a look. Strange, it is deactivated. I had done everything asked. I will follow up.

**Comment by Jason3S** [comment]
![image](https://user-images.githubusercontent.com/3740137/112267795-47966400-8c76-11eb-99dc-5b4b2e763159.png)

Hmm, maybe I needed to republish.

**Comment by mclang** [comment]
Hello

Now I find it and can install. Thanks for the quick reply :+1:

**Comment by Jason3S** [comment]
The extension had been signed. I was confused by the Open VSX UI:

![image](https://user-images.githubusercontent.com/3740137/112721159-b38cfc80-8f02-11eb-94bd-b26d0a0ff08b.png)

@spoenemann ^^^ 

I think the banner at the top of the Open VSX Market place is confusing. At a quick glance, it seems to imply that the extension was deactivated, but it is not. After careful reading, I realized it was just a general statement.

**Comment by brianking** [comment]
Thanks for the feedback on the banner @Jason3S. I can see how it might be a bit confusing. We'll be removing it soon.
