### ISSUE TITLE
Bump vscode code-spell-checker dictionaries up to date with streetsidesoftware/cspell-dicts ?

### ISSUE THREAD

**Issue by vikivivi** [streetsidesoftware/vscode-spell-checker#661]
While using vscode code-spell-checker-1.10.2, I found that misspelled word `identifer` is indicated as correctly spelled.
It should be `identifier`. Upon investigation, the word `identifer` is found in dotnet.txt.gz

```sh
cd ~/.vscode/extensions/streetsidesoftware.code-spell-checker-1.10.2
find ./ -name "*.gz" | xargs -n1 zgrep -Hn identifer
./server/node_modules/cspell-dict-dotnet/dotnet.txt.gz:1068:identifer
```

When checking against project `streetsidesoftware/cspell-dicts`, the misspelled word `identifer` is not found.
Upon further investigating `dotnet` dictionary, it was found to be very different between the two `dotnet` dictionaries.
9824 entries vs 2543

```sh
grep -rn -w identifer dictionaries/
find ./dictionaries/ -name "*.gz" | xargs -n1 zgrep -Hn identifer

wc -l dictionaries/dotnet/dotnet.txt
9824 dictionaries/dotnet/dotnet.txt

zcat ~/.vscode/extensions/streetsidesoftware.code-spell-checker-1.10.2/server/node_modules/cspell-dict-dotnet/dotnet.txt.gz | wc -l
2543
```

Question: Is it possible to bump vscode code-spell-checker dictionaries up to date with [streetsidesoftware/cspell-dicts](https://github.com/streetsidesoftware/cspell-dicts) project?

**Comment by Jason3S** [comment]
The updated dictionaries are now available in the prerelease version: [Releases · streetsidesoftware/vscode-spell-checker](https://github.com/streetsidesoftware/vscode-spell-checker/releases).

---
Do you find `cspell` useful? Here are some ways you can support future development:
- Contribute to dictionaries: [How to Create a Dictionary](https://github.com/streetsidesoftware/cspell-dicts#how-to-create-a-new-dictionary)
- Documentation
- Helping answer questions and fix issues:
    - [Issues · cspell](https://github.com/streetsidesoftware/cspell/issues)
    - [Issues · VS Code Extension](https://github.com/streetsidesoftware/vscode-spell-checker/issues)
    - [Issues · cspell dictionaries](https://github.com/streetsidesoftware/cspell-dicts/issues)
- Become a [<img src="https://github.githubassets.com/images/modules/site/icons/funding_platforms/patreon.svg" width="16" height="16" alt="Patreon">Patreon!](https://patreon.com/streetsidesoftware)
