### ISSUE TITLE
Use a single language for a specific folder

### ISSUE THREAD

**Issue by DarkLite1** [streetsidesoftware/vscode-spell-checker#671]
I'm sorry if this has been asked before but I couldn't find it in the reported issues here on GitHub, nor in the [FAQ](https://github.com/streetsidesoftware/vscode-spell-checker/blob/master/packages/client/FAQ.md) or the [manual](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker). 

In our project we have a folder called `i18n` that contains `.json` translation files:
![image](https://user-images.githubusercontent.com/10828570/104466160-2e59a300-55b5-11eb-9ece-2578aedadc19.png)

Disregarding these files from being checked by Cspell is easy by inlcuding the filter in the `cspell.json` option `ignorePaths`:
```json
{
  "version": "0.1",
  "language": "en",
  "ignorePaths": [
    "src/i18n/**/*.json"
  ]
}
```

I was wondering if there is a way to tell cspell to check all files in folder `de-de` with the German language and all files in folder `nl-be` with the Dutch language? 

I thought it would be as easy as excluding the paths in the top level `cspell.json` config file and then add another `cspell.json` config file in the subfolder `de-de` for example, with the language set to `de`. But this does not seem to be working. Anyway, if this was working, it would still not solve the issue of checking a `.json` translation file for errors. Example of such a file:

```json
{
  "name": "some German text here",
  "shortDescription": "some German text here",
}
```
So even if it would work it would flag `name` and `shortDescrtiption` as unknown German words. Is there a way around this? Besides enabling a bunch of different languages on all files in the project?

**Comment by Jason3S** [comment]
You can use `overrides`. See [cspell-dicts/cSpell.json](https://github.com/streetsidesoftware/cspell-dicts/blob/master/cSpell.json)
![image](https://user-images.githubusercontent.com/3740137/105550513-cd8f4080-5d01-11eb-8124-5d2946f42dd8.png)

**Comment by DarkLite1** [comment]
Thank you for getting back tome @Jason3S . I tried your suggestion and it works fine like this:

```json
    "overrides": [
        {
            "filename": "***/de-de/**/*.json",
            "language": "en,de"
        },
```
But not like this:
```json
    "overrides": [
        {
            "filename": "src/i18n/de-de/**/*.json",
            "language": "en,de"
        },
```

I am 100% certain the path is correct,. Because the same path does work in the `ignorePaths` section. I'm closing this one as I can live with the wildcards. Just wanted to report it.
