### ISSUE TITLE
.md file markdonwn error create problems

### ISSUE THREAD

**Issue by alexandre-leng** [streetsidesoftware/vscode-spell-checker#677]
Hi,

It can be great if VS CODE ignore .md file format markdonwn and didn't report false positive.

Have a nice day
Alexander
![105608606-2a433780-5da4-11eb-97b5-e487c0d1305c](https://user-images.githubusercontent.com/72550137/105628655-6e831600-5e3e-11eb-865a-168140979982.png)

**Comment by Jason3S** [comment]
@alexandre-leng ,

Would you please double check which extension you are using? The output doesn't look the same.

Kind regards.

**Comment by alexandre-leng** [comment]
the 

> 
> 
> @alexandre-leng ,
> 
> Would you please double check which extension you are using? The output doesn't look the same.
> 
> Kind regards.

THe extension is .md

and the file note.md

the format markdown.

i double check it

have a nice day 
Alexander

**Comment by Jason3S** [comment]
Would you please double check which spell checker you are using. Looking at the output, I do not think it is this one.

**Comment by alexandre-leng** [comment]
Please try it with .Md markdown format ?

Le mer. 27 janv. 2021 à 12:11, Jason Dent <notifications@github.com> a
écrit :

**Comment by Jason3S** [comment]
Please open VS Code's extension market place:
![image](https://user-images.githubusercontent.com/3740137/106169075-432a5f00-618f-11eb-8d21-03e1a7fdd91b.png)

And Check which spell checker is used:
![image](https://user-images.githubusercontent.com/3740137/106169037-3ad22400-618f-11eb-807e-8f1b15b88b55.png)

**Comment by alexandre-leng** [comment]
Hi

two picture are better than a large speech

Witout spell i didn't get fasle positive error
[image: image.png]

with spell i get error on .md file fasle positive


[image: image.png]

i'm 100% sure it's your app who create this bug!!!

have a nice day
Alexander



Le jeu. 28 janv. 2021 à 17:37, Jason Dent <notifications@github.com> a
écrit :

**Comment by alexandre-leng** [comment]
![image(1)](https://user-images.githubusercontent.com/72550137/106196162-61a15200-61b1-11eb-86a9-f23341dc8f4a.png)
![image](https://user-images.githubusercontent.com/72550137/106196164-6239e880-61b1-11eb-8cdb-e7c4be16c1d5.png)

**Comment by Jason3S** [comment]
Hello @alexandre-leng ,

These notifications are coming from the [Spell Right](https://marketplace.visualstudio.com/items?itemName=ban.spellright) extension.
![image](https://user-images.githubusercontent.com/3740137/106243343-85908200-6209-11eb-8315-cd3240766417.png)

These notification are coming from this extension:
![image](https://user-images.githubusercontent.com/3740137/106243514-d3a58580-6209-11eb-961d-7463456fda3c.png)

To Enable French:
1. Install the French Add-on: [French - Code Spell Checker - Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker-french)
  ![image](https://user-images.githubusercontent.com/3740137/106243691-136c6d00-620a-11eb-9639-cfd8b7977b79.png)
2. Tell the extension you want to use French as a language.
  ![image](https://user-images.githubusercontent.com/3740137/106243925-78c05e00-620a-11eb-9fc2-63db02f04d9f.png)
