### ISSUE TITLE
[Question] How to setup a custom dictionary?

### ISSUE THREAD

**Issue by lonix1** [streetsidesoftware/vscode-spell-checker#681]
I'm a little confused by the various config options, and I've read [through this](https://github.com/streetsidesoftware/vscode-spell-checker/issues/61).

I want to store my custom words in a text file at `/.vscode/dictionary.txt`.

So I added this to my workspace settings (`/.vscode/settings.json`), but it doesn't work:
````json
"cSpell.dictionaryDefinitions": [
  { "name": "custom", "path": ".vscode/dictionary.txt" },
],
"cSpell.dictionaries": [ "custom" ],
````

What am I doing wrong?

**Comment by Jason3S** [comment]
The spell checker cannot find the dictionary because it does not know what the file is relative to.

Please try changing the path to:
```
"path": "${workspaceFolder}/.vscode/dictionary.txt"
```

The docs need to be updated to make this clearer, but here is the blurb from the changelog:
## `${workspaceFolder}` substitution in paths and globs

Relative paths were difficult to get working when specified in VS Code settings. It wasn't clear what they should be relative to. Relative paths to a `cspell.json` files are clear.

It is now possible to have the following setting in VS Code preferences.

```json
"cSpell.import": [
  "${workspaceFolder}/node_modules/company_standards/cspell.json"
]
```

for a multiroot with folders `client`, `server`, `common`, it is possible to specify the name of the folder:

```json
"ignorePaths": [
  "${workspaceFolder:client}/**/*.json"
],
"cSpell.import": [
  "${workspaceFolder:server}/node_modules/company_standards/cspell.json"
],
"cSpell.dictionaryDefinitions": [
  {
    "name": "Company Terms",
    "path": "${workspaceFolder:common}/dictionaries/terms.txt"
  }
],
"cSpell.dictionaries": ["Company Terms"]
```

**Comment by lonix1** [comment]
Thanks that seems to solve the path issue! The extension loads all the words from that txt file.

But now there's another issue: when a word is not recognized and I choose the option `Add: "foo" to workspace dictionary`, it actually adds it to the `.vscode/settings.json` file instead of the `dictionary.txt` file...

**Comment by Jason3S** [comment]
It is not very well documented, but it is possible:

```
"cSpell.customFolderDictionaries": ["custom"]
```

Will tell the extension to add files to the `custom` dictionary.


See [Release Notes v1.9.0-alpha.0](https://github.com/streetsidesoftware/vscode-spell-checker/releases/tag/v1.9.0-alpha.0) and https://github.com/streetsidesoftware/vscode-spell-checker/issues/61#issuecomment-629992135

**Comment by lonix1** [comment]
Unfortunately that didn't work for me.

From my `.vscode/settings.json`:
````json
"cSpell.dictionaryDefinitions": [
  { "name": "custom", "path": "${workspaceFolder}/.vscode/dictionary.txt" },
],
"cSpell.dictionaries": [ "custom" ],
"cSpell.customFolderDictionaries": ["custom"],
````

But still when I use <kbd>ctrl .</kbd> over a misspelled word and choose `"Add: "foo" to workspace dictionary"`, it gets added to `.vscode/settings.json` rather than `.vscode/dictionary.txt`.

**Comment by Jason3S** [comment]
I'm guessing you have just a single folder in your workspace.

Please try:
```
"cSpell.customWorkspaceDictionaries": [ "custom" ]
```

**Comment by Jason3S** [comment]
VS Code is a bit confusing on how it deals we workspaces and folders.

If you have a single folder open, that folder is considered the "workspace". If you have multiple folders open, then there is a `.code-workspace` file that defines the workspaces.

VS Code Merges the settings in the following order: user, workspace, folder.

If the folder has a setting of the same name, it overrides the settings from user and workspace.

To be able to write words to different dictionaries, it is necessary to be able to distinguish between the three different configurations. To accomplish this, three different settings are used:

- `customUserDictionaries`
- `customWorkspaceDictionaries`
- `customFolderDictionaries`

**Comment by lonix1** [comment]
> ```
> "cSpell.customWorkspaceDictionaries": [ "custom" ]
> ```

That works! Thank you!

I assume you're talking about those "multi root" workspaces? Yeah I'm just using one root / workspace.

The docs could benefit from my above use case... the `customWorkspaceDictionaries` setting is the magic sauce to make it work.

This is an excellent extension, thanks for making and maintaining it!

**Comment by lonix1** [comment]
BTW the docs mention this twice, but the `addWords` setting doesn't exist:

> // If `addWords` is `true` words will be added to this dictionary.
