### ISSUE TITLE
Ignore camelcase words / deal with letter–diacritics

### ISSUE THREAD

**Issue by bernardoadc** [streetsidesoftware/vscode-spell-checker#686]
I have a language-specific situation where variable words are without letter–diacritics (eg: contratacao vs contratação). This usually happens with camelCased expressions, although it can happen in a single variable word. How to deal with this?

If I ignore those words, then wrong words in valid texts will be ignored as well.

I've tried to ignore RegExp with "[a-z]+[A-Z]+\\w+", but I guess this is builtin the extension, so only the splitted words get to that processing.

**Comment by Jason3S** [comment]
This is a current limitation to the spell checker. A solution is in progress. See [accented letters make errors · Issue #12 · streetsidesoftware/vscode-cspell-dict-extensions](https://github.com/streetsidesoftware/vscode-cspell-dict-extensions/issues/12)

**Comment by bernardoadc** [comment]
Great! I'll follow there
