### ISSUE TITLE
Spellchecking stops in the middle of .md file

### ISSUE THREAD

**Issue by jwatkin** [streetsidesoftware/vscode-spell-checker#689]
I just started to notice that the Code Spell Checker 1.10.2 spellcheck stops working at roughly line 471 in a 563 line .md file. I haven't made any extension or system alterations recently. I've tried disabling all of my other VS Code extensions and reloading but that doesn't make a difference. If I deliberately introduce a misspelled word right before the last one with a squiggly, then the newly misspelled word gets a squiggly and the one after it loses its squiggly. It acts like there's a limit to the allowable number of misspelled words.

**Comment by Jason3S** [comment]
@jwatkin ,

There are limits to the number of issues and the size of the file.

### Issue Limit
`Preferences -> spell problems`
![image](https://user-images.githubusercontent.com/3740137/106246023-bd99c400-620d-11eb-84ff-c0725dda90da.png)


### Size Limit
`Preferences -> spell check limit`
![image](https://user-images.githubusercontent.com/3740137/106245863-82979080-620d-11eb-9f05-a8fc806e0a98.png)

**Comment by jwatkin** [comment]
Excellent. That solved the problem. Thank you for your prompt reply.
