### ISSUE TITLE
short word leading with number works unexpectedly

### ISSUE THREAD

**Issue by JounQin** [streetsidesoftware/vscode-spell-checker#694]
`3rdparty` reports `rdparty`, `alaudak8s` reports `alaudak`

I tried to add `3rdparty` and `alaudak8s` into the dictionary, but it does not work.

**Comment by Jason3S** [comment]
This will get fixed when the cspell library is upgraded to v5.

**Comment by Jason3S** [comment]
In the mean time, it will ignore `rdparty`.
