### ISSUE TITLE
Doesn't understand the contraction "doesn't" in Haskell files.

### ISSUE THREAD

**Issue by kfish610** [streetsidesoftware/vscode-spell-checker#707]
Exactly what the title says. This is in a Haskell string, but I doubt it's because of Haskell, since "don't" works, as does "can't". There might be some more contractions missing, but I'm not sure which.

**Comment by kfish610** [comment]
Related to #9, it seems this one was missed.

**Comment by Jason3S** [comment]
Hello @kfish610,

Thank you for the report. It seems to be an issue explicitly with the Haskell dictionary.

In a JavaScript file:
![image](https://user-images.githubusercontent.com/3740137/108254458-52cc1080-715b-11eb-851b-a1c207b8322b.png)

In a Haskell file:
![image](https://user-images.githubusercontent.com/3740137/108255232-472d1980-715c-11eb-9780-6bed05959095.png)

**Comment by Jason3S** [comment]
Here is a workaround:

VS Code Settings:
```json
"cSpell.languageSettings": [
    {
        "languageId": "haskell",
        "patterns": [
            {
                "name": "'",
                "pattern": "/(?<!n(?='t))'/gi",
                "description": "Prevent ' from breaking contractions."
            }
        ]
    }
]
```

or `cspell.json`

```json
"languageSettings": [
    {
        "languageId": "haskell",
        "patterns": [
            {
                "name": "'",
                "pattern": "/(?<!n(?='t))'/gi",
                "description": "Prevent ' from breaking contractions."
            }
        ]
    }
]

```

**Comment by Jason3S** [comment]
A more inclusive expression would be: 
```
/(?<!n(?='t\b))(?<!\w(?='s\b))(?<!d(?='ve\b))(?<!\w(?='d\b))(?<!\w(?='re\b))'/gi
```
But if you use it, please remember to escape the `\`

**Comment by Jason3S** [comment]
Related to #369

**Comment by kfish610** [comment]
Alright, thanks for the quick reply!

**Comment by cuixiping** [comment]
I added an item to vscode settings and solved my problem.

```json
    "cSpell.ignoreRegExpList": [
      "/\\b(don't|doesn't|didn't|isn't|wasn't|wouldn't|won't)\\b/gi"
    ],
```

You can add more similar words into it.

**Comment by adam-grant-hendry** [comment]
I've also seen this happen with contracted words in YAML files.

**Comment by adam-grant-hendry** [comment]
@Jason3S Here's a list of English word contractions, partly gathered from [here](https://gist.github.com/nealrs/96342d8231b75cf4bb82) with a couple extra additions. You can use this for your unit tests if you like:

[contractions.txt](https://github.com/streetsidesoftware/vscode-spell-checker/files/9033868/contractions.txt)

**Comment by Jason3S** [comment]
@adam-grant-hendry,

Do you have an example of where it is failing? Most of the contractions you listed were already in the dictionary. I have added your list to the English US dictionary.

This issue is very specific to Haskell because it uses `'` in identifiers forcing word breaks on `'`.

**Comment by Jason3S** [comment]
This issue was completed a while ago.
