### ISSUE TITLE
Suggetion lightbulb not showing, adding .ini files to spell check,  cSpell.json as a link..

### ISSUE THREAD

**Issue by derekwallace** [streetsidesoftware/vscode-spell-checker#711]
Hi,
Long time users of vscode and cspell.
Im using remove development from windows box and ssh to a linux box.
extension is enabled on remote ssh.

recently its not being behaving well and i cant debug what is going on.
I have being using a cSpell.json in my workspace to build up a list of allowed words. 

im finding several  issues
1. misspelled words are identified and underlined. but the suggestion light bulb is not appearing.
These are Python files.

![image](https://user-images.githubusercontent.com/5574230/108600162-75457000-738d-11eb-8fc7-9e6f4e588275.png)

no light bulb
![image](https://user-images.githubusercontent.com/5574230/108600163-7eced800-738d-11eb-8167-cf906c5ad067.png)

2. i want to spell check .ini files. 

![image](https://user-images.githubusercontent.com/5574230/108600312-6c08d300-738e-11eb-817a-79d8ab35a74d.png)

works are not spell checked.
![image](https://user-images.githubusercontent.com/5574230/108600328-893da180-738e-11eb-8595-cc4e92cb449a.png)

3. i tried changing the cSpell.json to be a link to another file .this doesnt appear to work 100%. if i add a word it is written to the file. however the word is still listed as not spelt correctly
if i close vscode and reopen the word is now seen as spelt correctly

I was thinking of having several cSpell,json files and i could link to one of them (the reason is not important)

any pointers 
thanks
derek

**Comment by derekwallace** [comment]
investigating a bit more wrt 1.
FOr a non python file (tcl) it works correclty.

Showing the problems console.
right click on a spelling issue for a Python file
![image](https://user-images.githubusercontent.com/5574230/108601169-269ad480-7393-11eb-9cf7-0f021f4854a5.png)

right click on a spelling issue for a TCLfile
![image](https://user-images.githubusercontent.com/5574230/108601176-30243c80-7393-11eb-996b-df2ea8a1fbce.png)


im guessing the Python extensions are in some way hogging and preventing the cSpell from running correctly.
any way to debug this or maybe report to Python extension owner?

**Comment by derekwallace** [comment]
by disabling Pylance the issue is resolved for Python files.

**Comment by derekwallace** [comment]
solved isssue with my .ini files.
vscode regarded them as type TXT
![image](https://user-images.githubusercontent.com/5574230/108606031-8e5f1880-73af-11eb-89c2-5673310b5e10.png)

so i enabled txt for cspell

"cSpell.enableFiletypes": ["txt"]

**Comment by Jason3S** [comment]
@derekwallace,

Thank you for the detailed report.

It is possible the spell checker is getting stuck on a single python file due to a regular expression in `ignoreRegExpList` or `includeRegExpList`. Please double check any patterns you might have there.

Sometimes it can be very subtle in how it appears. It might seem to just stop working, but then works again after VS Code restart.

Would you be able to share your `cSpell.json` file? or at least the parts that include regular expressions?

**Comment by derekwallace** [comment]
I don't have any re in my cspell.json file or in any of my settings. 
When I disable pylance cspell works again. 

D
