### ISSUE TITLE
Only checks first 512K bytes of file.

### ISSUE THREAD

**Issue by lrhn** [streetsidesoftware/vscode-spell-checker#718]
I enabled the checker in a long LaTeX document, and got a surprise error at a prefix of a longer word. I noticed that there were no markers after that point at all, and if I added some characters before, the prefix got shorter.

I checked the file in a hex-viewer, and it seems the file is truncated at precisely 0x7D000 bytes, aka 512000 bytes. The actual file is more than 700k.

**Comment by Jason3S** [comment]
There is a setting that limits how far it will check.

`Settings` -> `spell limit`
![image](https://user-images.githubusercontent.com/3740137/109069624-c341d700-76f1-11eb-879b-73306633b7aa.png)

**Comment by lrhn** [comment]
Thanks!
