### ISSUE TITLE
Support for R and Rmarkdown

### ISSUE THREAD

**Issue by shirdekel** [streetsidesoftware/vscode-spell-checker#734]
What is the chance that support will be added for R and Rmarkdown files?

**Comment by Jason3S** [comment]
You can turn on the spell checker for nearly any file type. See this comment: [How to enable Ruby](https://github.com/streetsidesoftware/vscode-spell-checker/issues/171#issuecomment-778758114)

For full support, it would be great if someone would contribute a dictionary to: [streetsidesoftware/cspell-dicts](https://github.com/streetsidesoftware/cspell-dicts).

**Comment by shirdekel** [comment]
Thanks, that works!
