### ISSUE TITLE
Enhancement: Use a CodeLens UI

### ISSUE THREAD

**Issue by bobrocke** [streetsidesoftware/vscode-spell-checker#76]
Make use of a CodeLens for correction suggestions in place of the decoration in the gutter.

**Comment by Jason3S** [comment]
I agree that the discoverability of suggestions needs to be improved, but I haven't figured out what it is yet.  CodeLens has a different purpose.  At the moment, the right click menu isn't accessible from the plug-in.

**Comment by Jason3S** [comment]
The right click menu can now be used for suggestions.
