### ISSUE TITLE
Unknown words added to workspace dictionary are not taken into account afterwards

### ISSUE THREAD

**Issue by wsw70** [streetsidesoftware/vscode-spell-checker#784]
I have a set of words that are correct for me but tagged as typos by `cSpell`. I therefore added them to the workspace dictionary:

![image](https://user-images.githubusercontent.com/1345886/112974158-7159fa00-9152-11eb-88ec-a357b215e143.png)

![image](https://user-images.githubusercontent.com/1345886/112974349-a49c8900-9152-11eb-943b-267277d71530.png)

They seem, however, **not to be taken into account** and are still highlighted in the text and in the "Problems" area.

They **work fine when added to the "User dictionary"** (I do not know where it is located, but it is correctly parsed by `cSpell`)

**Comment by Jason3S** [comment]
Please check to see if there is a `.vscode/settings.json` file in your project.

It is possible that there is a `cSpell.words` section in that file. If that is the case, then VS Code overrides the setting with the one is `.vscode/settings.json`.

**Comment by wsw70** [comment]
Thank you - yes, the file was there, with the section you mentioned (the only one by the way). Removing this file fixed the issue.
