### ISSUE TITLE
File "is spell checked" – but do not shows any errors (suddently stopped to work)

### ISSUE THREAD

**Issue by olegolegoleg** [streetsidesoftware/vscode-spell-checker#812]
Hi, file marked as "is spell-checked", but do not shows any errors:

![image](https://user-images.githubusercontent.com/7686755/114530108-5065ce80-9c53-11eb-93ee-2cde1343457c.png)

SpellCheck suddenly stopped working for no visible reason. I even did not notice, when the error has been occupied.
I have tried to re-enable several times, modify settings, anything no luck.

**Comment by olegolegoleg** [comment]
I found the problem, it was due to one option of the VS Code's settings – `settings.json`. In my case:

```
"cSpell.customFolderDictionaries": [
        {   
            "path": "${workspaceFolder:client}/.vscode/settings.json",
            "addWords": false,
            "description": "Temporary recovery of the dictionary before Windows installation.",
            "name": "TempBeforeInstall"
        }
    ],    
```

When this single option is removed everything is working fine. The strange is that when it was added, all was working fine!
I hope this can help someone with similar issue.

**Comment by Jason3S** [comment]
@olegolegoleg,

I'm glad you found the issue.

I don't think think `cSpell.customFolderDictionaries` would have worked as you expected.
It is intended as a way to load custom word lists. A word list is just a text file with one word per line. `.vscode/settings.json` is a `.json` file.

Even so, it should not have caused things to stop working.
