### ISSUE TITLE
Next release date

### ISSUE THREAD

**Issue by glen-84** [streetsidesoftware/vscode-spell-checker#815]
I'm just curious when the next release will occur, as I'm using `cspell.config.js` files, but the extension is using an old(er) version of the library that doesn't support these files (AFAIK). Thanks!

**Comment by Jason3S** [comment]
It is currently in progress. You can try out the new version if you like: [Releases · streetsidesoftware/vscode-spell-checker](https://github.com/streetsidesoftware/vscode-spell-checker/releases)
If you download the v2 [code-spell-checker.zip](https://github.com/streetsidesoftware/vscode-spell-checker/releases/download/v2.0.0-alpha.2/code-spell-checker.zip) and unpack it. You can install the extensions from the included `.vsix` file.

When it is officially released, VS Code will replace the pre-release version.

**Comment by glen-84** [comment]
I just tried this, but it doesn't seem to read my `cspell.config.js` files.

**Comment by glen-84** [comment]
This is working with `alpha.3`, thanks! 🙂
