### ISSUE TITLE
Incorrect suggestions for "Inprogress" with UK dictionary in C file

### ISSUE THREAD

**Issue by BillDenton** [streetsidesoftware/vscode-spell-checker#83]
Invalid words suggested for "Inprogress" (I meant to type In progress:
Onprogress
Noprogress
Einprogress
Dadprogress
Inproghits
This is using the UK dictionary and in a C file:
"cSpell.language": "en-GB"

**Comment by Jason3S** [comment]
I haven't checked, but I am sure these are coming from the C dictionary.

The C dictionary was build from the standard C libraries.  It looks like a bit of junk came along for the ride.

**Comment by Jason3S** [comment]
For example:
`onprogress` and `noprogress` are event names.
`einprogress` is part of `APR_STATUS_IS_EINPROGRESS`, see [APR_STATUS_IS_EINPROGRESS](https://apr.apache.org/docs/apr/0.9/group__APR__STATUS__IS.html)

You are right, they are not actual words, but they are part of the C libraries.  I am not sure which way to go in these cases.

**Comment by BillDenton** [comment]
They appear to be part of the Apache. As I'm not using anything Apache, I wouldn't expect them to appear. However, some people will be using Apache. Two thoughs:
1. Breaking the C language support into multiple configurable parts, so that for example support for Apache could be disabled.
2. Allowing word to case sensitivity to be put in the dictionary. So for example EINPROGRESS would only be accepted if in uppercase.

**Comment by BillDenton** [comment]
Also found "inital", which should have been initial. I would guess that this is a mistake in the dictionary.

**Comment by Jason3S** [comment]
Hey Bill,
Thank you.  I'm still working on the trace utility that will show you where these errors are coming from.

It looks like some words need to be cleaned out of the C dictionary.

**Comment by Jason3S** [comment]
This issue has grown a bit stale.
