### ISSUE TITLE
Software terms in YAML files

### ISSUE THREAD

**Issue by momt99** [streetsidesoftware/vscode-spell-checker#868]
I'm not sure it is the cause or not but in a `gitlab-ci.yml` file in our project, some words are unknown which can be found in the software terms dictionary.
For example "integration" and "nuget".
![image](https://user-images.githubusercontent.com/27495015/118388331-00ef3580-b639-11eb-9c97-f03e95268422.png)
![image](https://user-images.githubusercontent.com/27495015/118388337-12384200-b639-11eb-850e-3d6c5315f6ef.png)

--------
version: v1.10.2

**Comment by Jason3S** [comment]
@momt99 

Please check your `cspell.json` configuration to see if there are any expressions in `ignoreRegExpList` that might cause the issue.

If you include your config, I might be able to help.

The reason I think the issues might be caused by `ignoreRegExpList` is because `IntegrationTests` is only partially underlined.

This is what I get:
![image](https://user-images.githubusercontent.com/3740137/118399023-6e13c280-b65b-11eb-9b9e-5b0bbf2c2675.png)

If I misspell `integration`:
![image](https://user-images.githubusercontent.com/3740137/118399043-7ff56580-b65b-11eb-893c-ee7da76f326e.png)

**Comment by momt99** [comment]
@Jason3S 
> Please check your `cspell.json` configuration to see if there are any expressions in `ignoreRegExpList` that might cause the issue.
I don't think that I have set such a thing. I just have some extra words in the vscode and workspace settings.
```json
{
    "cSpell.words": [
        "DTOs",
        "Serilog",
        "workfloweng"
    ],
}
```

**Comment by Jason3S** [comment]
@momt99,

Let's see if it is only an issue with the extension or the `cspell` tool.

What happen if you do the following?:

```
npx cspell "**/gitlab-ci.yml"
```

Does it list the same errors?

If so, would you attach some debug info to this issue?

Please run
```
npx cspell "**/gitlab-ci.yml" --debug > debug.txt
```

And then attach `debug.txt` to this issue.

**Comment by momt99** [comment]
No, the error is not reported in this way. It may be a problem with the extension.

Also here's a screenshot of the preferences in the file.
![image](https://user-images.githubusercontent.com/27495015/118503195-a4c30900-b73f-11eb-85a0-856693e782ea.png)

If there are logs generated by the extension let me provide them.

**Comment by Jason3S** [comment]
I still think it might be related to a regular expression.

1. In VS Code Settings (User), turn on `cspell Experimental Enable Regexp View`.
  ![image](https://user-images.githubusercontent.com/3740137/118510127-f57f3580-b730-11eb-9015-0e4bd7852f35.png)

1. Open `gitlab-ci.yml`
2. Open the Regexp View by clicking on 
  ![image](https://user-images.githubusercontent.com/3740137/118510707-7c341280-b731-11eb-8ddc-e38eb267eef9.png)

1. You should see something like this:
  ![image](https://user-images.githubusercontent.com/3740137/118510903-b0a7ce80-b731-11eb-8b7b-d9857b06d600.png)

Please make a screen shot.

**Comment by momt99** [comment]
Here you are
![image](https://user-images.githubusercontent.com/27495015/118515655-d2fa1600-b74a-11eb-9a4f-97f68f9b4807.png)
![image](https://user-images.githubusercontent.com/27495015/118515897-0f2d7680-b74b-11eb-841b-3d437b4f8b8d.png)

**Comment by Jason3S** [comment]
thank you.

I'm not seeing any obvious problems.

**Comment by Jason3S** [comment]
@momt99,

Did you try restarting VS Code? It is possible the extension got stuck.

**Comment by momt99** [comment]
@Jason3S 
We have removed those parts temporarily, but I wrote it again now and the word "Integration" was ok this time (no error).
But "NUGET_PACKAGES", which has not been removed, is still detected as an unknown word. It's also good to point that if I add the word "NUGET" to the workspace dictionary it will be ok.

**Comment by Jason3S** [comment]
I'm glad you got it working.
