### ISSUE TITLE
[Feat] Support multi-level/multi-project workspace

### ISSUE THREAD

**Issue by luchillo17** [streetsidesoftware/vscode-spell-checker#92]
This is something common for me:
![image](https://cloud.githubusercontent.com/assets/9698639/26108025/d6eba9d8-3a10-11e7-8fe0-b63a06e20f17.png)

Opening the workspace so that i can see all my projects there, however they should have their own `.vscode` workspace config.

The issue is when i use the `Add: "something" to project dictionary`, when i use that, such word is saved towards the Full Workspace dictionary instead of the Project one.

In the image above i wanted it to save it into the second `.vscode` config, allowing me to commit such dictionary to git, but this plugin always hit's the top most `.vscode` config.

Is it possible to detect the nearest config from the file from which the dictionary addition event was triggered?

**Comment by Jason3S** [comment]
I can see how this would be useful. I am not quite sure how to do it in a way the works for everyone.

**Comment by luchillo17** [comment]
Maybe on such command check 1 level below before going to the workspace `.vscode` folder? after all the idea is when the workspace contains multiple folders which each represents a project.

About compatibility, make it an `Opt-in` feat, by default it could stay like now, while if we config a flag then it would check the 2 level folders taking in account current file path before the workspace config.

Say my file is in `${workspace-path}/newProject/src/file.js`, then default would go for `${workspace-path}/.vscode` and the Opt-in one would check if `${workspace-path}/newProject/.vscode` folder exists before going for the workspace one.

**Comment by Jason3S** [comment]
I believe something like this is supported.
