### ISSUE TITLE
Add setting to disable showing "Unknown word" text inline in editor

### ISSUE THREAD

**Issue by deadlydog** [streetsidesoftware/vscode-spell-checker#937]
I want to have unknown words underlined with the blue scribble, but don't want the `"buildscripts": Unknown word.` text to show up inline in the editor (see screenshot below).

![image](https://user-images.githubusercontent.com/1187140/121412826-55c55980-c922-11eb-8d1a-f2ec0f3a9ea9.png)

Is there a way to disable that inline text from showing up in the editor? Perhaps there is a setting to disable this already and I'm just missing it?

Thanks for the great extension!

**Comment by Jason3S** [comment]
@deadlydog,

I have not seen that before. I think it is part of VS Code inlining warnings and errors.

What version of VS Code are you using?

**Comment by deadlydog** [comment]
Hmmmm, that's odd, as if I just disable the `Code Spell Checker` extension then the inline text goes away (along with the blue squiggle).

You're probably right though that it's VS Code (or another extension) creating the inline text when this extension reports the word as an issue. Changing this extension's `C Spell: Diagnostic Level` setting changes both the color of the squiggle and the inline text.

Here's my VS Code info.

![image](https://user-images.githubusercontent.com/1187140/121551265-bad58980-c9cc-11eb-855e-b9572ca30836.png)

**Comment by deadlydog** [comment]
Ahhh, I tracked it down. I recently installed the [Error Lens](https://marketplace.visualstudio.com/items?itemName=usernamehw.errorlens) plugin, and that's what's doing it. Sorry to bother you with this. Sorry to bother you with this. Thanks!

**Comment by Jason3S** [comment]
It makes sense that Error Lens would be displaying the messages.
