### ISSUE TITLE
"Add item" now shows a select/dropdown rather than a text entry field

### ISSUE THREAD

**Issue by patrickhlauke** [streetsidesoftware/vscode-spell-checker#943]
![The 'add item' form, showing a select rather than a text entry field](https://user-images.githubusercontent.com/895831/121802897-c9bf7480-cc36-11eb-9a68-e346db280d30.png)

Not sure when it started, but noticed today that for all the settings that have an "Add item", the form now shows a select/dropdown field rather than a text entry field, making them all unusable.

Using VSCode Insiders 1.58.0

**Comment by Jason3S** [comment]
Please file an issue with VS Code. Nothing has changed with the extension recently.

As a workaround, you can always edit VS Code settings the file directly.

**Comment by patrickhlauke** [comment]
While it's true the extension itself hasn't changed recently, it may be related to some change/new requirement for extension configuration declarations https://code.visualstudio.com/api/references/contribution-points#Configuration-schema

**Comment by patrickhlauke** [comment]
Closing, as this is indeed a bug in VSCode itself (and a fix should be coming in the next release)

**Comment by Jason3S** [comment]
@patrickhlauke Thank you for looking into it.
