### ISSUE TITLE
Adding custom language dictionary

### ISSUE THREAD

**Issue by MormonJesus69420** [streetsidesoftware/vscode-spell-checker#965]
Hello! 
I would like to use this extension for spell checking, but I have a problem when it comes to adding custom language dictionary. I would like to enable spell checking in Norwegian, but can't figure out how to do that.  In the readme it talks about ways of adding small custom dictionaries in `txt` format, whereas a whole language dictionaries I have from hunspell are in `aff` and `dic` formats. Am I just meant to convert it into a `txt` file, or would I need to develop a custom extension like there are for German, Dutch, etc? If I need to make a custom extension, can anyone give me pointers as to where I should start?

**Comment by Jason3S** [comment]
Hello @MormonJesus69420,

There is a collection of language dictionaries found here: [streetsidesoftware/cspell-dicts: Various cspell dictionaries](https://github.com/streetsidesoftware/cspell-dicts). It includes instruction on how to build a dictionary.

Custom Dictionary extensions are found here: [streetsidesoftware/vscode-cspell-dict-extensions: VS Code Spelling Dictionary Extensions](https://github.com/streetsidesoftware/vscode-cspell-dict-extensions)

If you need help, please just open an issue in either one of those repositories.
