### ISSUE TITLE
The spell checker is crashing over and over.

### ISSUE THREAD

**Issue by Gustavolando** [streetsidesoftware/vscode-spell-checker#978]
Issue Type: <b>Bug</b>

The spell checker is crashing and some special words are not colored.

Extension version: 1.10.2
VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:28:32.912Z)
OS version: Darwin x64 18.7.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz (4 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 3|
|Memory (System)|8.00GB (1.10GB free)|
|Process Argv|. --crash-reporter-id a3133cf0-8872-4e51-8944-0c4d5ae52098|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehov:30309549
vscod805cf:30301675
binariesv615:30325510

```

</details>

**Comment by Jason3S** [comment]
@Gustavolando,

I would like to be able to help, but I need some more information.

1. Is it a new install or was it previously working and recently stopped?
2. Do you have anything in the `ignoreRegExpList` section of your config?

**Comment by Gustavolando** [comment]
Hi Jason3S,
It was working fine and recently started crashing.

This is what I have in my ignoreRegExpList:

![Captura de Pantalla 2021-06-26 a la(s) 11 37 19](https://user-images.githubusercontent.com/39180796/123521275-e3b77900-d672-11eb-9342-1b612a575e9b.png)


`
C Spell: Ignore Reg Exp List
List of regular expressions used to exclude the matching text from being checked.
Example: "0x[a-f0-9]+" to skip 0x hex values.
By default the flags are 'gim'.
You can specify them like this:
"/0x[A-F0-9]/g" to match only upper case hex numbers.
Example to match email: "<?[\\w.\\-+]+@\\w+(\\.\\w+)+>?"
`

I am using a Macbook Air, and recently I run this diagnostic tools to remove unnecessary files and stuff and deactivated a couple of demons that i thought there were related to MS Office.  I am not using office in this laptop so I removed them, but I don't know how to enable them again.  
I am also having issues with my Live Server extension, but I can open a new ticket for that later.  I just mention it in case this may help.  Live server is not showing an error, it just don't work.
I removed VS Code and reinstall it again, but issue persist.  Probably need to delete other dependencies because after reinstalling VS code, extensions remained as they were before.  I had also tried to uninstall and reinstall the live server and spell check extensions, but problem persists

**Comment by Jason3S** [comment]
@Gustavolando,

It is possible part of the extension is missing. VS Code keeps a cache of all extensions. You might need to delete that and reinstall them. See #388. 

On my Mac, they are in `/Users/jason/.vscode/extensions`.

**Comment by Gustavolando** [comment]
Hi Jason3S,

Today I removed Live Server and Code Spell Checker, closed the VS code app (right-click on taskbar + Exit), then I opened the VSC again, reinstalled both extensions and the are running fine now.  Code Spell checks works and live server is available now. 
I am not sure if there wee any special update or upgrade in my Mac. It got freeze a couple of times today,  I suspect that antivirus upgrade had something to do there, but so far mu VS code issues are gone.

This is my first ticket here in Github, so tell me if you need me to do any special close step, or filling survey before closing this issue.

**Comment by Jason3S** [comment]
I'm happy you got it working. I'll close it.
