### ISSUE TITLE
settings.json and cspell.json configuration issue when importing from a nested folder

### ISSUE THREAD

**Issue by ramarivera** [streetsidesoftware/vscode-spell-checker#996]
Hey! 

I've been using both the VsCode extension and the CLI tools and both of them rock, kudos on the project you've built 🥳 

Now for the not so happy part, I've been having some weird issues with configuring the extension.
My setup is something like:
* VsCode `settings.json` with a key of `cSpell.import` with `[ "${workspaceFolder}/folder1/folder2/cspell.json" ]`
* `cspell.json` inside of `folder1/folder2` (folder2 contains CI scripts, and it has to stay there unfortunately)

So if I have something like this on the `cspell.json` file:
```
"ignorePaths": [
    "**/node_modules/**",
    "**/.git/objects/**",
    ".vscode",
    "**/*.config.json",
],
"overrides": [
    {
        "language": "es-es",
        "filename": "**/*-es.json"
    }
]
```
And I then go to a `config.json` or `*-es.json` file, the extension will report that those files contain errors.
However, if I replace the block from before with `cSpell.ignorePaths` and `cSpell.overrides` and I paste it into the `settings.json` file, then the extension will correctly exclude the corresponding files.

So I was wondering if there's any way to keep all my config inside of my nested `cspell.json` file, or if I will need to always keep some configuration duplicated? `dictionaries` and `enabledLanguagesId` for example are correctly picked up from the `cspell.json` file, so I'm guessing the issue is with my folder structure.

Any help would be appreciated :)

**Comment by Jason3S** [comment]
@ramarivera,

There is a new version of the extension coming out soon. Please try it and tell me if it fixes the issue: [Releases · streetsidesoftware/vscode-spell-checker](https://github.com/streetsidesoftware/vscode-spell-checker/releases)

The current extension uses cSpell 4, the new version uses cSpell 5 which handles globs and ignorePaths differently.

**Comment by ramarivera** [comment]
Amazing! I'll check it out later and I'll let you know if it works

**Comment by ramarivera** [comment]
Sorry for the delay, just tried it out and it works like a charm!!
Looking forward for the release :D
