### ISSUE TITLE
Salary is unknown word

### ISSUE THREAD

**Issue by alexey-sh** [streetsidesoftware/vscode-spell-checker#997]
I'm pretty sure the word "salary" exists in English
https://www.dictionary.com/browse/salary
While the extension throws the error "unknown word salary"

![image](https://user-images.githubusercontent.com/1584156/124357581-f60e5580-dc24-11eb-8107-4c4a5dac57c4.png)

**Comment by Jason3S** [comment]
Please check your settings.

`salary` is in the spell checker's dictionary.

Did you set the language to Russian? Please make sure your set it to "en,ru" so both languages are enabled.

**Comment by Jason3S** [comment]
If you open VS Code Command Palette and run `Show Spell Checker Configuration`, it will show the settings.

Something like this:
![image](https://user-images.githubusercontent.com/3740137/124364744-cde21f00-dc43-11eb-8398-ecc6df62ad33.png)

**Comment by Jason3S** [comment]
Closing for now.
